eclair-demo/src/main/scala/fr/acinq/eclair/Globals.scala
eclair-demo/src/main/scala/fr/acinq/eclair/blockchain/ExtendedBitcoinClient.scala
eclair-demo/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-demo/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-demo/src/main/scala/fr/acinq/eclair/channel/Scripts.scala
eclair-demo/src/main/scala/fr/acinq/eclair/package.scala
eclair-demo/src/test/scala/fr/acinq/eclair/ConversionSpec.scala
eclair-demo/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
eclair-demo/src/test/scala/fr/acinq/eclair/channel/InteroperabilitySpec.scala
lightning-types/src/main/protobuf/lightning.proto
lightning-types/src/main/scala/ToStrings.scala
lightning-types/src/test/scala/lightning/NonRegSpec.scala

This makes us compatible with lightningd up to [df4df8679d956f0f4c72838412c0a676b1f91964](https://github.com/ElementsProject/lightning/commit/df4df8679d956f0f4c72838412c0a676b1f91964).

compatibility with lightningd

---

eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/Register.scala
eclair-node/src/main/scala/fr/acinq/eclair/package.scala
eclair-node/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
eclair-node/src/test/scala/fr/acinq/eclair/PackageSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/db/ChannelStateSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala

See https://github.com/lightningnetwork/lightning-rfc/pull/119

Switch to 32B channel-id

---

eclair-node/src/main/resources/gui/main/channelPane.fxml
eclair-node/src/main/resources/gui/main/main.fxml
eclair-node/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala

* Wording in announcement tabs
* Wording in channel panel: Node id becomes Remote node id

Wip gui wording

---

README.md

* Added a link to Oracle JRE download page
* Added a note for OpenJDK users

Added warning for openJDK in README.md

---

eclair-node/src/main/scala/fr/acinq/eclair/blockchain/PeerWatcher.scala
eclair-node/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

Build was randomly failing due to race issues in integration tests.

Fix travis

---

eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala

We need to put watches back even when restoring to CLOSING state, because the counterparty may have published their commitment (or a revoked) tx when we were down.

Setting watches when restoring in CLOSING state

---

eclair-node/src/main/resources/gui/main/channelPane.fxml
eclair-node/src/main/resources/gui/main/main.css
eclair-node/src/main/resources/gui/main/main.fxml
eclair-node/src/main/resources/gui/modals/openChannel.fxml
eclair-node/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/Handlers.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala

* fixed Testnet chain color in status bar
* fixed some wording

(GUI) Added an option in the GUI to open a simple connection to a node

---

eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-node/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-node/src/test/scala/fr/acinq/eclair/db/ChannelStateSpec.scala

as it is not a direct protocol parameter

LocalParams should not include maxFeerateMismatch

---

eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-node/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
eclair-node/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-node/src/main/scala/fr/acinq/eclair/router/RouterExceptions.scala
eclair-node/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

As a side effect, we now retry payments that have failed on a local channel.

Better router/channel exception handling

---

README.md
eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/Handlers.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/ReceivePaymentController.scala
eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/SendPaymentController.scala
eclair-node/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala
eclair-node/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
eclair-node/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
eclair-node/src/test/scala/fr/acinq/eclair/channel/states/FuzzySpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala

* added a dedicated payment request object
* if the amount paid is less than the amount expected, the node fails the HTLC
* if the amount paid is more than twice the amount expected, the node fails the HTLC

New PaymentRequest object + HTLC verification

---

eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala
eclair-node/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-node/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
eclair-node/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
eclair-node/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-node/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala

see https://github.com/lightningnetwork/lightning-rfc/pull/135

wire: add chainHash field to open message

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/ExtendedBitcoinClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/ChaCha20Poly1305.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/Noise.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/Sphinx.scala
eclair-core/src/test/scala/fr/acinq/eclair/crypto/NoiseSpec.scala
pom.xml

we now use spongycastle instead of bouncycastle

upgade to bitcoin-lib 0.9.11

---

README.md
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala

getinfo returns node id, node alias, port, chain hash and current block height

api: add a simple getinfo method

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala

use 8 bytes for msat amounts

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala

Previous version was weird and didn't always converge (a test was added that reproduces the issue).

Simplified computation of closing fee

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala

Reported by @btcontract in #97

Reproduced and fixed issue with different dust limits

---

eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala

Maybe display it as amountMsat(int) and description(str)? If so it should be applied to any other help lines too.

Add description to receive in help menu

---

README.md

Improved Configuration section in README

---

README.md
eclair-node-javafx/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
eclair-node-javafx/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala

Changed the logic to access the state of the channel when building the cell

(gui) Fix direction icons in the list of the known channels in network

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

getinfo is deprecated and will be removed in 0.16.

Replace getinfo with getnetworkinfo

---

eclair-core/src/main/scala/fr/acinq/eclair/FSMDiagnosticActorLogging.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-node/src/main/resources/logback_colors.xml
eclair-node/src/main/scala/fr/acinq/eclair/LogSetup.scala

This allows for easier debugging.

Use logback's MDC to display channelId in logs

---

eclair-core/src/main/scala/fr/acinq/eclair/DBCompatChecker.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala

An exception is thrown if the files are not compatible

Added a compatibility check with DB files when booting application

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/SpvWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/spv/BitcoinjKit.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/wallet/BitcoinjWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

This should avoid rejection of segwit txes.
Also, reduced some log levels.

Now requiring spv nodes to be Segwit-compatible

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/SpvWatcher.scala

Set a hard-coded timestamp for bitcoinj watched scripts

---

eclair-core/pom.xml

Make Integration tests work in macos

---

eclair-core/pom.xml
eclair-node-gui/pom.xml
eclair-node/pom.xml
pom.xml

use scala plugin 3.3.1 (mvn scala:console now works)
add Dominique to the list of developpers

back to 0.2-SNAPHOT

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

Base checks in `sendAdd` on the *last* sent sig

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

This fixes #173 (for good this time).

Store state when receiving a `CommitSig` in state SHUTDOWN

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/wallet/BitcoinCoreWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

Rework channel closing logic

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/SpvWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/NetworkEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/ThrottleForwarder.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

Prune stale network announcements

---

README.md
eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala

Fix doc for api call `connect`/`open`

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProvider.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProviderSpec.scala

and set it as default, keeping earn.com as fallback.

Added bitgo fee provider

---

eclair-core/src/test/resources/application.conf
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

Making sure we don't reproduce #242.

Add test on signing a single `Updatefee` with no other updates

---

eclair-node-gui/src/main/resources/gui/modals/openChannel.fxml
eclair-node-gui/src/main/resources/gui/modals/receivePayment.fxml
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ReceivePaymentController.scala

Units are hardcoded in different places, which causes problems. Now using the labels from `CoinUtils`, next step would be to use localized properties

[Gui] Centralize units labels from CoinUtils values

---

Dockerfile
README.md

Add `entrypoint.sh` to eclair with extensibility point to setup the configuration.

Entrypoint for dockerfile and documentation to setup the eclair.conf

---

eclair-core/src/main/resources/reference.conf
pom.xml

This sets more reasonable defaults for routing fees.
Reported by @mably.

Reduce default fees

---

eclair-node-gui/pom.xml
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ReceivePaymentController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/CoinUtils.scala
eclair-node-gui/src/test/resources/logback-test.xml
eclair-node-gui/src/test/scala/fr/acinq/eclair/gui/utils/CoinUtilsSpec.scala

This PR affects the _open channel_ window and the _receive payment_ window.

[GUI] Default unit should be milliBTC

---

README.md
eclair-node-gui/src/main/resources/gui/modals/nodeInfo.fxml
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxPreloader.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/NodeInfoController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ReceivePaymentController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/SendPaymentController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/stages/NodeInfoStage.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/GUIValidators.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/QRCodeUtils.scala
eclair-node-gui/src/test/scala/fr/acinq/eclair/gui/utils/CoinUtilsSpec.scala

[gui] Various gui fixes

---

README.md
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala

It is not verified/used in the code.

Remove api.user

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinJsonRPCClient.scala

The error message didn't give much indications as to what was wrong and how to fix it.

Indicate that wallet mode is needed before exiting

---

README.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-node-gui/src/main/resources/application.conf
eclair-node-gui/src/main/resources/gui/main/channelPane.fxml
eclair-node-gui/src/main/resources/gui/main/main.css
eclair-node-gui/src/main/resources/gui/main/main.fxml
eclair-node-gui/src/main/resources/gui/main/notificationPane.fxml
eclair-node-gui/src/main/resources/gui/modals/sendPayment.fxml
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/Handlers.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/NotificationPaneController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/NotificationsController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ReceivePaymentController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/SendPaymentController.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/CoinUtils.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/GUIValidators.scala
eclair-node-gui/src/test/scala/fr/acinq/eclair/gui/utils/CoinUtilsSpec.scala
eclair-node/src/main/resources/logback_colors.xml

This PR fixes various issues in the GUI. The most interesting part is the addition of a user variable `eclair.gui.unit` which define a bitcoin unit in which all the displayed amounts are converted. By default, this unit is `btc`.
fixes #335 #332 #347 #314

Various GUI Improvements

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/DBCompatChecker.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/SimpleSupervisor.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/NetworkEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteNetworkDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
eclair-node-gui/src/main/resources/gui/main/main.fxml
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala

Fix issues with gui being updated from wrong threads
Add more logging to SimpleSupervisor to ensure any actor crashes
are logged.

Add channel fees and capacity to Channel GUI

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
eclair-node/src/main/resources/application.conf

And changed akka default log level from `DEBUG` to `INFO`.
`LoggingFSM` were great for debugging but they come at a high performance cost so it's time to get rid of them.

Replaced `LoggingFSM` -> `FSM`

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProvider.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProviderSpec.scala

It supports mainnet/testnet fees.

Use bitgo API v2 to get network fees

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

Also, renamed `getBlacklistedChannels` to `getIgnoredUpdates` and added
test.

Fixed bug in ignored channel computation

---

BUILD.md

fixes #478 and supersedes #450

build: Specify that we need at least 1.8u161 to build

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala

see https://github.com/lightningnetwork/lightning-rfc/pull/397
fixes #474

Use `lnbcrt` prefix for regtest

---

eclair-core/pom.xml
pom.xml

It may even fix https://github.com/akka/akka-http/issues/1459.

Updated dependencies

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

In order to reduce gossip spam.

Send `channel_update` once every 7 days instead of every day

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPool.scala

Electrum client should not resolve addresses when reading server list ; instead resolution is now made only when attempting connection.

Resolve Electrum server address only when connecting

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

Support signing multiple similar/identical HTLCs

---

README.md

Update docker link

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumEclairWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSimulatedClientSpec.scala

This will let us display the wallet's xpub and its path on eclair-wallet.

Electrum wallet: export xpub

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala

Fixed conversion: 1 BTC = 1e8 satoshis

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-node/src/main/resources/application.conf

Fixes #577 
The issue can reliably be reproduced with the help of [stress](https://people.seas.harvard.edu/~apw/stress/), and those timeouts increase solve the issue in my box.
EDIT: the timeouts also happen when bitcoind is catching up with block, using most of my 2 CPUS  and IO available....

Increase startup timeout

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala

this is copied from #592, which will be merged later and includes additional tests for our electrum wallet, including a specific test for this issue.

Electrum wallet: fix balance computation issue

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala

We should return a `FeeInsufficient` error when an incoming htlc doesn't
pay us what we require in our latest `channel_update`.
Note that the spec encourages us to being a bit more lax than that (BOLT
7):
> SHOULD accept HTLCs that pay an older fee, for some reasonable time
after sending channel_update.
>    Note: this allows for any propagation delay.

Check when relay fee is insufficient

---

eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

Fix for https://github.com/ACINQ/eclair/issues/630

Fix scala.NotImplementedError when public-ips config parameter contains invalid values

---

eclair-core/src/main/scala/fr/acinq/eclair/Logs.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/resources/logback-test.xml
eclair-node/src/main/resources/logback.xml
eclair-node/src/main/resources/logback_colors.xml

Whenever possible, we provide context about the peer or the channel in various parts of the app.

Added context to logs

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

And min_final_cltv_expiry is defined BOLT 11(not BOLT 7)

Fixed default min_final_cltv_expiry value

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala

Needless to say this is far more efficient than what we were previously doing.
h/t @n1bor

 Get full blocks when looking for spending tx 

---

BUILD.md

Mention Docker in our build instructions (fixes #669)

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/FailureMessageCodecsSpec.scala

This is better reviewed commit by commit, as there are three distincts fixes.

Multiple fixes in payment lifecycle

---

.travis.yml
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

See #703, this is not a definitive fix (couldn't reproduce at will) but should facilitate debugging.

Improve integration tests

---

eclair-core/pom.xml
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala

Bitcoind 0.16.0 is no longer available

Tests: use bitcoind 0.16.3

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala

Bitcoind returns version as MMmmrr (major, minor, revision), use an int representation and compare it to our minimum version target.
This will help users run new versions of bitcoin core (but there will probably be additional steps to follow, since each new bitcoin code version incudes behaviour changes, deprecates or removes RPC calls, ...) 
See #730

Simplify bitcoind version check

---

README.md
eclair-core/eclair-cli

Minor changes. Typos and grammar corrected.

Updated readme.md

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

This is the second and simplified attempt to implement https://github.com/lightningnetwork/lightning-rfc/pull/508#discussion_r233429207, this time `Peer` just waits for `Pong` and disconnects a remote peer if `Pong` does not arrive within 10 seconds.

Disconnect peer if it does not reply to our Ping messages

---

eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/EarnDotComFeeProviderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsBatchValidationSpec.scala

Okhttp works better on Android.

Switch sttp backend async-http-client -> okhttp

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala

As turned out in https://github.com/lightningnetwork/lnd/issues/2232 both BLW and Eclair currently do not take HTLC direction in account when doing `maxHtlcValueInFlightMsat` checks. This PR fixes an issue.

Make maxHtlcValueInFlight checks directional

---

contrib/eclair-cli.bash-completion

Update bash completion

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

Fixes the flaky test in integration spec

Fix flaky test in IntegrationSpec

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala

There was a unit mismatch. Added a test.

Fixed computation of available balance

---

eclair-core/src/main/scala/fr/acinq/eclair/Logs.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala

Added context, and log socks5 as info.

Better error logs for socks5 proxy

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

Move the param 'randomize' from RouteRequest to RouteParams, the configuration is not affected.

Rework route params

---

.travis.yml

This matches the scala library target used in the main pom.xml

Upgrade scala library target on travis: 2.11.12

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/api/OldService.scala

Move GetInfoResponse and AuditResponse out of the api package
Fix parameter handling for audit() and networkFees()

Minor API fixes

---

eclair-core/eclair-cli

Eclair-cli was not working as advertised in the documentation, this PR fixes the behavior.

Fix eclair-cli to work with equal sign in arguments

---

README.md

This has somehow been missed by PR #826.

Update readme with bitcoin 0.17 instructions

---

eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/IndexedObservableList.scala

Fixed concurrency issue in `IndexedObservableList`

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/Autoprobe.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/FailureMessageCodecsSpec.scala

See https://github.com/lightningnetwork/lightning-rfc/pull/516 and https://github.com/lightningnetwork/lightning-rfc/pull/544

Replace UnknownPaymentHash/IncorrectPaymentAmount with IncorrectOrUnknownPaymentDetails

---

README.md

Update link for recommended JDK

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/resources/integration/bitcoin.conf

Make Bitcoin Core bind on localhost in tests

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/TlvCodecs.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/TlvCodecsSpec.scala

Hide some internals (tlvFallback, generictlv codecs).
Add a length-prefixed tlv stream codec.

Add a few improvements to tlv.

---

BUILD.md
README.md

* Clean-up the readme formatting warnings
* Update the OpenJDK 11 link everywhere
* Added a section linking to our wiki and API doc
* Most of the wiki pages have been updated prior to this PR

Documentation update

---

eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala

The spec PR was updated to modify the feature bits in the official test vectors.

Update invoice test vectors

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala

When paying a multi-part payment, we tell the PaymentLifecycle to use a route prefix that contains the first hop (for example a -> b via channel 1).
We need to also tell the router to ignore the nodes that are in the route prefix, otherwise when retrying it may try some completely dumb routes that have no chance of succeeding.
For example if we have the following network:
```
A -------> B
|         |
|         v
`------> C
```
A sends a multi-part payment to C. It will send as much as possible via the direct channel A -> C and will send the rest via A -> B and let the router find the rest of the route.
If the channel B -> C doesn't have enough capacity, the retry would yield the following (useless) route: B -> A -> C. We want to prevent the router from doing this by telling it to ignore …

PaymentLifecycle should tell the router to ignore route prefix

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala

See
https://about.gitlab.com/blog/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/

Added blank lines to minimize conflicts

---

.travis.yml
Dockerfile

This fixes the failing builds.

Update Maven (3.6.3)

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

Instead of sending messages to the connection actor, we put them in a
list and send during transitions, like it's done elsewhere in the
channel actor.

More consistency in sending messages during sync

---

eclair-core/src/main/scala/fr/acinq/eclair/db/AuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/ChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PendingRelayDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingRelayDb.scala

They are used by our mobile applications.

Restore missing 'db.close()' methods

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

There is currently a backwards-compatibility issue with eclair-mobile.
Eclair-mobile mistakes feature bit 15 (payment_secret) for the
gossip_queries_ex prototype (which is incompatible with the spec-ed version).
To temporarily avoid this issue (until eclair-mobile is patched and all users have updated),
we never advertize those ambiguous bits in Init.
They're only really needed in the invoice so it's ok.

Avoid sending PaymentSecret/MPP in Init

---

CONTRIBUTING.md
SECURITY.md

Add instructions for contributing and reporting security issues.
Greatly inspired by Bitcoin and LND.

Add contributing instructions

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

This is needed to make sure we broadcast our own gossip.
Otherwise we will try to gossip at the beginning of the connection,
when the peer hasn't set any timestamp, so our gossip will be dropped.
See https://github.com/lightningnetwork/lightning-rfc/pull/684
Tested against:
- lnd v0.9.0-rc3
- c-lightning master

Broadcast gossip regardless of timestamp filters

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala

This is an alternative to #1302.

Payment request: ignore fields with invalid length

---

eclair-core/src/main/scala/fr/acinq/eclair/PimpKamon.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Auditor.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartPaymentFSM.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala

Consolidate and add payment metrics.
This can be reviewed commit by commit, each commit is scoped to a specific area of the codebase.
That will allow building many graphs that will be helpful when doing A/B testing with path-finding algorithm changes, and will allow easy alerting on many payment KPIs.
Please bikeshed the names, as changing those will require updating all the graphs that rely on them, so it's better to get them right from the start (as much as possible).

Payment metrics

---

eclair-core/src/main/scala/fr/acinq/eclair/Logs.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala

Following the change made with #1347.

Minor: removed unused code

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BatchingBitcoinJsonRPCClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala

Add a metric to track wallet balance.
Add a few channel metrics.
Tweak RPC metrics.

Add wallet balance metric

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala

Just less repetition and a better comment.

fixup! Harden requirements on htlc-minimum-msat (#1339)

---

.travis.yml
pom.xml

Latest scala version has a bug [1] that breaks build on windows.
[1] https://github.com/scala/bug/issues/11955

Downgrade to scala 2.13.1

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartPaymentFSM.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Announcements.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/StaleChannels.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Sync.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqlitePaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RoutingSyncSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala

This is a low hanging fruit, it is portable to android.

`Platform.currentTime`->`System.currentTimeMillis`

---

eclair-node-gui/src/main/resources/eclair-node-gui.sh
eclair-node/src/main/resources/eclair-node.sh

Fixes https://github.com/ACINQ/eclair/issues/1421

Fix eclair-node.sh for OSX

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala

When a new connection happens while already connected, the `Peer` will
switch to the new connection.
In the current implementation, upon receiving a `ConnectionReady`, the
`Peer` will kill the current connection, then sends back the
`ConnectionReady` message to itself. In the meantime, the
`PeerConnection` will happily forward any incoming messages to the `Peer`.
This opens up to a race in the `Peer`'s mailbox between the
`ConnectionReady` message, and any incoming messages from the new
connection. If the latter win, they will get dropped because the `Peer`
is in state `DISCONNECTED`. Typically those are `ChannelReestablish`
messages and channels will get stuck in state `SYNCING`.
This PR make the `Peer` atomically switch to the new connection, without
going back to the `DISCONNECTED` …

Atomically switch to new connection

---

eclair-core/src/main/scala/fr/acinq/eclair/db/BackupHandler.scala

They are very spammy and not useful.

Reduce log level of backup handler

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala

This is a first step before actually deciding how we can improve our tolerance to remote feerate mismatch.

Monitor on-chain feerate mismatch

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/CltvExpiry.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala

Improve comments and explanations in various places.
This is a simpler alternative to #1452

Increase fulfill safety window

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/db/FileBackupHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPendingRelayDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingRelayDb.scala

Akka 2.4 introduced a non-blocking bounded mailbox.
It makes sense to upgrade the backup handler to that mailbox type.
We also add DB metrics and wrap interesting calls.

Update backup handler and add DB metrics

---

.github/workflows/main.yml
codecov.yml

@t-bast 9454540 "revive codecov.yml" 🙄

Use wildcard for codecov files

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala

Fix typo related to pico-bitcoin conversion

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala

We were previously returning TemporaryNodeFailure for trampoline payments to neighbour nodes with depleted liquidity. This prevented us from finding alternative, indirect routes.
In such cases, we now roughly estimate whether the fee is "big enough" to allow finding alternative routes; if not we ask the sender to raise the fee before telling them we're lacking liquidity.
A more costly alternative that we may implement in the future would be to run the path-finding to find a route without bounding the fee, and send that information back to the sender.

Trampoline relay exhausted liquidity

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

The downstream HTLC-timeout integration test was sometimes hanging waiting for the local commit tx to appear inside the mempool.
The reason was that the remote peer was also trying to get its version of the commit tx in the mempool, and when it won that race we weren't testing the right thing.
Simply disconnecting the two nodes fixes the issue as it ensure only the local node will be broadcasting his commit tx.

Fix flaky integration test

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala

We can be less repetitive given that we now have a `relayId` that we can
use to factor all info.

Improve relayer logs

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala

This is mostly about cleaning up useless logs.

Minor improvements to the watcher

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala

Sometimes logs are more useful than just comments.

(minor) Improve logs in channel relayer

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala

It was missing a sender ActorRef.

Fix forceclose API

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

Fix empty replyTo in `update_relay_fee`

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerEvents.scala

It's useful for plugins to know this to do some basic anti-spam for example.

Remote address in ConnectionInfo

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala

We track the following metrics:
* Total utxos amount
* Number of utxos
* Split by status: unconfirmed, unsafe, safe and confirmed

Add metrics to track utxos

---

eclair-node/src/main/resources/application.conf

It only needs to be enabled in cluster mode.

Disable the distibuted pubsub extension by default

---

eclair-node/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/JsonSerializersSpec.scala

A recent refactoring to include a `replyTo` parameter made the JSON serialization ugly and hard to work with.
Fixes #1611

Fix htlc origin JSON serialization

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala

We need to manually set the MDC in `onTermination` handler because the `StopEvent` isn't processed like a regular message by the actor.

(Minor) Improve logs

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

If the `eclair.conf` changes while we're offline, we want to apply the fee changes to existing channels once they come back online.

Update relay fees from eclair.conf

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala

The routing hint we get in a Bolt 11 invoice may be obsolete when we attempt the payment: one of the nodes in the route may have updated his relay fees.
Since this affects a private channel that is not kept in the routing graph, we need to update the routing hints before injecting them in the router. This was already done in `PaymentLifecycle` with automatic retries, but when using MPP we retried in the `MultiPartPaymentLifecycle` instead of inside the `PaymentLifecycle`, so we need to handle routing hints updates there.
NB: don't forget to cherry-pick this commit on the `android` branch to ensure `eclair-mobile` gets this fix.

Remote failure updating routing hint

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

Fixing those small warnings one by one in unrelated PRs makes reviews more difficult.

Address all intellij warnings for Channel.scala

---

eclair-node/src/test/scala/fr/acinq/eclair/api/JsonSerializersSpec.scala

Need a tweak to make tests pass on Windows.

fixup! Rework XxxCommitPublished types (#1728)

---

source/index.html.md

This is a draft of specifying units of fields that are not obvious.
Closes #1739
I inferred the units from context, so please double-check if it's correct. Also please LMK what unit to specify for `htlcMinimum`.

Attempt to clarify units in docs

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala

Ensure that we only visit each node once in Dijkstra's algorithm.

Fix implementation of Dijkstra's algorithm

---

eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/RelayerSpec.scala

We need to wait for the channel relayer to be registered to the event stream before publishing an event, otherwise the channel relayer will never receive it.
We send it a first message and wait for its response to ensure it had time to correctly initialize.

Fix flaky relay-htlc-add test

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Payment.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

Add an option to block until the payment completes to the `payinvoice` API.
This can be simpler to use for payments that complete quickly than polling the inefficient `getsentinfo` API.

Add blocking option to payinvoice API

---

.gitignore
eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/NetworkDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PeersDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PendingRelayDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteFeeratesDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteFileBackupHandlerSpec.scala

Commits are best reviewed independently.

Database nits

---

README.md

I'll add two of mine later once documentation is there and it's made sure they work as intended.

Add a list of plugins

---

eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/PluginParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala

As discussed at https://github.com/ACINQ/eclair/pull/1791#discussion_r630997260

Remove ConnectionControlPlugin trait

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdogSpec.scala

We want to check secondary blockchain sources when we haven't received blocks in a while.
Thanks @engenegr and @btcontract for raising this.
Fixes #1803

Check blockchain watchdogs regularly

---

eclair-core/src/main/scala/fr/acinq/eclair/db/DbEventHandler.scala

That error can get spammy because it will be emitted at every block for
every channel, and it doesn't bring a lot of value to store it anyway.

Do not store `CannotAffordFees` errors

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala

Otherwise the creation of the jdbc url check file for postgres fails.

Create the chain directory

---

source/index.html.md

Document status type in /getreceivedinfo, /getsentinfo

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala

This test was added to lightning-kmp where this case wasn't correctly handled: https://github.com/ACINQ/lightning-kmp/pull/278
It is correctly handled by eclair, but an additional test doesn't hurt.

Additional reestablish test

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

We didn't handle shutdown messages in the negotiating state, whereas they may be received upon reconnection. This created some unnecessary warnings in the logs.

Handle shutdown retransmit when negotiating

---

eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala

There's a very annoying race condition in that test, and we can end up emitting events twice on slow machines. This isn't an issue so we stop verifying that we avoid duplicate events.

Fix ZmqWatcher flaky test

---

eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

Fix isNode1 in tests

---

docs/Tor.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala
eclair-core/src/main/scala/fr/acinq/eclair/tor/Socks5Connection.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdogSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/tor/Socks5ConnectionSpec.scala

Fixes https://github.com/ACINQ/eclair/discussions/1947

Make Tor optional for blockchain watchdogs

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelFeatures.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelFeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

A few minor changes and refactoring. Best reviewed commit-by-commit.

Minor changes

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala

The fee that's recorded in the path-finding metrics should count the local channel. Without it we record failing payments with a fee budget larger than the fee recorded for the successful payment to the same node.

Count local fees in path finding metrics

---

eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

As usual, the race condition is due to a delay before subscribing to the event stream.

Fix race condition in 'stream updates to front' test

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala

Whenever a remote commitment is confirmed in which we received htlcs, we generate a claim-htlc-success transaction even if we don't have the preimage yet (so we can't broadcast it).
This created a confusing log line:
```log
tx generation success: desc=claim-htlc-success
```
We want to create that log line only when we have the preimage and the node operator can expect the HTLC to be redeemed on-chain.
This confusion happened in the investigation of #2070

Remove misleading claim-htlc-success log

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/MessageRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/Postman.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/MessageOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/OnionMessagesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Message.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/serde/FormParamExtractors.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

In preparation for offers, add a postman that listen to incoming replies and delivers them to the right actor.

Process replies to onion messages

---

.github/workflows/docker-image.yml

Publish docker images for master branch with tag `latest`

Publish docker images

---

eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelFeatures.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/package.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

Best reviewed commit by commit.

(Minor) Nits

---

eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala

Instead of always using the last known peer address from the `PeersDb`,
we randomly pick the address from the `PeersDb` and the `NetworkDb`.
We use clearnet or tor addresses depending on the node configuration:
- tor not supported: always use clearnet addresses
- tor supported but not enabled for clearnet addresses: use clearnet
addresses when available
- tor supported and enabled for clearnet addresses: use tor
addresses when available

Choose node address at random when reconnecting

---

eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteUtilsSpec.scala

This is an alternative to #2152.

Have sqlite also write to jdbc url file

---

docs/PostgreSQL.md
eclair-core/pom.xml
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/jdbc/JdbcUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/CompareAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/CompareChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/CompareDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/CompareNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/ComparePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/ComparePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/ComparePendingCommandsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigrateAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigrateChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigrateDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigrateNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigratePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigratePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigratePendingCommandsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingCommandsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/DbMigrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/DualDatabasesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteUtilsSpec.scala

Add a migration tool and a step-by-step guide for users who want to switch from Sqlite to Postgres.
That's a lot of code, but it's always the same things. I suggest starting with `ComparePeersDb`/`MigratePeersDb`.

Database migration Sqlite->Postgres

---

docs/release-notes/eclair-vnext.md
eclair-core/pom.xml
eclair-front/pom.xml
eclair-node/pom.xml
pom.xml

Back to Dev

---

eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinJsonRPCClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/ExplorerApi.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestBitcoinCoreClient.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/watchdogs/ExplorerApiSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsBatchValidationSpec.scala
eclair-node/pom.xml
pom.xml

This updates versions of a few major dependencies: scala, akka, postgres, etc.
Supersedes #2160.

Update a few dependencies

---

eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala

Show details that lead to this exception.

Better logging for NegativeProbability exception

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala

Building an inconsistent intermediate `RemoteCommitPublished` object was error-prone and defeats the purpose of strong typing.
We also handle the `paysDirectlyToWallet` case directly in the method, which enables a nice factorization and better contains this now deprecated feature.
⚠️ This is a trivial change, but it touches sensitive parts of the code. Please review extra carefully.

Refactor `Closing.claimRemoteCommitMainOutput()`

---

docs/release-notes/eclair-vnext.md

Add delayed fees to release notes

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala

This is a classic race condition that can appear when we register to
events in tests. We need to make sure that the subscription is taken
into account before moving forward.

(Minor) Fix timeout in tests

---

eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt11Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt12Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/MessageOnion.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/Offers.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/TlvCodecs.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt12InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/OffersSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/serde/FormParamExtractors.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
pom.xml

Add types for representing offers and Bolt12 invoices (https://github.com/lightning/bolts/pull/798)

Add Bolt12 types and codecs

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version0/ChannelCodecs0.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version1/ChannelCodecs1.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version2/ChannelCodecs2.scala

Only define decode method in legacy codecs

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/RestoreSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

Remove unused `LocalChannel` class in the router

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitor.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala

There was a race condition when testing fee-bumping: we could emit the new block event before the underlying actor (`MempoolTxMonitor`) registered to this event type.
This is fixed by emitting the `TransactionPublished` event after registering to the new block events, and waiting for that in tests before publishing a new block event.

Fix flaky replaceable tx publisher tests

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala

Our mechanism to detect double-spending wasn't correctly taking into account unconfirmed inputs. This was only used in single-funder scenarios so it could only be an issue in rare edge cases, where it would not lead to any loss of funds as we keep commit tx data in our DB even for closed channels.
The second commit is a refactoring that introduces an `isTransactionOutputSpent` function, let me know if you like it, otherwise we can just keep the first commit alone. In the future, once (if) we have https://github.com/bitcoin/bitcoin/pull/24539 we can update `isTransactionOutputSpent` and `doubleSpent` with a `minDepth` parameter to make them reorg-safe(r).

Improve wallet double-spend detection

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala

Addresses https://github.com/ACINQ/eclair/issues/2260 and https://github.com/ACINQ/eclair/issues/2259.
Not tested yet on mainnet node with remote Bitcoind.

Configurable watchdog and batching

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala

Before eclair v0.6.0, we didn't store a mapping between `htlc_id` and htlc txs, which made it tricky to correctly remove identical htlcs that used MPP during force-close, when an htlc tx was confirmed.
We have added that mapping since then and released it more than one year ago, so we can now safely remove that code.

Remove legacy force-close htlc matching

---

monitoring/grafana-dashboard/akka-metrics.json

In this PR I have added `akka-metrics.json` file to monitor akka metrics in grafana dashboard. 
- Channels (4 panels)
- Register (4 panels)
- Peers (4 panels)

Add akka metrics grafana dashboard

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala

May be useful in feature branches.

Add a `ChannelOrigin` placeholder

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala

In case feeRatePerKw is high and liquidity is low on the initiator side, the initiator can't send anything and the test would fail because we try to create a HTLC for an amount of 0.

Fix flaky CommitmentsSpec test

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/ClientSpawner.scala
eclair-core/src/test/resources/logback-test.xml
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/testutils/FixtureSpec.scala

Best reviewed commit by commit. Those are minor changes that mostly touch tests.

Reduce diff with feature branch

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/RouteBlindingSpec.scala

Note that this is a PR on #2499, that contains fixes and refactoring for my comments on that PR.
Let me know if something looks weird or doesn't make sense.

Improve Bolt 12 invoice building from intermediate nodes

---

eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

Keep at most one scheduled `LiftChannelExclusion` by cancelling the previous one if the new ban lasts longer

Cancel previous `LiftChannelExclusion`

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Monitoring.scala

The Kamon histogram was not created properly.

Fix balance histogram

---

eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ExtraDirectives.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Invoice.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Message.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/serde/FormParamExtractors.scala

(Minor) Streamline api extractor names

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitor.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxTimeLocksMonitor.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/DummyOnChainWallet.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/TxTimeLocksMonitorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/zeroconf/ZeroConfAliasIntegrationSpec.scala

This PR supersedes #2493: it cherry-picks the first two commits and fixes other flaky tests.
Best reviewed commit-by-commit.

Fix flaky tests

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version0/ChannelCodecs0.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version1/ChannelCodecs1.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version2/ChannelCodecs2.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala

`Commitments` clean-up

---

.github/workflows/docker-image.yml
BUILD.md
CONTRIBUTING.md
README.md
eclair-core/eclair-cli

- link to plugins repository
- remove android mention for eclair
- update other implementations (renamed)
- update docker CI action versions
- missing eclair-cli APIs in help

Update various doc files

---

README.md
eclair-core/pom.xml
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala

This bitcoind release contains a few bug fixes and improvements.

Update to bitcoind 23.1

---

eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala

Since we only sign one-input txs, the input index was hardcoded to `0`, but with splices we will spend previous funding txs, which may have a change. The change is trivial since we do have all the info to figure out the output index.

Do not hardcode input index at signature

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala

Apparently lnd and cln don't send a payment secret when using keysend, even when we advertize the feature as mandatory. This is ok though, we don't actually need a payment secret to protect keysend payments as long as the sender doesn't use MPP (which is their responsibility, not ours).
Since our codebase requires payment secrets to index payments, we simply use the preimage as secret when receiving keysend payments.
Thanks @kiwiidb for reporting this compatibility issue.

Allow keysend payments without a payment secret

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/Postman.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/MessageOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/OnionMessagesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala

The postman now has a higher level API to send messages: the user provides the content and the paths to use and the postman takes care of building the message packet and sending it to the next node.

Build message inside Postman

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPrePublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala

The ReplaceableTxPublisher only looked at the remote commit and ignored the case where our peer publishes their next commit. This created two issues:
- eclair would keep trying to publish htlc transactions that had no chance of confirming, which is a waste of resources
- eclair would fail to RBF claim-htlc transactions: this had no impact today because we currently target the next 2 blocks so RBF isn't necessary, but it will become useful if we allow setting a more economical block target in the future

Handle next remote commit in `ReplaceableTxPublisher`

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt12Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferPaymentMetadata.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/OfferPayment.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/offer/OfferManagerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/send/OfferPaymentSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Payment.scala

This is a PR to integrate into #2566: there are only minor changes in business logic, it is mostly refactoring to make the code easier to understand, remove duplication and add more tests. Each commit contains a detailed description of what it includes.

Offer manager refactoring and tests

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/SingleFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptDualFundedChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingInternalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

- Small improvements to the channel open response
- Clean up RBF attempt some missed error cases
This is a PR on top of #2608

Refactoring and clean up RBF attempts

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

This is a single commit on top of #2634

Fix splice test for dynamic funding public keys

---

eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala

A peer that receives `Disconnect` *may* also be sent the `Init` message. The `Init` message is ignored by the two disconnect tests so these tests should occur only after all of the tests that should not result in a `Disconnect`. Otherwise an extra `Init` could trigger the error here:
```
// Do not disconnect an old peer when a new peer with channels connects.
switchboard ! ChannelIdAssigned(channel.ref, hasChannelsNodeId2, randomBytes32(), randomBytes32())
switchboard ! PeerConnection.Authenticated(peerConnection.ref, hasChannelsNodeId2, outgoing = false)
peer.expectMsgType[Peer.Init]
peer.expectNoMessage(100 millis)
```
Because we expect no additional messages to be sent to a peer that gets an `Init` but does not get a `Disconnect`, and instead could get two `Init`s. The solution was to …

Fix connection limiter test to prevent error when waiting for no messages

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala

Improvements for `Remove minDepth from InteractiveTxParams`

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/ChannelKeyManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/LocalChannelKeyManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/resources/nonreg/codecs/000003-DATA_NORMAL/fundee-announced/data.json
eclair-core/src/test/resources/nonreg/codecs/000003-DATA_NORMAL/funder/data.json
eclair-core/src/test/resources/nonreg/codecs/020002-DATA_NORMAL/funder-announced/data.json
eclair-core/src/test/resources/nonreg/codecs/030000-DATA_WAIT_FOR_FUNDING_CONFIRMED/funder/data.json
eclair-core/src/test/resources/nonreg/codecs/03000a-DATA_WAIT_FOR_CHANNEL_READY/funder/data.json
eclair-core/src/test/resources/nonreg/codecs/03000c-DATA_WAIT_FOR_DUAL_FUNDING_READY/funder/data.json

There was a confusion between `fundingKeyPath` and `channelKeyPath`.

Cleanup `ChannelKeyManager`

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala

Now that the model is stable we can remove restrictions.

Remove restriction to regtest/testnet

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

We let the initiator pick the feerate, but it must at least meet some sanity requirements.

Reject unreasonably low splice feerate

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala

This is interesting to perform traffic analysis on the messages we send and receive, to inform research about traffic shaping.

Add message size metric

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Autoprobe.scala

The autoprobe feature creates fake invoices to send payments to remote nodes. These fake invoices must include a payment secret.
@rorp we're not actively maintaining this, I think that we'll move it soon to a plugin, which makes more sense to allow users to tweak its behavior, but this should fix it in the meantime.
Fixes #2623

Fix Autoprobe dummy invoice

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt11Invoice.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala

For amounts that are multiples of 1btc, we shouldn't use a multiplier and should directly encode this amount.
See https://github.com/ACINQ/lightning-kmp/issues/470 for more context.

Handle invoice with amounts larger than 1btc

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala

It's a bit clumsy because `ActorRef.noSender` its just `null`, to test we need a real `ActorRef` and so we need an actor system.

Add serialization test for RES_GET_CHANNEL_INFO

---

eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala

Test assumes that payments inserted in the db will be returned in a deterministic order because they have different timestamps. It may not always be the case if TimestampMilli.now() returns the save value twice. So here we use explicitly different timestamps: now = TimestampMilli.now(), now + 1.milli, now + 2.milli ....

Fix AuditDb test

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala

Increase timeout for tests that would sometime fail on low performance machines.

Increase timeout for offer tests

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

When an inactive revoked commitment containing outgoing HTLCs is confirmed, we must consider the outgoing HTLC failed and relay that failure upstream. Because of the alternative commit tx mechanism, those inactive revoked commitments match the remote commit, so we were waiting for tx confirmation before failing back upstream.
This bug was found when testing splicing with HTLCs on `lightning-kmp`.

Relay HTLC failure when inactive revoked commit confirms

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/CompactBlindedPathsResolver.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

- Use `UnknownNextPeer` error when unable to resolve blinded paths
- Small formatting
- A few more tests

Some nits from PR comments

---

eclair-core/src/main/scala/fr/acinq/eclair/router/BalanceEstimate.scala

This will allow us to try different algorithms to estimate the balance and evaluate them on historical data.

Log balance estimate updates

---

eclair-front/src/main/resources/logback.xml
eclair-node/src/test/resources/logback-test.xml

There were more unused appenders.

fixup! Update logback to 1.5.16 (#2995)

---

eclair-core/src/main/scala/fr/acinq/eclair/balance/BalanceActor.scala

There are no functional changes, we are just sorting the utxos and channel diffs for easier analysis on busy nodes.

Sort amounts in the balance check

---

eclair-core/src/main/scala/fr/acinq/eclair/Logs.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/OffersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgOffersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteOffersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/DefaultOfferHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferCreator.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/BlindedPathsResolver.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/OffersDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/offer/OfferManagerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/OfferTypesSpec.scala

This commit doesn't contain any implementation change, it only focuses on refactoring, adding comments, logs, applying formatter suggestions and improving tests.

Clean-up and refactoring for #2976

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala

This is especially useful to join on the `local.channels` table to retrieve the `node_id`.

Add an index on `audit.relayed(channel_id)`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

Should fix [#9979](https://github.com/lightningnetwork/lnd/issues/9979)

Ensure htlc_maximum_msat is at least htlc_minimum_msat

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/reputation/Reputation.scala

Fixes https://github.com/ACINQ/eclair/issues/3130

Rename maxHtlcAmount to maxHtlcValueInFlight in Commitments
