eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala

We were extracting F's commit tx from its internal state right after receiving the `PaymentSent` event. The issue is that this could happen before the fulfill was completely signed on both sides, so the commit tx we obtained would still contain the HTLC and would be different from the one F would publish when closing.
This is the race condition that was sometimes happening:
```
C            F
add ------->
<--- fulfill
payment-sent
F's commit tx 1
<------- sig
rev ------->
sig ------->
<------- rev
force-close
F's commit tx 2
```
And F's commit tx1 and commit tx2 would be different, so we were trying to get the wrong tx from bitcoind.

Fix HTLC fulfill race condition in integration spec

---

eclair-core/src/main/scala/fr/acinq/eclair/PimpKamon.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Sync.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-front/src/main/resources/application.conf
eclair-node/src/main/resources/application.conf

It's costly, we're not using it, and it's too invasive.
There's no reason to keep it at the moment.

Remove kamon tracing

---

eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala

Some reconnection tests seem to be overly strict, it makes them flaky for
no good reason (or so it seems).

Fix failing reconnection tests

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Sync.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RoutingSyncSpec.scala

Our previous behaviour was to do a full routing table sync whenever we connected to a node (or a node connected to us).
This was wasting a lot of bandwidth for no reason.
Instead, we only sync with nodes that are either:
- in our sync whitelist
- have channels with us
On top of that, we trigger a sync whenever our first channel is opened with a new peer: this ensures we following flow works:
- connect to a new node
- we don't have channels together yet, so we're not syncing
- open a channel
- once the channel is open, sync the routing table
- we can now make payments (yay!)
The syncing state is a bit hard to read: we've started discussions in the spec to make changes to channel queries (see https://github.com/lightningnetwork/lightning-rfc/issues/804 and …

Only sync with channel peers

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/QueryShortChannelIdsTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/ReplyChannelRangeTlv.scala
eclair-front/modules/awseb/logback_eb.xml

Front-end logs can produce a huge amount of logs, with significant
duplication. In order to reduce the log volume, we truncate `nodeId` and
`channelId` in the MDC to only keep the first 8 hexadecimal characters.
Also, override a few `toString` because some channel-queries-related
case classes produce huge strings.

Truncate hex strings in front logs

---

eclair-core/src/test/scala/fr/acinq/eclair/TestKitBaseClass.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/RecoverySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedInternalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala

It's useful to separate these test methods in a dedicated trait instead of always bundling it with `FixtureTestSuite`.
In particular, it was previously impossible to use both `BitcoindService` and `StateTestsHelperMethods` because `BitcoindService` doesn't work with fixtures (it leverages `beforeAll` and `afterAll` instead because launching one bitcoind instance per-test would be too expensive and useless).
My goal is to then use this new `StateTestsHelperMethods` in the `ZmqWatcherSpec` (and other related actors) to test the CPFP and RBF logic against real commitments.

Refactor channel test helpers

---

docs/Configure.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

We keep the `GetRoutingState` API available in the router as it's useful to query network information locally (or between actors), but we stop sending that data to remote nodes.
I've checked the last week on our node, and there were no queries using initial_routing_sync, so it feels ok to drop support.

Remove support for initial_routing_sync

---

eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

Obviously the route amount must be strictly positive.
We don't control `htlcMinimumMsat` (it is set by our peer) and for backwards compatibility reasons we allow it to be `0 msat` (even though it doesn't make much sense), so we need to enrich our condition to detect empty channels.

Fix MPP path-finding edge case

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/ChannelKeyManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/LocalChannelKeyManager.scala

Monitor the rate at which we sign channel txs and the duration of the signing operations.

Add tx signing metrics

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala

When a peer is disconnected, the register will return a forward failure.
This can happen if the peer is connected when we start the payment FSM and then disconnects before we send them an HTLC.

PaymentLifecycle handle disconnected peers

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Sync.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RoutingSyncSpec.scala

We are restoring the previous behavior of using the `sync_complete` field to signal the end of a `channel_range_query` sync.
The first step is to correctly set that field, before we can read it and interpret it to mark the end of sync.
See https://github.com/lightningnetwork/lightning-rfc/pull/826 for more details.

Correctly set gossip sync_complete

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala

When our mempool is full, its min-relay-fee may be constantly changing.
To ensure our txs can be published, we need to check the min-relay-fee when we fund the transaction, and raise it if necessary.
Fixes #1686

Publish txs with min-relay-fee met

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Announcements.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsSpec.scala

Addresses in node announcement should be sorted.
We accept node announcements that don't do this, but we should do it for our own announcements.
See https://github.com/lightningnetwork/lightning-rfc/pull/842

Sort addresses in node announcement

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala

Added additional method to Eclair like findRoute but allowing for 2 nodeIds. Also added a new endpoint to the http Api "findroutebetweennodes" which takes sourceNode and targetNode as params.
This is the impl of feature request #1068. The ticket is rather old so I don't know whether this is still a thing, but straightforward so I gave it a try. Depending on pull request for #1690 I will either impl the API change there or with this pull.

Find route between nodes. #1068

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FeeEstimatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

With anchor outputs, the actual feerate for the commit tx can be decided when broadcasting the tx by using CPFP on the anchor.
That means we don't need to constantly keep the channel feerate close to what's happening on-chain. We just need a feerate that's good enough to get the tx to propagate through the bitcoin network.
We set the upper threshold to 10 sat/byte, which is what lnd does as well. We let the feerate be lower than that when possible, but do note that depending on your configured `feerate-tolerance`, that means you can still experience some force-close events because of feerate mismatch.
The last two commits fix small related issues and can be reviewed independently.
NB: anchor outputs is still not safe to use after this commit: we don't bump the feerate yet by doing a CPFP …

Add a maximum fee threshold for anchor outputs

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

In some places of the codebase we relied on the fact that lightning transactions had a single input. That was correct with the standard commitments format, but will not be the case with anchor outputs: 2nd-stage txs (htlc-txs) and 3rd-stage txs (claim-htlc-txs) can be RBF-ed and have any number of inputs and outputs.

Relax single tx input requirements

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala

Our previous timeout was based on timestamps, mostly because `blockCount` could be `0` on mobile using Electrum until a new block was received. Now that we're diverging from the mobile wallet codebase, we can use block heights instead which is more accurate.
See lightningnetwork/lightning-rfc#839
I've done some E2E tests on regtest for the "migration" code. There is one edge case where a channel in `WAIT_FOR_FUNDING_CONFIRMED` will not be automatically cleaned up: if the peer never connects back to you, the channel will stay in `OFFLINE` and won't check for funding timeout. I think this edge case is quite harmless and can be ignored (I don't think it's worth adding more code to fix it).

Update funding timeout fundee

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/WatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ExtendedBitcoinClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitcoinCoreFeeProviderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala

And improve test coverage specifically for the calls we'll rely on for CPFP and RBF.
I wanted to separate this PR from the one that actually use these calls for RBF/CPFP to avoid a monster PR, as these refactoring/clean-ups make sense anyway.
I also split a test in the `ElectrumWatcherSpec` into two tests because it was a bit flaky (block count synchronization between `bitcoind` and `electrum` in the test suite is a bit flaky when a test generates multiple blocks in a sequence).

Refactor bitcoin clients

---

contrib/eclair-cli.bash-completion
eclair-core/eclair-cli

Using this escape sequence should solve the coloring issue on macOs. I don't have access to Win or Mac but it works fine in several Linux terminals so it won't get worse ;)
I also added the new "findroutebetweennodes" hint to the cli and completion file.

#1206 Use multiplatform escape sequence, added cli findroutebetweennodes

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala

Type is erased at runtime, but it's not needed, so let's simply remove it.

Fix PaymentLifecycle warning

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/WatcherTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala

Since we almost always know which transactions will spend the utxos that we are watching, we can optimize the watcher to look for those instead of starting from scratch.

Optimize watching for spending txs

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

This fixes the `multiarg infix syntax looks like a tuple and will
be deprecated` warning.

Fix annoying compiler warning

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

If a channel closes when we've received an `UpdateFailHtlc`, signed it but not yet received our peer's revocation, we need to fail the htlc upstream.
That specific scenario was not correctly handled, resulting in upstream htlcs that were not failed which would force our upstream peer to close the channel.
In that scenario the HTLC is in the `remoteCommit` but not in the `nextRemoteCommit`.

Relay partially failed htlcs when closing

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/WatcherTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ExtendedBitcoinClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelTypesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

When using anchor outputs, the commitment feerate is kept low (<10 sat/byte).
When we need to force-close a channel, we must ensure the commit tx and htlc txs confirm before a given deadline, so we need to increase their feerates.
This is currently done only once, at broadcast time. We use CPFP for the commit tx and RBF for the htlc txs.
If publishing fails because we don't have enough utxos available, it will be retried after the next block is found.
The RBF/CPFP logic requires asynchronous calls to `bitcoind`, which is why we couldn't just do it in the `Channel` directly without making the channel state machine more complex (and it's already complex enough).
This PR is a good starting point, but it's still not recommended to activate anchor outputs on your node. More re-architecting …

Set anchor output feerates when force-closing

---

eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala

This command is sent by the `Peer` to its `PeerConnection`, therefore it
needs to be a `RemoteType` and have its own codec.

Add a serializer for `DoSync`

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala

Commits can be reviewed independently.

Improve channel state tests

---

eclair-node/src/main/resources/application.conf

The module is still there and can be enabled if needed.

Disable jdbc instrumentation by default

---

eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

We just merged https://github.com/lightningnetwork/lightning-rfc/commit/b201efe0546120c14bf154ce5f4e18da7243fe7a in the spec which added Bolt 3 tests, thus invalidating one of our tests and failing the build.

Fix Bolt 3 spec change that broke our test suite

---

README.md
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala

Drop mention of p2sh-segwit. We should encourage users to use bech32.
This doesn't change our internal behavior in practice.
I also bumped the minimal bitcoin core version to 0.18.0 (it was mentioned in our documentation but not enforced at start-up).

Use bech32 addresses by default

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FeeEstimatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

It makes sense to allow node operators to configure the value they want to use as a maximum threshold for anchor outputs commitment tx feerate.
This allows node operators to raise this value when mempools start getting full in anticipation of a potential rise of the min-relay-fee.
This value can also be overridden for specific nodes.

Configurable anchor output max commitment feerate

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

We previously relied on `context.child` to check whether we already had a relay handler for a given `payment_hash`.
Unfortunately this can return an actor that is currently stopping itself.
When that happens our relay command can end up in the dead letters and the payment will not be relayed, nor be failed upstream.
We fix that by maintaining the list of current relay handlers in the `NodeRelayer` and removing them from the list _before_ stopping them. This is similar to what's done in the `MultiPartPaymentFSM`.
This bug has been seen in the wild by the Electrum team with an eclair trampoline node that they run. Phoenix is *not* affected by this, because this bug only happens when the sender uses trampoline with multiple incoming HTLCs, but *without* letting the trampoline node aggregate …

Fix potential race condition in node-relay

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/AuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/ChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DbEventHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteChannelsDbSpec.scala

(First commit is a refactor/cleanup and can be reviewed independently).
Here is the rationale for implementing channel metadata as additional
columns in the `local_channels` table of the `channels` db, as opposed
to a dedicated `channel_metadata` table of a `audit` db:
1) There is a migration to do (in the `local_channels` table, no less!),
but it's just a table migration, as opposed to a data migration, if we
had to populate a new table in a separate database.
2) We don't need to worry about creating a new metadata line when a new
channel is created (compared to doing add-or-update stuff). It's only
_updating_ optional columns in a best-effort manner.
3) We don't need to worry about inconsistencies between two tables
located in two separated databases (that's a big one).
4) We may want …

Add metadata to local_channels table

---

eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/AuthDirective.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/DefaultHeaders.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/EclairDirectives.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ErrorDirective.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ExtraDirectives.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/TimeoutDirective.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Invoice.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Message.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Node.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Payment.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/WebSocket.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

We incorrectly applied error handlers at each sub-route instead of applying it after grouping all sub-routes together. The result was that only `getinfo` (the first one tried) could actually be called.
The tests were changed to directly call the sub-routes so they didn't notice this issue. I fixed that by adding tests that failed with the previous code by simply using the top-level route.
I thought I had tested this E2E before merging #1690 but my (custom, poorly written) scripts in fact didn't correctly re-source my `.bash_aliases` so I was in fact testing `master` :facepalm: 
cc @tompro

Fix API regression

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala

This commit clarifies some parts of the code on which we regularly have questions during pull requests.
We also add a test for an edge case in shutdown that was correctly handled, but not properly tested, to ensure non-regression.

Clarify some comments and add tests

---

docs/Architecture.md

It can be useful for newcomers to have a high-level view of the main components in eclair. This will help them quickly find where they should start digging into actual code to achieve what they want.
We're leaving a lot of details out to ensure this document stays up-to-date and doesn't need to completely change every time we slightly rework internal details of our architecture.

Add high-level architecture diagrams

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TestVectorsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

Since anchor outputs, we not only deduce the commit tx fee from the funder's main output but the cost of the anchors as well.
We rename the function that does that for more clarity as it came up in multiple reviews as something that was a bit confusing.
The change is split in two commits to make it easier to verify that there's no regression:
- the first commit renames the function
- the second commit adapts places where we actually only want the commit tx fee

Clarify commit tx fee anchor cost

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

An interesting side-effect of anchor outputs is that htlc txs can be merged when they have the same lockTime (thanks to sighash flags).
We're not currently doing that, but our peers may do it, so we need to handle it in the revoked commit tx case and correctly claim multiple outputs if necessary.

Handle aggregated anchor outputs htlc txs

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

We'd like to provide an abstraction for child actors creation, otherwise our actors become too tightly coupled and hard to test in isolation. But we don't want to move too much business logic outside of the actor (for instance the choice of child supervision strategy).
I'm going with a simple ad-hoc factory pattern in this PR, which removes unnecessary fields in actor constructors and allows more flexibility in tests. I must say I'm not entirely satisfied, but can't find a simple alternative (it's important to have a simple solution here, I don't want to make it harder for readers of the code).
If you have a better naming for the concrete Factory classes, let me know!

Introduce actor factories

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

Several improvements to `yenKshortestPaths`:
- Run `yenKshortestPaths` backwards like what is already done in `dijkstraShortestPath`. It allows to compute the correct weights directly.
- Prevent producing loops by excluding the root path nodes
- Do not run `dijkstraShortestPath` several times on the same input by only computing spur paths for new edges. `shortestPaths(k)` often has a lot of overlap with the previous `shortestPaths` so a lot of the poential spur nodes were already considered.

Shortest paths: prevent producing loops and remove some duplicated work

---

BUILD.md
eclair-core/pom.xml

It was only used by Electrum which was removed in #1750

Remove Docker test dependency

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala

There was a much more efficient method to compute the pukey recovery id that was not used.

Make signing payment requests faster

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PeersDbSpec.scala

The upsert pattern in `channelsDb.addOrUpdateChannel` is apparently not compatible with concurrent transactions when they are in `SERIALIZABLE` mode.
A simple test shows the issue and the following exception is thrown:
```
Canceled on identification as a pivot, during conflict out checking
```
I tried reducing the isolation level, but 1) I'm not sure what the consequences are in terms of locking the db and 2) it didn't entirely fix the issue.
As per the [postgres doc](https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-UPSERT-EXAMPLE), the recommended construct for the _upsert_ pattern is with the `ON CONFLICT` clause:
> It is recommended that applications use INSERT with ON CONFLICT DO
UPDATE rather than actually using this pattern.
I'm not sure about the …

Posgres: fix concurrency in channels db

---

eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala

The `ReconnectionTask` was only catching
`ConnectionResult.Failure.ConnectionFailed`, which is a subset of
possible failures. It should instead have caught
`ConnectionResult.Failure`.
All authentication and initialization failures were not caught and
didn't trigger reconnections.
Fixes #1748.

Catch all connection failures and reconnect

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

We don't want a database error to cause force close of channels.
Database errors are more likely to happen when using Postgres, but can
also happen with Sqlite in case of e.g. full disk.
Since we always write to disk before sending messages, we should be able
to recover gracefully after the db issue is fixed and eclair is
restarted.

Make db errors fatal in channels

---

.github/workflows/main.yml

The default is 360 minutes which is very long.
Our builds are usually around 10 minutes, so 20 minutes is a good value to prevent overbilling builds that create infinite loops.

Add shorter CI timeout

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/StaleChannels.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/NetworkDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala

Commits are independent and are best reviewed separately.

More database nits

---

eclair-core/src/main/scala/fr/acinq/eclair/db/jdbc/JdbcUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPendingRelayDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteFeeratesDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingRelayDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/NetworkDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteFeeratesDbSpec.scala

(This part of the code is sensitive, but not critical, because bugs
should be obvious, and their impact should be limited to the app
refusing to start.)
~~No SQL code has been modified, this is just a refactoring.~~
edit: second commit does remove `IF NOT EXISTS` statements.
The way our `getVersion`/`setVersion` worked was very unintuitive
and led to comments like the following in tests:
```scala
dbs.getVersion(statement, "network", 1) // this will set version to 1
```
The reason is that we treat unitialized databases and up-to-date
databases exactly the same way. That is why a `getVersion` will set the
version to the most up-to-date if none is found. It's also why we use
`CREATE IF NOT EXISTS` statements for tables and indices.
I think that is misleading and we should have a `getVersion` …

Rework the db version management

---

eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala

There are issues with IPv6 loopback addresses on build machines, so we force IPv4 and use non-blocking socket servers.

Reenable ServerSocket tests

---

eclair-core/src/main/scala/fr/acinq/eclair/db/jdbc/JdbcUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala

Did some refactoring in tests and introduced a new `migrationCheck`
helper method.
Note that the change of data type in sqlite for the `commitment_number`
field (from `BLOB` to `INTEGER`) is not a migration. If the table has
been created before, it will stay like it was. It doesn't matter due to
how sqlite stores data, and we make sure in tests that there is no
regression.

Use proper data type for timestamps in Postgres

---

eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/crypto/ChaCha20Poly1305.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/Mac.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/Noise.scala
eclair-core/src/test/scala/fr/acinq/eclair/crypto/NoiseSpec.scala
eclair-node/src/main/resources/logback.xml

- Use latest spongycastle versions
- Reformat files
- Remove support for the obsolete wireshark lightning dissector
Fixes #1375

Use bouncycastle instead of spongycastle

---

eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/singleaddress/SingleAddressEclairWallet.scala
eclair-node/pom.xml
pom.xml

This will allow us to use this key as our static payment point for static-remote-key channels.
We use the BIP84 address for this key as our single address.

Update single-address wallet to accept a public key instead of an address

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala

It may contain a lot of data and pollute the logs.

Don't log ClosingType object

---

eclair-front/pom.xml
eclair-node/pom.xml

Bintray has been discontinued and artifacts have been migrated to Maven
Central.

Remove bintray repository

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

We need to group incoming HTLCs together by `payment_hash` *and* `payment_secret`, otherwise we will reject valid payments that are split into multiple distinct trampoline parts (same `payment_hash` but different `payment_secret`).
Thanks @ecdsa for pointing out this issue.
Fixes #1723

Index trampoline payments by hash and secret

---

eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/crypto/ChaCha20Poly1305.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/Mac.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/Noise.scala
eclair-core/src/test/scala/fr/acinq/eclair/crypto/NoiseSpec.scala
eclair-node/pom.xml
pom.xml

We get rid of our old JNI wrapper and switch to bitcoin-lib 0.18 which is based on secp256k1-kmp.
This will give us a consistent secp256k1 library on all our apps (since secp256k1-kmp also provides an Android library).
We also switch from spongycastle bouncycastle (bitcoin-lib 0.18 uses bouncycastle).

Use secp256k1-kmp

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala

We don't need `SERIALIZABLE` consistency guarantees when all we do is
updating timestamp columns. This happens concurrently to channel data
update and raised serialization errors in postgres.
Fixed #1786.

Use less strict isolation level for channel meta

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/zmq/ZMQActor.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala

We use one actor per topic, but each actor previously registered to multiple topics so we received duplicate events and consumed twice the necessary bandwidth.
Thanks @btcontract for noticing this in #1789

ZMQ actors should subscribe to a single topic

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala

* The two months window for channel age was too small for today's network (where most channels are at least 6 months old)
* CLTV is less of an issue nowadays: there are fewer stuck payments and we're encouraging nodes to increase their CLTV because of the recent mempool congestions, so when your payment is stuck it's very painful regardless of the path you took

Update default path-finding weight ratios

---

docs/Tor.md

torproject's website is a bit difficult to navigate.  Until they fix it, this change will help readers find the Windows "Expert Bundle."

Instructions for downloading Tor Bundle

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala

This fixes a case where `MultiPartPaymentLifecycle` keeps retrying a payment even after it got confirmed on chain. Doing so is harmless but meaningless.

Do not retry sending if payment gets confirmed on chain

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsSpec.scala

This is a security feature that has been introduced a long time ago and is widely supported across the network.
We can safely make it mandatory which closes probing attack vectors.
A separate follow-up PR will remove some legacy code that handled cases where `payment_secret` could be missing.
I'd rather first release the activation bits and then remove that legacy code instead of bundling the two together.

Make payment_secret mandatory

---

eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/zmq/ZMQActor.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala

One of ZMQ's drawbacks is that subscribers on an unreliable network may silently disconnect from publishers in case of network failures.
In our case, we want to reconnect immediately when that happens, so we set a tcp keep-alive to ensure this.
Thanks @engenegr for noticing this and testing the fix.
Fixes #1789

Add TCP keep-alive on ZMQ socket

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala

Opt-in to allow any future segwit script in shutdown as long as it complies with BIP 141 (see  https://github.com/lightningnetwork/lightning-rfc/pull/672).
This has been tested successfully against c-lightning v0.10.0 compiled with `--enable-experimental-features`.

Add support for option_shutdown_anysegwit

---

docs/Tor.md

My testing showed that when the path to the configuration file was specified without quotation marks, the installation of the service ignored the -f option.  This resulted in `IMPORTANT NOTE: The Tor service will run under the account "NT AUTHORITY\LocalService". This means that Tor will look for its configuration file under that account's Application Data directory, which is probably not the same as yours.`  After I added quotation marks, as shown at [miloserdov's instructions](https://miloserdov.org/?p=1839), this "IMPORTANT NOTE" went away, and Eclair can now see tor.

Quotes for Windows Service Install

---

eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala

Remove a legacy work-around for very old eclair-mobile users.
NB: this is a PR to the `android` branch. It should then be merged in the `android-phoenix` branch as well.

Stop masking feature bits

---

eclair-core/src/main/scala/fr/acinq/eclair/db/DbEventHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/FeeratesDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/FileBackupHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/jdbc/JdbcUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPendingCommandsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteFeeratesDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingCommandsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala

This allows us to use the full power of scala collections, to iterate
over results, convert to options, etc. while staying purely functional
and immutable.
There is a catch though: the iterator is lazy, it must be materialized
before the result set is closed, by converting the end result in a
collection or an option. In other words, database methods must never
return an `Iterable` or `Iterator`.

Make result set an iterable

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala

It's similar with built-in akka metrics, but with message-type granularity.

Add metrics on channels processing time

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

The spec defines `max_accepted_htlcs` and `max_htlc_value_in_flight_msat` to let nodes reduce their exposure to pending HTLCs. This only applies to received HTLCs, and we use the remote peer's values for outgoing HTLCs.
But when we're more restrictive than our peer, it makes sense to apply our limits to outgoing HTLCs as well.

Symmetrical HTLC limits

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

The spec defines `max_accepted_htlcs` and `max_htlc_value_in_flight_msat`
to let nodes reduce their exposure to pending HTLCs. This only applies to
received HTLCs, and we use the remote peer's values for outgoing HTLCs.
But when we're more restrictive than our peer, it makes sense to apply our
limits to outgoing HTLCs as well.

Symmetrical HTLC limits (#1828)

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala

This will allow plugins to know where the Eclair datadir is and look for their files in that dir. Fixes https://github.com/ACINQ/eclair/issues/1830

Make `Setup.datadir` a val

---

eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala

With the move to akka _typed_, we will be using more and more
scalatest's `eventually` as a replacement for akka's `awaitCond`
(which isn't available in `testkit.typed`).
But there is a catch:
- `awaitCond` expects a boolean
- `eventually` expects a non-failure
Which means that we must use `eventually(assert(cond))`, and not
`eventually(cond)`.

(Minor) Fix eventually statements

---

README.md
eclair-core/pom.xml
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala

Update the default version of `bitcoind` to 0.21.1.
Deprecate support for version 0.18.1 and 0.19.1.
Nothing impacting changed between 0.20.1 and 0.21.1.
The only change relevant to lightning would be the following:
```
A new fee_rate parameter/option denominated in satoshis per vbyte (sat/vB) is introduced to the sendtoaddress, sendmany, fundrawtransaction and walletcreatefundedpsbt RPCs as well as to the experimental new send RPC.
```
But we will be able to leverage it only once we deprecate versions of `bitcoind` older than 0.21.1.
There's also a change that may be useful in tests (in particular for the `TxPublisher`):
```
The generateblock RPC allows testers using regtest mode to generate blocks that consist of a custom set of transactions. (#17693)
```

Udpate to Bitcoin Core 0.21.1

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
pom.xml

There are no functional changes, but bitcoin-lib 0.19 is based on secp256k1-kmp (instead of our own fork of secp256k1's JNI wrapper) which is cleaner, easier to maintain and used in our mobile apps.

Use bitcoin-lib 0.19

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/FileBackupHandler.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteFileBackupHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala

This is a bit less trigger happy than previously, and the implementation
is simpler.

Schedule backup at regular interval

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

It doesn't make any sense to forward empty payments.
This is also checked when adding the htlcs in the outgoing channel, but we should fail early in the node-relay actor.

Reject 0-value trampoline payments

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

Make sure trampoline users pay at least as much as the other users.

Trampoline payments use per-channel fee and cltv

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

Add support for logging warning messages as introduced in https://github.com/lightningnetwork/lightning-rfc/pull/834
Support for sending warning messages instead of current errors will be added in a later PR.
Note that c-lightning already sends these messages, so it will be useful to have them correctly logged.
Even if the spec PR is eventually changed, this will not introduce backwards-compatibility issues so IMO it's worth merging on master now.

Decode warning messages

---

eclair-core/src/main/resources/reference.conf

The `file-backup` section should be inside `eclair`, otherwise startup fails.

Fix default file backup config

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala

https://github.com/lightningnetwork/lightning-rfc/pull/834 recommends sending warning messages instead of connection-level errors in some cases, which avoids unnecessary channel closure.

Use warning messages for connection issues

---

eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala

We still use sqlite as the primary db, but all calls are replicated
asynchronously on postgres.
The goal is to prepare a smooth transition from sqlite to postgres
on a production server. This is a very specific use case and most users
shouldn't use it, which is why the new config `eclair.db.driver=dual` is
not documented.

Add support for dual db backend

---

eclair-core/pom.xml
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/balance/BalanceActor.scala
eclair-core/src/main/scala/fr/acinq/eclair/balance/ChannelsListener.scala
eclair-core/src/main/scala/fr/acinq/eclair/balance/CheckBalance.scala
eclair-core/src/main/scala/fr/acinq/eclair/balance/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/balance/ChannelsListenerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/balance/CheckBalanceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/OnChain.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/serde/JsonSerializers.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/JsonSerializersSpec.scala

For now it just gives detailed info on the current pending mutual closes.

Add a globalbalance API call

---

eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPendingCommandsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/NetworkDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PendingCommandsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala

Instead of having a flat organization under the default `public` schema, we classify tables in schemas. There is roughly one schema per database type.
The new hierarchy is:
- `local`
- `channels`
- `htlc_infos`
- `pending_settlement_commands`
- `peers`
- `network`
- `nodes`
- `public_channels`
- `pruned_channels`
- `payments`
- `received`
- `sent`
- `audit`
- (all the audit db tables)
- `public`
- `lease`
- `versions`
Note in particular, the change in naming for local channels vs external channels:
- `local_channels` -> `local.channels`
- `channels` -> `network.public_channels`
The two internal tables `lease` and `versions` stay in the `public`
schema, because we have no meta way of migrating them.

Use schemas in Postgres

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala

For some reason, the payments database was forgotten by #1778.
NB: this is missing a migration test.

Use proper data type for timestamps in Postgres 2

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala

I was able to reproduce #1856 by replaying the "concurrent channel
updates" test with hardcoded additional delays in the database code. It
was due to a conflict between `addOrUpdateChannel` and
`updateChannelMetaTimestampColumn`. The two calls run in parallel and
the latter completed before the former, causing it to fail. Reducing
the isolation level makes the problem disappear.
We reduce the transaction isolation level from `SERIALIZABLE` to
`READ_COMMITTED`. Note that [*]:
> Read Committed is the default isolation level in PostgreSQL.
I'm not sure why we were using a stricter isolation level than the
default one, since we only use very basic queries. Doc does say that:
> This behavior makes Read Committed mode unsuitable for commands that involve complex search conditions; however, it …

Reduce Postgres transaction isolation level

---

eclair-core/src/test/scala/fr/acinq/eclair/balance/CheckBalanceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

I was OCD-ing over [this comment](https://github.com/ACINQ/eclair/pull/1737/files#r662959421) and it was quick to fix, so here it is :smile: 
I'm moving balance check tests to their own test file instead of making the tests in `NormalStateSpec` more complex than they were.

Refactor global balance tests

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/ChannelRelayerSpec.scala

See #1829.
We should fail outgoing _unsigned_ htlcs on force close, just like we do when disconnected.

Fail unsigned outgoing htlcs on force-close

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala

Delegate the payment request generation, signature and db write to a short-lived child actor.
There is small (~5%) gain in performance in `PerformanceIntegrationSpec` because what matters is the db write, and it is not parallelized in WAL mode.

Parallel payment request generation

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala

Our test suite is putting a lot of strain on our CI machines, and we start hitting some timeouts. There were places where we would put a 60 seconds timeout on an `awaitCond` but inside we'd still use the default 15 seconds timeout.
The wumbo test was failing sometimes because we generated blocks before the closing tx reached the mempool.

Fix flaky channel integration tests

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala

This is a simpler approach to completely parallelizing the handling of payments (attempted in branch [parallel-payment-handler](https://github.com/ACINQ/eclair/tree/parallel-payment-handler)), where we simply parallelize the fetch from the database.
The advantage is that it is a much smaller change, that already brings a ~30% performance improvement in performance in `PerformanceIntegrationSpec`.

Fetch incoming payments in parallel

---

eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala

The parallelization introduced with #1880 has created race conditions in tests.

Fix payment handler tests

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala

If we want C to go to the closed state, we must ensure it's really his claim transaction that's in the mempool before generating blocks.

Fix yet another flaky test

---

eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala

This test sometimes fail when the `NewTransaction` events are delayed too much because the CI machine is overloaded.

Fix watcher flaky test

---

eclair-node/pom.xml
pom.xml

Fixes:
```
021-07-19 12:03:13,504 WARN  akka.util.ManifestInfo - You are using version 10.2.4 of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 10.2.4 of the [akka-http] artifacts to your project. Here's a complete collection of detected artifacts: (10.2.0, [akka-http]), (10.2.4, [akka-http-core, akka-parsing]). See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
```

Update akka-http-json4s dependency

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartPaymentFSM.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentFSMSpec.scala

_This is a PR to branch android-phoenix_
Compare the *sum* of all pay-to-open parts against the min pay-to-open
amount.

Fix pay-to-open below minimum when using MPP

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsSpec.scala

Split the settings for the default relay fee in two:
- fees for announced channels
- fees for unannounced channels
- minimum fee for trampoline relays (we don't even try to relay trampoline payments with lower fees)

Different default relay fees for announced and unannounced channels

---

eclair-node/src/main/scala/fr/acinq/eclair/api/directives/EclairDirectives.scala

According to https://github.com/akka/akka-http/issues/745#issuecomment-271571342, we should use `toStrictEntity` to wrap all underlying operations if we want to avoid hitting the `Substream Source(EntitySource) cannot be materialized more than once` error.
This has been tested by @engenegr who confirmed that it does fix the issue on his side.
Fixes #1855

Fixing API substream materialization issues

---

eclair-core/src/main/scala/fr/acinq/eclair/balance/CheckBalance.scala
eclair-core/src/test/scala/fr/acinq/eclair/balance/CheckBalanceSpec.scala

HTLCs are stored in a `Set`, and doing `htlcs.map(_.amount).sum` will
deduplicate identical amounts, resulting in an erroneous balance
calculation. The `Set` must be converted to a `List` first.
Identical htlcs amount are quite frequent due to splitting for AMP.

Balance: do not deduplicate identical htlcs amounts

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala

When using trampoline, we previously made a single payment attempt per trampoline fee.
That doesn't work when our best channel has a local failure (such as `remote cannot afford increased commit tx fees`), because:
- we instantly failed the `MultiPartPaymentLifecycle` (because `maxAttempts` was set to `1`)
- we retried with a higher trampoline fee (from the `PaymentInitiator`) but since the channel selection is deterministic for the first attempt, we selected the same channel and the local failure was still there regardless of how much trampoline fees we were ready to pay
We usually only need one attempt, but there's no reason to always limit it to `1`, so we now use the node's configuration for `max-payment-attempts`. Since the `MultiPartPaymentLifecycle` aborts when it receives an error …

Retry local channel failures in trampoline payments

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPendingCommandsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteFeeratesDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingCommandsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/NetworkDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PendingCommandsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteFeeratesDbSpec.scala

Simplify the migration by not duplicating code. Should be less error-prone when adding new migration.

Refactor db migration

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

Some users are experiencing path-finding issues when trying to send big payments.
This is because the way MPP path-finding currently works is:
- Find N routes with Yen's algorithm for a small arbitrary amount (set by the node operator, by default 15 000 sats)
- Split the total amount to send between the routes we found based on their capacity (and some randomization)
If this set of routes cannot carry the whole payment, the path-finding fails (and returns `RouteNotFound`).
For this very simple algorithm to work, instead of providing an arbitrary, static amount to Yen's algorithm, we should instead use `total_amount / num_routes` (which is what this PR does). The reason we didn't do this earlier was because this code was shared with wallets (such as Phoenix) and we wanted to be able to …

MPP scale min part amount based on total amount

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeProvider.scala

Override `toString()` for the various feerate classes.

Nicer feerate string representation

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ExtendedBitcoinClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala

This PR is split in two independent commits.
In the first commit, we fix a (harmless) issue where we kept spawning `TxPublisher` actors to spend anchor outputs even when the commit tx was confirmed if the feerate was already high enough. This was spamming the logs for no reason (and spawning actors that immediately stopped themselves), we should instead check the status of the commit tx as the first precondition to spending anchor outputs.
In the second commit, we call `bitcoind`'s `abandontransaction` when 2nd-stage txs are evicted from the mempool because their parent is replaced (e.g. the remote commit tx is confirmed instead of our local commit tx). This ensures the `bitcoind` wallet will not keep these obsolete transactions in its DB and reserve their inputs for no good reason.
Fixes …

Better handling of remote commit confirmation in TxPublisher

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

Split `SendPayment` in `SendPaymentToRoute` and `SendPaymentToNode`
This allow us to ensure that when sending to a specific route, we never try another route.

Split `SendPayment` in `SendPaymentToRoute` and `SendPaymentToNode`

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Autoprobe.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PerformanceIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/Handlers.scala

For path finding we always need `routeParams`, however all of the messages asking for finding a route have `routeParams` as an optional parameter. This makes it hard to enforce that a given payments uses a given `routeParams` as there may be a `None` somewhere that reverts to the global defaults.
It seems that the reason all the `routeParams` are optional is that the messages asking for finding a route are sometimes used when we already have a route. This is a hacky solution and I've tried to replace these messages by traits that work both when we want to find a route and when we already have it.
I'm trying to enable AB testing which requires using different `routeParams` for different payments and this is a blocker.

Make route params explicit

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala

We offset the `recid` by `31` for compatibility with `lnd` [1] but we
should also support normal values (0-3), and also add boundary checks.
[1] https://twitter.com/rusty_twit/status/1182102005914800128

Add validation on the recid in `verifymessage`

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala
eclair-front/src/main/resources/application.conf
eclair-node/src/main/resources/application.conf

This allows instant restart of eclair when using Postgres backend.
Fixes #1896.

Gracefully release Postgres lock on shutdown

---

README.md

The GUI has been deprecated a long time ago, and doesn't inform users about potential risks, such as RBF-ing funding txs.
We should instead incentivize users to use the CLI and read the documentation, which ensures they will know about potential pitfalls. I have added a warning about RBF to the wiki documentation [here](https://github.com/ACINQ/eclair/wiki/Usage).
This is related to #1926

Add warning about GUI deprecation

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/RegisterSpec.scala

This is an alternative and hopefully more principled solution to https://github.com/ACINQ/eclair/pull/1924. It makes `Register` in base Eclair to rely on new `ChannelAvailable` trait rather than on concrete `ChannelRestored` class so non-standard channels can be injected into `Register` without affecting other parts of system.
> https://github.com/ACINQ/eclair/pull/1924#issuecomment-908417301
> Why do you have to use ChannelRestored? Your code must be the one emitting and listening to those events, since we only emit ChannelRestored for non-virtual channels.
`ChannelRestored` connectes HC to the rest of the system by injecting it into `Register` so routings like `Normal channel -> HC`, `HC -> Normal channel`, `HC -> HC` become possible while reusing all of the existing base code. 
This is …

Add `AbstractChannelRestored` event trait

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala

Add payment secrets (see https://github.com/lightningnetwork/lightning-rfc/pull/887)
We'll wait for the next release, and then change the `payment_secret` field to be non-optional

Update Bolt 11 official test vectors

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
README.md

Remove references to Gitter, so that newcomers use Github discussions instead.

Use Github discussions instead of Gitter

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/PathFinding.scala

Add a new way of scoring paths that estimates the success probabilities of paths and put a cost on failed payment attempts.
For now the success probabilities are estimated in a very simple way based on capacity: I assume that the balance is a random variable uniformly distributed between 0 and capacity and multiply probabilities for all the channels on the path.
The formula for estimating the probability could be changed easily, that's not the focus of this PR. The goal of this PR is to introduce a new scoring of paths that uses this probability and can be evaluated using the new AB testing framework from #1930.

Add success probabilities in path finding

---

README.md

Installation instructions now make it clear that future versions of Bitcoin Core are not supported in the current version of Eclair.

Forward incompatibility with Bitcoin Core

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Channel.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

Implement https://github.com/lightningnetwork/lightning-rfc/pull/894
We can safely accept dust limits as small as 354 sats, as long as we explicitly handle the case where a closing tx is generated with an output below dust (when that happens, we force-close to get our funds back).
The spec PR received broad agreement during yesterday's spec meeting, so we can safely merge this change now.

Lower minimum remote dust limit

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala

Channels with 0 capacity shouldn't exist. But if it happens somehow we should ignore them, not pretend that they are big channels.

Ignore channels without capacity

---

docs/Configure.md
eclair-core/src/main/resources/reference.conf

Having basic documentation in-place by providing examples in
`eclair.conf` is great and very convenient, but in the case of
path-finding, defining experiments take so much space that it makes
the whole configuration file actually more complicated to understand.
And since we don't want to enable experiments by default, the user still
has to figure out what to change to actually enable AB-testing.
I believe a better trade-off is to move examples to the docs.

Move path-finding examples to documentation

---

eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Autoprobe.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentError.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

It's quite cumbersome to investigate complex payment failures.
We need to grep on the parent ID, then group together logs for each child payment, and then we're ready for some analysis.
Most of the time, a quick look at the breakdown of all intermediate failures is all we need to diagnose the problem.
This PR adds such a log line, which hopefully will mean less time wasted grepping stuff.
I had to add an `amount` field to all `PaymentFailure`s: you will notice that in a few places, I didn't have the exact information available, let me know if you think the choices I made were wrong.
The resulting log line looks like this:
```
12:14:35.958 INFO  f.a.e.p.s.MultiPartPaymentLifecycle PAY n:025fc0c757afafb9fbae3b39f68fbbdbe81d94a7b10b5884b783c12e583e1d879f …
```

Log payment failure summary

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitor.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/RawTxPublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxPublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/AuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DbEventHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/RawTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/TxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala

We previously computed the on-chain fees paid by us after the fact, when receiving a notification that a transaction was confirmed. This worked because lightning transactions had a single input, which we stored in our channel data to allow us to compute the fee.
With anchor outputs, this mechanism doesn't work anymore. Some txs have their fees paid by a child tx, and may have more than one input.
We completely change our model to store every transaction we publish, along with the fee we're paying for this transaction. We then separately store every transaction that confirms, which lets us join these two data sets to compute how much on-chain fees we paid.
This has the added benefit that we can now audit every transaction that we tried to publish, which lets node operators audit the anchor …

Store published txs in AuditDb

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FeeEstimatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

Allow any feerate when we're fundee and are using anchor outputs: this will completely prevent unwanted channel closure.
However this can be unsafe in a high fee environment if the commit tx is below the propagation threshold.
It could be argued that when we discover it it's too late anyway, so our only option is to wait for package relay to save the day.
But I feel a bit uneasy with a completely unbounded restriction on the lower bound...
Shall we keep the check on the lower bound until package relay lands or is it useless?

Update anchor outputs feerate tolerance

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala

Unfortunately, `context.log` is *not* thread safe and shouldn't be used in future continuation. We should instead use `pipeToSelf` when we want to act on the results of a `Future`.

Fix ZmqWatcher block timeout

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3Spec.scala

The script wasn't length-delimited.
Fortunately this feature was disabled by default.
Since no-one reported the issue, we can probably just do this simple fix.

Fix remote upfront script codec

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala

If a _local_ mutual close transaction is published from outside of the actor state machine, the channel will fail to recognize it, and will move to the `ERR_INFORMATION_LEAK` state. We could instead log a warning and handle it gracefully, since no harm has been done.
This is different from a local force close, because we do not keep the fully-signed local commit tx anymore, so an unexpected published tx would indeed be very fishy in that case. But we do store the best fully-signed, read-to-publish mutual close tx in the channel data so we must be ready to handle the case where the operator manually publishes it for whatever reason.

Handle mutual close published from the outside

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala

Fixes #1995, which was due to a pattern matching error for the expected response type of `sendToX` helper methods in `EclairImpl`, and had nothing to do with json serialization. Added a few non-reg tests.
In the second commit I also set a basic "ok" json serializer for all default `RES_SUCCESS` messages, but didn't follow https://github.com/ACINQ/eclair/issues/1995#issuecomment-940821678, because we would either completely break backwards compatibility, or create inconsistency with non-default command responses like `RES_GETINFO`, and with other API calls not related to channels. Seemed better to leave it for another PR.

Fix response for `updaterelayfee`

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/Sphinx.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/crypto/SphinxSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/RelayerSpec.scala

We previously created restrictions in `Sphinx.scala` to only allow using it for two types of onions: a 1300 bytes one for HTLCs and a 400 bytes one for trampoline.
This doesn't make sense anymore. The latest version of trampoline allows any onion size, and onion messages also allow any onion size. The Sphinx protocol doesn't care either about the size of the payload.
Another reason to remove it is that it wasn't working that well with pattern matching because of type erasure.
So now the caller must explicitly set the length of the payload, which is more flexible. Verifying that the correct length is used is deferred to higher level components.

Refactor sphinx payment packet

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/MessageOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/CommonCodecsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/MessageOnionCodecsSpec.scala

This PR was quite a trip. It started because I realized after merging #1957 that since the sphinx packet doesn't really use a prefix, but rather a mix of prefix and suffix (since the mac is encoded after the payload), I actually wasn't sure the `_ - 66, _ + 66` trick was correct.
So I dived into the tests and added new ones playing with length more extensively, and I ended up with some failing tests. At some point I thought our `bytes32` codec was the culprit, so I added tests for that, but it turned out it wasn't the culprit (but I think it's worth keeping the tests, we didn't have enough coverage there). It took me quite a while to realize that it was actually my test that wasn't correctly written :face_with_head_bandage: 
Now everything is green, we have more coverage (in particular …

Simplify onion message codec

---

docs/release-notes/eclair-vnext.md
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Payment.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

The new name should be much easier to understand and matches the name used in eclair-core

Rename feeThresholdSat to maxFeeFlatSat

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala

If the remote commit confirms before our local commit, there is no reason to try to publish our HTLC transactions, we will instead directly claim the htlc outputs from the remote commit.
We previously checked timelocks before checking preconditions, which in this case means we would be waiting for a confirmation on our local commit forever. We now check preconditions before timelocks, and added a precondition that verifies that the remote commit isn't confirmed before publishing our HTLC txs.
It wasn't a big issue, we just had a watch that would linger forever and a few idle actors (until the channel closes and the channel actors stops, which stops all its publisher children), but we can easily avoid it without making the code more complex.

Abort HTLC tx publisher if remote commit confirms

---

eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

For some reason, when sending to a pre-defined channel route, we only looked at the public channel graph. This was incorrect, we should also include private channels and routing hints.
Thanks @viaj3ro for reporting this, definitely a bug in my code.
Fixes #2081

Support private channels in SendToRoute

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala

When using the API to update the relay fees of a channel, the changes are saved in the DB and then the channel is updated. If the channel can't be updated, because it is not ready yet for instance, that's fine because it will use the values from the DB as soon as it is ready. So there is no need to return an error in that case.
Fixes #2085

No error when updating the relay fees not in normal state

---

eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

Otherwise the API hangs when requesting a disconnection to a peer that is offline.

(Minor) Handle disconnect request when offline

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

The switchboard is our singleton actor entry point to all of our peers and peer connections, it can be useful to have it deliver basic information about our peers, especially when we don't have access to a peer `actorRef` yet.
This PR also fixes a bug where the `Peer` wouldn't correctly notify the `LastChannelClosed` event if it happened while the peer was disconnected.

Switchboard exposes peer information

---

eclair-core/src/main/resources/reference.conf

We've seen users bump into these limits often because many nodes now run behind Tor on poor hardware, so it makes sense to make our default values more robust.

Raise default connection timeout values

---

eclair-core/src/main/scala/fr/acinq/eclair/db/DbEventHandler.scala

We were previously subscribing to all payment events, which includes `PaymentSettlingOnChain`, for which there is nothing to do at the `DbEventHandler` level.
We now register to each concrete event instead of registering to a generic trait.

Fix unhandled event in DbEventHandler

---

eclair-core/src/main/scala/fr/acinq/eclair/balance/BalanceActor.scala
eclair-core/src/main/scala/fr/acinq/eclair/balance/CheckBalance.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala

With anchor outputs, we need to keep utxos available for fee bumping: having enough on-chain funds to claim HTLCs in case channels force-close is necessary to guarantee funds safety.
There is no perfect formula to estimate how much we should reserve: it depends on the feerate when the channels force-close, the number of impacted HTLCs and their amount. We use a very rough estimation, to avoid needlessly spamming node operators while still notifying them when the situation becomes too risky.
The choice of `sqrt` to estimate the portion of malicious channels is particularly arbitrary, but we do have to choose _something_, and it feels somewhat reasonable (or at least we can argue that in practice, it has a reasonable distribution).

Notify node operator on low fee bumping reserve

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala

In channel tests, we set a 60 seconds timeout on the receiver end, otherwise we sometimes run into timeout on slow CI machines that run a lot of tests in parallel.
It makes sense to do the same for onion messages, to help us figure out whether there is a race condition or it's just the machines that are slow.

Increase timeout onion message integration tests

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/ClientSpawner.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/MessageRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Server.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala

We may create connections to new peers for relaying onion messages but we don't want to keep them open for long.

Kill idle peers

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala

This is tiny refactoring PR of some test helpers: I extracted this from a bigger branch to avoid cluttering a future PR (with anchor outputs stuff).
A few of our test helper functions started using too many default arguments, which makes them a bit messy to use in tests, especially when we want to add new arguments without fighting to fix all existing tests that relied on positional arguments...
We change this to use method overloading instead, which makes it easier to add new overloads without changes to existing tests.

Avoid default arguments in test helpers

---

.github/workflows/latest-bitcoind.yml
BUILD.md
eclair-core/src/test/scala/fr/acinq/eclair/TestUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitcoinCoreFeeProviderSpec.scala

We should regularly run against bitcoind master, to detect if a change to bitcoind is affecting us.
This will let us detect changes that may break lightning before bitcoind releases them, giving us a chance to rectify it.
This isn't a completely unrealistic scenario since we depend on some non-standard "hacks" in our transactions formats.
For example, a change to CSV behavior was recently proposed: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-September/019400.html
If merged into bitcoin, lightning transactions wouldn't have been relayed by upgraded bitcoin nodes, so it would have been very important to catch it *before* a bitcoind release.

Add nightly build with bitcoind master

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala

The rate limit is applied on the destination side as it is too easy to cheat on the origin side.

Rate limit onion messages

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala

Use the amount **without** the fees when computing the success probability of routing through an edge.
This fixes a problem where the computed probability could be negative, leading to a shorter path after adding an edge.

Fix potential loop in path-finding

---

eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ExtraDirectives.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

Previous value was `10001950-04-24 09:07:11+00` which is out of range for Postgresql, which broke the `audit` API call on eclair nodes that were using Postgres.
9999 seems far away enough for most databases (for most SQLdialects anyway).
I chose to just change how we handle API parameters instead of modifying `Timespamp.max` to minimize the impact of this change, but it's debatable.

Set max timestamp in API call to 9999/12/31

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/balance/CheckBalanceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

We add `claim-htlc` transactions to the set of transactions that we will RBF if they don't confirm quickly.
This is important because the feerate is evaluated [when we see the remote commitment in the mempool](https://github.com/ACINQ/eclair/blob/ac9e274f0d1083319f70e08d495f20e27dd4cccd/eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala#L1048), so it may be outdated by the time we can actually publish the `claim-htlc` transaction (either because of the absolute timelock or because the remote commitment took a long time to confirm).
It's very simple to set the fees for these transactions: since we can unilaterally sign, we simply decrease the output amount and re-sign. Note that we do it for both standard commitments and anchor output commitments. For standard commitments, …

Make `ClaimHtlcTx` replaceable

---

eclair-core/src/main/scala/fr/acinq/eclair/Timestamp.scala
eclair-core/src/test/scala/fr/acinq/eclair/TimestampSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ExtraDirectives.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

This effectively reverts #2112 and implements it differently.
Having a single very conservative max value is simpler and the risk of regression is very low. Also fixed a wrong comment, previous max wasn't `11/04/2262` but a huge value.

Define 9999-12-31 as max value for timestamps

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/FinalTxPublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/balance/CheckBalanceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/FinalTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/TxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

This makes the distinction between final and replaceable txs more obvious.
Do note that this doesn't mean that final txs cannot be replaced.
Transaction replacement logic may happen outside of the tx publisher components, which will change the txid and replace the existing attempts.

Rename `RawTxPublisher` to `FinalTxPublisher`

---

eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgUtils.scala
eclair-front/src/main/scala/fr/acinq/eclair/Boot.scala
eclair-front/src/main/scala/fr/acinq/eclair/ClusterListener.scala
eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala

We use scala's `sys.exit()` instead of java's `System.exit()`, etc.

(Minor) Use `sys` package instead of `System` when applicable

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/io/MessageRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/Postman.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

I believe we can safely activate onion messages by default in our next release.
It will be interesting to see how people use it and what feature requests emerge.
We already have some rate-limiting with safe defaults in place, so I don't think this creates any risk for node operators.
On top of that, it can be very easily disabled (as explained in the release notes).
I also took this opportunity to fix an issue with the supervisor for `MessageRelay` actors, which incorrectly inherited the `resume` strategy (which makes sense for `Peer` actors).
Running the integration tests with logs activated showed many errors and warnings about this, we should have caught it earlier.
I don't know if it is related to the transient test failure we've seen.

Activate onion messages

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/SetupAndControlTlv.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

This adds the option to report a remote IP address back to a connecting peer using the `init` message.
A node can decide to use that information to discover a potential update to its public IP address (NAT) and use that for a `node_announcement` update message containing the new address.
See https://github.com/lightningnetwork/lightning-rfc/pull/917
I have successfully tested cross-compatibility with c-lightning https://github.com/ElementsProject/lightning/pull/4864

Send remote address in init

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PgUtilsSpec.scala

When using postgres, at startup we optionnally run a few basic safety checks, e.g. the number of local channels, how long since the last local channel update, etc. The goal is to make sure that we are connected to the correct database instance.

Postgres: add safety checks at startup

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FeeEstimatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala

Now that #2113 is out of the way, we can start tweaking and making small improvements to the fee-bumping mechanism.
An optimistic schedule for confirmation during force-close scenarios could in theory help malicious peers starve us of our utxos, making it hard to fee-bump HTLC transactions in high-fee environments.
If we detect that our safe utxos count is low, we try to get force-close transactions confirmed as quickly as possible, which will yield a new utxo that can be used to fund other transactions.
This PR is a deterministic alternative to #2137

More aggressive confirmation target when low on utxos

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala

When using MPP, we previously inserted an entry in the payments DB only after path-finding completed. Meanwhile, `getsentinfo` would return an empty array, so users cannot know that the payment is being attempted. This could lead to users eagerly retrying and double-paying.
We now keep track of pending payments in the `PaymentInitiator`. When the payment doesn't seem to be pending based on the DB alone, we also check the `PaymentInitiator`.
However, this doesn't entirely fix the risk of double-paying, which cannot be completely fixed from inside eclair. External applications that make payments on behalf of users must use the `externalId` and check for double payments themselves before calling eclair if they want to ensure that there's no risk of double payments.
Each commit is …

Improve `getsentinfo` accuracy

---

README.md

Eclair does not include an onchain wallet and instead uses the wallet of the bitcoin node it is connected to.
Users must also backup this wallet.

Document onchain wallet backup.

---

eclair-front/modules/awseb/run.sh

This is used by the built-in AWS Beanstalk package.
See
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html.

Front: use IMDSv2 to retrieve instance ip

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitor.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/TxPublisherSpec.scala

If a funding tx is double-spent, we can't publish our commit tx.
However, the previous code would retry very regularly in a loop, polluting the logs.
When that happens, we now only retry when a new block is found.
We should keep retrying to handle the following case:
- the mempool contains a non-replaceable commit tx and a claim-htlc-success tx (when anchor outputs is **not** used)
- the commit tx is evicted from the mempool because the mempool is full
- that automatically evicts our htlc tx as well
- after the next block, the mempool isn't as full and the commit tx is republished
- our htlc tx should automatically be republished
In the worst case, we will retry once per block and fail, until the channel is eventually closed (which stops the corresponding `TxPublisher`).

Fix publish loop when funding tx double-spent

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala

When we restart, if a downstream channel is closing with a revoked commit, we should fail the corresponding htlcs in upstream channels (because we will claim all the outgoing htlcs on-chain).
Otherwise they will be ignored until they timeout, which will cause the upstream channel to force-close (because if the revoked commit has previously been confirmed, we will not put a `WatchConfirmed` on it after a restart so we won't have the opportunity to run the corresponding `Channel.scala` code).

Ignore revoked htlcs after restart

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala

If a channel is force-closed before the funding transaction is deeply confirmed, broadcasting our local commit can be a problem if the funding tx is double spent. When that happens, the channel stays stuck in the closing state trying to publish a commit tx with an invalid input.
If we haven't even seen the funding tx in the mempool, we have no way of being sure that it was double spent, so we would need to keep trying forever, which pollutes the logs with publishing errors.
Whenever we have nothing at stake and a channel closes before reaching the normal state, we now directly go to closed.

Don't broadcast commit before funding locked

---

eclair-core/src/main/scala/fr/acinq/eclair/message/Postman.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala

Makes the code a bit cleaner and fixes a bug where `Postman` could respond with both a failure to send and later a `NoReply`.

Improve postman

---

CONTRIBUTING.md
README.md
docs/API.md
docs/Architecture.md
docs/Configure.md
docs/FAQ.md
docs/Features.md
docs/Guides.md
docs/Logging.md
docs/MultipartPayments.md
docs/TrampolinePayments.md
docs/Usage.md

The wiki on [github](https://github.com/ACINQ/eclair/wiki) has become outdated in a few places relative to similar information in README.md, in particular Installation and Configuration. Also few people know about the wiki, even though we did have a few links to it in other documentation files.
To make sure the information is up-to-date I have also tried to replicate the steps in the wiki pages that have been transformed in to files in the docs directory.

Integrate wiki into README.md and files in the docs directory

---

docs/Usage.md

Fixup for  #2165,  Usage.md  should link to ./API.md and not the deprecated wiki

fixup! Convert wiki pages in to files in the docs directory and general docs file cleanups

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

We used to compute the edge weight before checking that the edge could actually relay the payment.
Since #2111 we throw an exception in case `heuristicsConstants` are used and the edge can't relay the payment instead of just ignoring the edge.
We fix this by checking that the edge can relay the payment before trying to call `addEdgeWeight`.

Fix path-finding

---

.github/workflows/docker-image.yml

It is not really useful to build docker images for PRs and would not work anyway for forks that are not in the ACINQ repo.

Restrict building and publishing docker images to new pushes on master

---

eclair-core/src/test/resources/logback-test.xml
eclair-front/src/main/resources/logback.xml
eclair-node/src/main/resources/logback.xml

We changed the logging MDC key for tx-publishing in #2131, but forgot to add a formatting rule in logback.xml for that new field, so it wasn't written to logs.

Add txId in logback.xml

---

CONTRIBUTING.md

In particular, we let reviewers mark comments as reviewed, not PR authors, which makes reviewers' lives easier.
We've been doing this for a while, but we never wrote it down as advice for newcomers / contributors.

Add more PR details to contributing guidelines

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelDataSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala

When we receive a preimage for a htlc during a local/remote force close, we only update the htlcs and keep the rest of `LocalCommitPublished` untouched. In particular, we don't regenerate the claim-main tx (which can cause issues if fees change), and leave the `irrevocablySpent` untouched.
Last commit is a rename of several methods, it's better to review it separately. I'm not entirely satisfied with it as the naming logic isn't consistent across closing types and tx types.

Separate htlc calculation from local/remote commit (no quicklens)

---

eclair-core/pom.xml

See https://github.com/advisories/GHSA-673j-qm5f-xpv8.
We're not vulnerable, but it doesn't cost much.

Bump postgres-jdbc version

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/ChannelRelayerSpec.scala

Adds feature  "Delay channel fee update until gossip has caught up [#2110](https://github.com/ACINQ/eclair/issues/2110)"
During the `relay.fees.enforce-delay` period after a local channel update, the channel relayer will not fail payments that satisfy the base and proportional relay fee from either the current or previous channel update.
When a local channel update comes in, we store the previous channel update in the `OutgoingChannel` of the relayer along with the new current channel update. If the current channel update is less than `relay.fees.enforce-delay` minutes old we will not fail for insufficient relay fees if a relayed payment satisfies either the current or previous channel update.

Relay if fees satisfy previous channel update for X minutes after current update

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelFeatures.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt11Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Announcements.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version0/ChannelTypes0.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelFeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

Instead of defining a separate type `FeatureScope` with its own hierarchy, that was then mixed in `Feature` using the cake pattern, we go with a simpler type hierarchy for `Feature`.
This significantly simplifies type declarations (no more `Feature with FeatureScope`) especially in the tests.

Replace `FeatureScope` by type hierarchy

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/StartupIntegrationSpec.scala

Add more specific startup failure messages for situations when the configured `eclair.bitcoind.wallet` does not match the wallet(s) loaded in bitcoind.
The default `eclair.bitcoind.wallet` is the empty string. This corresponds with the situation before multi-wallet support was added to bitcoind where only one wallet could be loaded at a time. When this default setting is used, Eclair will fail at startup if more than one wallet is loaded in bitcoind. 
If only one wallet is loaded in bitcoind, then it will be used regardless of its name if `eclair.bitcoind.wallet = ""`.
If `eclair.bitcoind.wallet` is configured with a wallet name other than the empty string, then multiple wallets can be loaded in bitcoind as long as one of them is the configured wallet.
If bitcoind is launched (or …

Add messages for when startup fails due to wrong bitcoind wallet(s) loaded

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/MessageOnion.scala

When the TLV tag for encrypted data was changed from 10 to 4 (https://github.com/lightning/bolts/pull/759/commits/6e99c5feaf60cb797507d181fe583224309318e9#diff-ad65f0beaac5cef88f5fd7a8b9ca36cbc5a790f4815b4b50b9ea794a55aaf012L551) I forgot to change it in the failure case.

Fix TLV tag number in exception

---

eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala

We've seen a few reports of local channels sometimes being ignored during path-finding (e.g. #2176). When that happens, it's currently hard to know whether the channel is in the graph or not: knowing that would let us know if there is a bug in the graph management code or the path-finding algorithm itself.
I'm adding a few logs to the relevant components:
- when a route request is received, we log the direct channels we have with that peer (if any): that will let us know whether our channels are considered or not
- when a local channel is added or removed from the graph, we log something: that will let us pinpoint whether some channels are missing from the graph when they should be in it

Add logs about local channel graph inclusion

---

.github/workflows/latest-bitcoind.yml

GitHub asks users to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
StepSecurity is working on securing GitHub workflows and [OSSF Scorecards](https://github.com/ossf/scorecard) recommends using StepSecurity's secure-workflows online tool [app.stepsecurity.io](https://github.com/cosmos/cosmos-sdk/pull/app.stepsecurity.io) to improve the security of GitHub workflows.
This repository has a Scorecards score of 0/10 in the `Token-Permissions` category with 10 being the most secure.
We have fixed one of the repo's workflow(s) …

Add token permissions for latest-bitcoind.yml

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

When using multipart payments, the path-finding request sent to the router does not match the actual payment, it is only a request to route a fraction of the amount but the fee budget is still the one for the full payment. As a consequence the router will return routes that will not satisfy the fee budget.
The fee budget is checked one last time before relaying the payment but ignoring the fee of the first channel (which should not be ignored for trampoline relays). I fix this last check.

Fix fees for trampoline relay

---

.github/workflows/latest-bitcoind.yml

The build against bitcoind master (see https://github.com/ACINQ/eclair/actions/workflows/latest-bitcoind.yml) broke on march 12 (and subsequent builds as well) with the following errors while installing dependencies:
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.2.6-0ubuntu0.1~20.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libegl1_1.3.2-1~ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libglx-dev_1.3.2-1~ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/li …
```

Fix latest bitcoin build

---

eclair-core/src/test/scala/fr/acinq/eclair/io/NodeURISpec.scala

The eth0 interface does not exist on some machines which causes the tests to fail.

Remove ipv6 zone identifier test

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala

The `option_scid_alias` feature (https://github.com/lightning/bolts/pull/910) is going to clash with the feature bit we use for trampoline payments. Fortunately we've never advertised it, so we can simply update it to a much higher value for now (until the final version of trampoline is specified).
We don't need to implement backwards-compatibility because no-one is generating trampoline invoices from eclair or paying trampoline invoices from eclair AFAIK. We will need to implement some backwards-compatibility in `lightning-kmp` however to ensure that Phoenix can smoothly transition to the new feature bit.

Update experimental trampoline feature bit

---

eclair-core/src/main/scala/fr/acinq/eclair/DBChecker.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala

On startup, we check that for each of our channels the public key derived from the channel seed matches the key that was
used when the channel was funded.

Check that channel seed has not been modified

---

eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala

When Phoenix was based on a branch of eclair, we needed a workaround for invoice backwards-compatibility.
Now that Phoenix uses `lightning-kmp` instead of eclair, we can remove that work-around.
We are now fully spec-compliant regarding feature dependency validation.

Remove Phoenix workaround for `payment_secret` dependency

---

docs/release-notes/eclair-vnext.md
eclair-core/eclair-cli
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Node.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

This API call was added for certain uses cases where killing the process was impractical but internally it just calls `sys.exit()`.
Eclair is designed to shutdown cleanly when its process is killed and this is still the recommended way of stopping it.

Add a "stop" API method

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/ChannelTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/CommonCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/InteractiveTxTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/TlvCodecs.scala
eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

This PR adds definitions for the messages and types used by [dual funding](https://github.com/lightning/bolts/pull/851).
Note that the codecs are slightly different from what is currently proposed in the spec, but [a PR has been opened](https://github.com/niftynei/lightning-rfc/pull/3) to add the proposed changes to the spec.
This is very tedious to review, don't focus on all the byte-level details, but it's interesting to look at what changes between `open_channel`/`accept_channel` v1 and this v2.

Add dual funding codecs and feature bit

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

In path-finding, we give a better score to channels with higher capacity because they have a higher change to have enough balance to relay the payment. But for local channels we know the balance so we can be sure that the payment can be relayed.

Give best capacity score to local channels

---

eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala

It was creating a race condition in the test `MultiPartHandlerSpec`.`PaymentHandler should reject incoming multi-part payment with an invalid expiry` due the 0-expiry invoice being immediately purged.

Disable invoice purger in tests

---

eclair-core/src/main/scala/fr/acinq/eclair/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LegacyChannelCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala

We add a new TLV-compatible field to `funding_signed`/`commit_sig` and send additional commitment signatures for a set of feerates (1, 2, 5, 10 sat/B) (only when there are no htlcs).
We also gracefully handle the case where remote decides to use one of those additional signatures to unilaterally close the channel. This creates yet another remote-close scenario, named _custom_, on top of the existing with _current_/_next_/_future_. 
Note that:
- since we use static remote key, there isn't anything to do in case of a custom close, since there are no htlcs
- codecs haven't been updated, there is no need.

Send additional commitment sigs with various feerates

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitorSpec.scala

Using the same test probe to get the current block height and watch the mempool can lead to rare race conditions, such as:
```
MempoolTxMonitorSpec:
- transaction confirmed *** FAILED ***
java.lang.AssertionError: assertion failed: expected class org.json4s.JInt, found class fr.acinq.eclair.channel.publish.MempoolTxMonitor$TxInMempool (TxInMempool(649207d7e7b8fcb8fdf851f28c4abfffadf926b8917c2ca53ca729b4fb5bb8bd,BlockHeight(151)))
at scala.Predef$.assert(Predef.scala:279)
at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:572)
at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
at fr.acinq.eclair.blockchain.bitcoind.BitcoindService.currentBlockHeight …
```

Fix flaky MempoolTxMonitor test

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala

Dijkstra's algorithm assumes that each edge has a fixed weight that does not depend on the rest of the path. In our case this assumption is broken when computing a cost for failed payments as it depends on all the edges of the path. We fix this by adding the possibility to use log probabilities which can be added per edge and offer a good approximation as long as the probabilities stay close to 1.
Edges still don't have a perfectly fixed weight because the fee of an edge depends on the fees of the previous edges, however since fees are typically low, it shouldn't matter in practice.

Use log probability in path-finding

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Sync.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala

While zlib provides good compression results for gossip, it's a dependency that had a few important CVEs in the past. Some implementations are reluctant to import it, so we decided to remove it from the specification in https://github.com/lightning/bolts/pull/981
We stop compressing with zlib and only send uncompressed results, while still supporting receiving compressed data. We will remove support for decompression once our monitoring indicates that we stopped receiving compressed data.

Stop compressing with zlib

---

eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala

In tests we can sleep for at least X seconds but because of other tests running in parallel, we can't get an upper bound on the sleeping time. This makes some tests that depend on time unfeasible.
Fixes #2175 #2276

Fix flaky test PeerConnectionSpec

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRouterIntegrationSpec.scala
eclair-front/src/test/scala/fr/acinq/eclair/router/FrontRouterSpec.scala
pom.xml

This is a simpler alternative to #2268.
In this PR we add a basic integration test between `Channel` and `Router` that checks the proper handling of local announcements.
This test found two bugs, fixed in two separate commits.

Add simple integration test between `Channel` and `Router`

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/CommonCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

We discussed the proposed changes (https://github.com/niftynei/lightning-rfc/pull/3) during yesterday's spec meeting, and agreed on the following changes:
* Use `u16` instead of `varint` for lengths
* Revert channel flags extension: we will use tlvs for future use-cases instead of channel flags
* Remove support for non-native segwit inputs (which removes the need to transmit a `scriptSig` field in `tx_add_input`)
NB: this builds on top of #2237 (necessary to continue dual funding work on other branches)

Update dual funding codecs

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/ChannelRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/RelayerSpec.scala

This is a preparation for https://github.com/lightning/bolts/pull/910.
The relaying logic is now based on the `channelId` instead of
`shortChannelId`.
We used to consider `shortChannelId` as a unique identifier for the
channel, but it's not true anymore: there will be multiple aliases per
channel.

Use long id instead of short id in `ChannelRelay`

---

eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

Builds on #2270.
This is the final preparatory step before we can introduce channel aliases, which are arbitrary values of type `ShortChannelId`. We had to move to a stable identifier for private channels. Public channels can keep using the `shortChannelId`, it is stable because it is a "real scid" (and only used after 6 confs) and is useful as an index for channel queries.

Index unannounced channels on `channelId` instead of `shortChannelId` in the router

---

eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigrateChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigrateNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala

There is no point in formatting the json since the `JSONB` data type that we use in postgres do not preserve formatting.

(Minor) Postgres: use write instead of writePretty

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala

This gives more time to rollback the funding tx in case where we moved from `WAIT_FOR_FUNDING_INTERNAL`->`CLOSED` and unlock utxos.
We could do it differently, with an additional state, or by only sending the "shutdown" symbol after we receive the wallet response for this specific transition, but it would be more complicated.

Increase `CLOSED` timeout from 10s to 1min

---

eclair-core/src/main/scala/fr/acinq/eclair/MilliSatoshi.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestUtils.scala

The path needed to be adjusted from "target" to "eclair-core/target".
Also fixed a typo in a comment.

Fix test when run in Intellij (#2288)

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala

When running behind a load balancer that doesn't preserve the client source IP address, it doesn't make sense to include the `remote-address` tlv in our `init` message, it will contain an IP address that is completely unrelated to our peer.
Fixes #2256

Add option to disable sending remote address in init

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitor.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/MempoolTxMonitorSpec.scala

Even though we use our anchor to CPFP our commit tx, the commit tx could confirm on its own. If that happens, we don't care about the anchor tx so we shouldn't RBF it. Ideally we'd like to cancel it but that's impossible, so we just wait for it to either confirm or drop out of mempools after a while.
I couldn't easily add a unit test for this, because the test would need to be able to publish the commit tx and our anchor tx, and then generate a block that includes the commit tx but not our anchor tx. Unfortunately the `bitcoind` RPCs on `regtest` don't easily allow such granularity, so please review carefully (it's quite a simple `if` so I think we're ok).

Don't RBF anchor if commit is confirmed

---

eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelFeatures.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version0/ChannelTypes0.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelFeaturesSpec.scala

We create a new feature trait for permanent channel features that aren't part of the channel type. These features must be included in our `ChannelFeatures` at channel creation time.
It's important to separate them from features that belong to the `channel_type`, otherwise we couldn't use a `channel_type` that's different from the one we'd pick based on init features alone. Let's provide an example to explain this:
- Alice and Bob's `init` contain `option_static_remotekey` and `option_anchors_zero_fee_htlc_tx`
- Alice wants to open an `option_static_remotekey` channel that doesn't use anchor outputs
- That's perfectly acceptable, and in that case the `channelFeatures` must not contain `option_anchors_zero_fee_htlc_tx`

Add trait for permanent optional channel features

---

eclair-core/src/main/scala/fr/acinq/eclair/router/BalanceEstimate.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/StaleChannels.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BalanceEstimateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

This is a PR on #2272 
It contains two commits that should be reviewed separately.
Please read the commit messages, they contain more details about each commit.
This first commit doesn't contain any meaningful logic changes, it's mostly refactoring and code clean-up, it should be quite straight-forward even though it contains many line changes.
The second commit focuses on the balance estimation business logic, and I'm curious to get your thoughts. It does two things: add a `didReceive` (symmetric to `didSend`) and fix a division by zero. I spent a lot of time trying to figure out if we could do a more meaningful update in the parallel channels case of `didSend`, it feels like we're not doing enough, but I didn't find a better solution...

Small improvements to balance estimation

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/TwoNodesIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala

There was a race condition between the `wait_for_funding_locked` state and the `normal` state. By only waiting for the channel to have handled the last message it could either be still in `waiting_for_funding_locked` or already in `normal.

Fix minimal node fixture flakyness

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/BalanceEstimate.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/StaleChannels.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BalanceEstimateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

Alternative to #2263 that uses the maximum capacity of all the channels between two nodes instead of the sum.
It make the balance information not symmetrical.

Balance estimate per side

---

eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala

I added the 2 tests that I suggested but noticed something surprising.
The test for the [wikipedia example](https://en.wikipedia.org/wiki/Yen%27s_algorithm#:~:text=Yen's%20algorithm) is not returning the expected results. I suspect that there is at least one bug. I'm reluctant to make the change in the production code because of my current lack of understanding, but if I remove the `reverse` from [this line](https://github.com/ACINQ/eclair/blob/9c7ddcd8745bbea9c7113457e1a1f378435347c7/eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala#L227), then at least the call to `dijkstraShortestPath` returns the shortest path that was expected. But even after making that fix, assuming that it is a correct fix, the next 2 shortest paths also do not match what is in the wikipedia article …

Add more GraphSpec tests (#2292)

---

eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelFeatures.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/FundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/test/scala/fr/acinq/eclair/ShortChannelIdSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3Spec.scala

This is a PR on #2224, best reviewed commit-by-commit.
The first commit contains only some clean-up and nits.
The second commit removes the use a depth 0 watch-confirmed (which is quite hacky) and instead skips the `WAIT_FOR_FUNDING_CONFIRMED` state entirely, which fits better with our model, at the cost of duplication a few lines of code (which we could refactor to a dedicated function, but I'd rather have them explicitly in each event handlers as they vary slightly depending on the case).
The third commit contains a few small changes to `Validation.scala`. The most important change is that we lost a call to `updateBalances` in #2224 by moving the initialization of private channels in the handler of `ShortChannelIdAssigned`, which we restore in `handleLocalChannelUpdate`, otherwise …

Remove watch-confirmed with depth 0 in zero-conf

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/CommonCodecs.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestUtils.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/RestoreSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/ZeroConfAliasIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRouterIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Channel.scala

This is a PR on #2224 to improve some of the tests.

Improve tests in #2224

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version0/ChannelCodecs0.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version1/ChannelCodecs1.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version2/ChannelCodecs2.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3Spec.scala

So we don't need to rename them when a new codec is added.

(Minor) Include the discriminator in all channel codecs

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/ThreeNodesIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/ZeroConfAliasIntegrationSpec.scala

This build failure: https://github.com/ACINQ/eclair/runs/6901214111 was possibly caused by the register not yet having been notified of the real scid.

Fix flaky `ZeroConfAliasIntegrationSpec`

---

eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/ShortChannelIdSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/ExtendedQueriesCodecsSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/serde/FormParamExtractors.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

This is a conversion that can fail by throwing an exception, which is dangerous.
It's only used in tests, so we're moving this to a test file to ensure we don't accidentally use it in non-test code.

Clean up scid parsing from coordinates string

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala

We can currently deduce the `channel_id` of a public channel because it is based on the funding transaction coordinates, but that won't be the case with dual-funding, where the `channel_id` will be private information between the two channel peers.

Remove `channelId` from `PublicChannel`

---

eclair-core/src/test/scala/fr/acinq/eclair/TestDatabases.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/ThreeNodesIntegrationSpec.scala

Create new database for each unit test instead of spawning a new db instance.

Reuse postgres instance in tests

---

docs/Monitoring.md
eclair-core/pom.xml
eclair-node/src/main/resources/application.conf

In this PR I have made following additions:
- Added dependencies for exposing metrics for Prometheus.
- Added default configuration for kamon.prometheus in `application.conf` (eclair node).
- Update `Monitoring.md`.

Expose scraping endpoint for prometheus metrics

---

eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
eclair-core/src/test/scala/fr/acinq/eclair/ShortChannelIdSpec.scala

This is an alternative to #2316.
Turns out the value space is large enough to not have to worry about duplicates.

Random values for `generateLocalAlias()`

---

eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
eclair-core/src/test/scala/fr/acinq/eclair/crypto/TransportHandlerSpec.scala

If the current chunk of data read from the TCP connection only contains unknown messages (in particular, could be only one isolated unknown message on an otherwise idle connection), we never resumed reading on the connection.
This means all subsequent messages, including pings/pongs, won't be read, which is why the most visible effect is disconnecting due to no response to ping.
Related to https://github.com/ElementsProject/lightning/pull/5347.
Reported by @wtogami.

Resume reading after processing unknown messages

---

docs/Configure.md
docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala

The `override-init-features` field in `eclair.conf` was not previously applied on top of the `features` field, so node operators were usually copy-pasting their `features` overrides in every `override-init-features`.
The overrides are now applied on top of the base `features` configuration, which makes it easier and more intuitive to configure per-node features.

Additive per-node feature override

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelFeatures.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelFeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/ZeroConfActivationSpec.scala

We restrict 0-conf activation on a per-peer basis. When 0-conf is activated by both peers, we use it even if it wasn't part of the `channel_type`. This matches the behavior of `cln` and `ldk`, who will not set that feature bit in the `channel_type` (but will will accept if we set it, because `lnd` on the contrary will always set the feature bit in the `channel_type`).

Activate 0-conf based on per-peer feature override

---

eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala

Calling `ConfigFactory.load()` automatically resolves the config (that is, processes substitutions), but that's not the case for `ConfigFactory.parseFile`, which means that substitutions don't work in `eclair.conf`.
We could resolve each of config separately, but the library's doc recommends one global `resolve()`, and frankly it makes more sense:
> A given Config must be resolved before using it to retrieve config values, but ideally should be resolved one time for your entire stack of fallbacks (see withFallback)
https://github.com/lightbend/config/blob/4458ea947a7a2a668bb811a122455f1f05975172/config/src/main/java/com/typesafe/config/Config.java#L204-L206
Fixes #2336.

Call `resolve()` on configuration

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FeeEstimatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

When a channel force-close without any pending htlcs, funds are not at risk. We want to eventually get our main output back, but if we are not in a rush we can save on fees by never spending the anchors.
This is disabled by default as there is a potential risk: if the commit tx doesn't confirm and the feerate rises, the commit tx may eventually be below the network's min-relay-fee and won't confirm (at least until package relay is available).

Allow disabling no-htlc commitment fee-bump

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala

Fixed https://github.com/ACINQ/eclair/issues/2295 using the second proposed approach so that values near the extremes will still be distinct.

Fix RoutingHeuristics.normalize (2295)

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala

In `SendPaymentToNode`, the routing hints were present twice: once in `invoice` and once in `extraEdges`. I'm only keeping `invoice`.
Also make the `ExtraEdge` trait use `def` as there may be problems with `val`.

Remove redundant routing hint

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala

We were using hints from `SendPaymentConfig.invoice` to populate `PathFindingExperimentMetrics`, but the invoice is optional and not populated for trampoline relay.

Use the correct extra edges to put in metrics

---

eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerEvents.scala

create pong event and publish pongs, so plugins can subscribe to the latency of the peers

Emit event when receiving `Pong`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala

When we have nothing at stake (channel was never used and we don't have funds to claim), we previously directly went to the CLOSED state without publishing our commitment. This can be an issue for our peer if they have lost data or had a hard time getting a funding tx confirmed.
We now publish our commitment once to help them get their funds back in all cases and avoid the CSV delays when getting their funds back.
Fixes #1730

Broadcast commit tx when nothing at stake

---

eclair-core/pom.xml

This should fix an intermittent segfault, see:
- failed build: https://github.com/ACINQ/eclair/runs/7741716877
- upstream issue: https://github.com/xerial/sqlite-jdbc/issues/680

Update sqlite to 3.39.2.0

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

This lets callers override the default duration or ban channels for unlimited durations (until they send a `ListChannelExclusion`).
Fixes #2364

Add explicit duration to `ExcludeChannel`

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala

This is a follow up of #2264 where we refactor handling of channel updates in failures coming from routing hints.
For failures in one of the routing hints, we use the `node_id` pair (source, destination) instead of the `short_channel_id` to identify the failing edge.

Refactor routing hint failure updates

---

eclair-core/src/main/scala/fr/acinq/eclair/router/StaleChannels.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

We previously incorrectly pruned only once both channel updates were stale. This was incorrect, we must prune channels as soon as one side becomes stale.
There are ~100 channels on the network today that have one inactive side, while the other side regularly refreshes their channel update, but those channels won't be usable for routing. They should eventually be closed, but the active side is probably hoping for the inactive side to come back online to get the opportunity to do a mutual close.

Prune channels if any update is stale

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala

Apply @rustyrussell's neat truncating integer arithmetic formula to calculate the amount that should be forwarded by blinded path nodes instead of our previous approximation.
This simply expands `ceil(a/b)` as `(a+b-1)/b` and provides better results in practice (I ran a simulation with many values for fees and amount).

Fix blinded path amount to forward calculation

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala
eclair-core/src/test/scala/fr/acinq/eclair/crypto/SphinxSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt12InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/RouteBlindingSpec.scala

To match the latest changes in https://github.com/lightning/bolts/pull/765 at commit https://github.com/lightning/bolts/pull/765/commits/aed5518a80aade56218da87f92e0a39963b660cf
The main change was the introduction of the `payment_relay`, `payment_constraints` and `allowed_features` tlvs, with small additional codec updates.

Update route blinding test vectors

---

eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ExtraDirectives.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

When not provided, we previously used unrestricted `from` and `to` parameters when reading from the DB. This can create issues when accidentally reading too much data.
We now limit this to the last 24 hours, unless explicitly set by the caller. Note that when reading a lot of data, it's recommended to use postgres and read from a replica to ensure there's no impact on the running eclair instance.
Thanks @DerEwige for raising this!
Fixes #2383

Limit default `from` and `to` API parameters

---

README.md
docs/Configure.md
docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/ExplorerApi.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/LocalChannelKeyManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/LocalNodeKeyManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/package.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt11Invoice.scala
eclair-core/src/test/scala/fr/acinq/eclair/PackageSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdogSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
pom.xml

Requires 0.24 version of bitcoin-lib ([#70](https://github.com/ACINQ/bitcoin-lib/pull/70)) which exposes hash of signet genesis block.

Add support for the `signet` test network

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala

Nodes also asynchronously republish funding txs after a restart, but we want to test the closing behavior so we ignore these events.

Fix dual funding flaky test

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala

We need to validate early that a `tx_add_input` message can be converted into an `OutPoint` without raising an out of bounds exception. With the previous ordering, the check for duplicate inputs could throw an exception.
We also fix a flaky test on slow machines: we need to wait for actors to be in the right state before accessing the data, otherwise the cast may fail.

Check input out of bounds early in `tx_add_input`

---

eclair-core/src/test/scala/fr/acinq/eclair/wire/internal/channel/ChannelCodecsSpec.scala

The test `ChannelCodecsSpec.backward compatibility older codecs (integrity)` uses reference json stored as text files. Depending on git settings and OS, the test may fail due to line ending differences.

(Minor) Ignore line ending when comparing strings in tests

---

eclair-core/src/main/scala/fr/acinq/eclair/balance/CheckBalance.scala
eclair-core/src/test/scala/fr/acinq/eclair/balance/CheckBalanceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala

While it makes sense to assume that relayed payments will fail in the context of balance computation (meaning that we don't earn a fee), the opposite is true for payments sent from the local node, which will cause the full htlc amount to be deducted from the balance.
This way we are consistent: the balance computation is pessismistic and always assume the lowest outcome.

Assume sent htlcs will succeed in the balance computation

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/OnChainWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/DummyOnChainWallet.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

If your peer uses unconfirmed inputs in the `interactive-tx` protocol, you will end up paying for the fees of their unconfirmed previous transactions. This may be undesirable in some cases, so we allow requiring confirmed inputs only. This is currently set to false, but can be tweaked based on custom tlvs or values in the open/accept messages.

Add option to require confirmed inputs in interactive-tx

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala

We previously generated random values, but the randomness doesn't protect against anything and adds a risk of re-using the same serial ID twice. It's a better idea to just increment serial IDs (while respecting the parity spec requirement).

Use deterministic serial IDs in interactive-tx

---

eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
eclair-core/src/test/scala/fr/acinq/eclair/ShortChannelIdSpec.scala

The bug is due to mistakingly using the `^` as power operator, while it instead is a `xor`. As a result, the available space for local alias was tiny, resulting in collisions. This in turns causes the `relayer` to forward `UpdateAddHtlc` to the wrong node, which results in `UpdateFailMalformed` error due to the peers being unable to decrypt the onion that wasn't meant for them.
Nice catch @robbiehanson!

Fix collision bug in local alias generation

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/CommandCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/FailureMessage.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala
eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/internal/CommandCodecsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/PaymentOnionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/RouteBlindingSpec.scala

This is best reviewed commit-by-commit: each commit contains a detailed description of what it achieves. This is a pre-requisite for #2395 and #2401, since it introduces a new `total_amount_msat` tlv which lets us get rid of the `payment_data` field.
The first and third commits deserve more tests, but they cannot be added now since we're lacking the utilities to send to a blinded route. We will add those tests in a future PR, once all the components for blinded payments are available.
This implements the changes to https://github.com/lightning/bolts/pull/765 after commit https://github.com/lightning/bolts/pull/765/commits/485c2b1a5bc5b7dc1eed919a47a036988cc540f4 (included).

Implement latest route blinding spec updates

---

eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala

Enable receiving blinded payments.
Unroll the dummy hops at the end of a blinded route.

Allow receiving to blinded routes

---

eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt11InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala

Add non-reg tests to ensure that we only validate invoice features, and correctly refuse to pay invoices containing unsupported mandatory features.

Add tests for invoice feature validation

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

In dual funded channels the reserve is computed automatically. But our model allows setting a reserve even for dual funded channels.
Changing the model is too much work, instead this PR proposes to:
- add `require`s in the `Commitments` class to verify at runtime that we are consistent (it would cause the channel to fail before it is created)
- pass the `dualFunded` status to `Peer.makeChannelParams` so we only build valid parameters.
We could also alter the handlers for `SpawnChannelnitiator`/`SpawnChannelNonInitiator` and mutate the `LocalParams` depending on the value of `dualFunded`. It is less intrusive but arguably more hacky.

Don't set channel reserve for dual funded channels

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/FixtureUtils.scala

When using a custom logger for log capture in tests (with `akka.loggers=["fr.acinq.eclair.testutils.MySlf4jLogger"]`), we need to explicitly disable the "hardcoded" slf4j logger for akka typed, otherwise we will end up with duplicate slf4j logging (one through our custom logger, the other one through the default slf4j logger).
See the rationale for this hardcoded sl4j logger here: https://doc.akka.io/docs/akka/current/typed/logging.html#event-bus.

Fix duplicate SLF4J loggers in tests

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/PaymentOnionSpec.scala

This is the first step in adding "async payments" as described in issue #2424 .

Add initial support for async payment trampoline relay

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala

These two fuzz tests setup a random set of HTLCs and then try to send or receive the maximum available amount. The initial HTLC setup may fail, if the initial balances are too low.
It is hard to set those initial balances to ensure this will always work, but since this will only rarely randomly happen, we should simply ignore it (instead of failing the test).

Fix `availableForSend` fuzz tests

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/ChannelTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/InteractiveTxTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/MessageOnion.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RoutingTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/SetupAndControlTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/TlvCodecs.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/TlvCodecsSpec.scala

We previously duplicated `variableSizeBytesLong(varintoverflow, ...)` whenever we wanted to work with a tlv field.
This was confusing and error-prone, so it's now factored into a specific helper codec. We also remove the length-prefixed truncated int codecs, as they are always used in tlvs and should simply use this new tlv field codec instead.

Add `tlvField` codec

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala

Currently, for an incomming payment we check that the CLTV delta is larger than the minFinalExpiryDelta from the invoice. However with BOLT 12, invoices no longer contain a minFinalExpiryDelta (not yet visible in eclair code, BOLT 12 moves fast!). I suggest to use the minFinalExpiryDelta value from the node params instead. Since we use this value for all the invoices we create, it doesn't change much. The only case where it would have an impact would be if we create an invoice, then shutdown, change the conf, restart, and only then someone tries to pay the invoice; in that case we would probably want to enforce the new conf anyway.

Validate payment using minFinalExpiryDelta from node params

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/ChannelTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/MessageOnion.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RoutingTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/SetupAndControlTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/TlvCodecs.scala

We currently accept some malformed TLVs with additional data that we ignore. This means that decoding and reencoding may give a different result. With this change, we now reject such TLVs.

Complete codec for TLV fields

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/zeroconf/ZeroConfActivationSpec.scala

If we have activated 0-conf support for a given peer, we send our `channel_ready` early regardless of whether our peer has activated support for 0-conf. If they also immediately send their `channel_ready` it's great, if they don't it's ok, we'll just wait for confirmations, but it was worth trying.

Use 0-conf based on local features only

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/OnionMessagesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala

We used to drop onion messages above a certain size, but the onion message packet is already limited to 65536 bytes so we only keep this larger limit instead.

Remove onion message size limit

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/ChannelTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptDualFundedChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenDualFundedChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingInternalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/RustyTestsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

We add a tlv to `open_channel2` and `accept_channel2` to require our peer to only use confirmed inputs, as proposed [here](https://github.com/lightning/bolts/pull/851#discussion_r994954281). Using only confirmed inputs ensures that we don't end up paying the fees of one of our peer's unconfirmed ancestors.
This can be configured at two levels:
- globally using `eclair.conf`
- on a per-channel basis by overriding the default value in `Peer.OpenChannel`
This PR contains a breaking change in the codecs: since dual funding isn't released yet, it's ok to make such a breaking change now: this is why I'd like to integrate this PR now, even though the final value of the TLV isn't specified yet. Updating the TLV can be done later without breaking compatibility.
This PR is probably best reviewed …

Add tlv to require confirmed inputs for dual funding

---

eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/StaleChannels.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/NetworkDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

When a channel was pruned and we receive a valid channel update for it, we need to wait until we're sure both sides of the channel are back online: a channel that has only one side available will most likely not be able to relay payments.
When both sides have created fresh, valid channel updates, we restore the channel to our channels map and to the graph.
We remove the custom `pruned` table and instead directly use the data from the channels table.
Fixes #2388

Fix pruned channels coming back online

---

README.md

Explain why we chose to delegate most onchain tasks to bitcoin core (including onchain wallet management), the additional requirements that it creates and also the benefits in terms of security.

Explain how and why we use bitcoin core

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

We previously had a few error messages where we would send the complete offending transaction instead of just its txid. This can be dangerous if we accidentally send a signed transaction that our counterparty may broadcast.
We are currently careful and avoid sending signed transaction when it may be dangerous for us, but there's a risk that a refactoring changes that. It's safer to only send the txid.

Only use txid in error messages

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala

When nodes receive HTLCs, they verify that the contents of those HTLCs match the intructions that the sender provided in the onion. It is important to ensure that intermediate nodes and final nodes have similar requirements, otherwise a malicious intermediate node could easily probe whether the next node is the final recipient or not.
Unfortunately, the requirements for intermediate nodes were more lenient than the requirements for final nodes. Intermediate nodes allowed overpaying and increasing the CLTV expiry, whereas final nodes required a perfect equality between the HTLC values and the onion values.
This provided a trivial way of probing: when relaying an HTLC, nodes could relay 1 msat more than what the onion instructed (or increase the outgoing expiry by 1). If the next node was …

Allow nodes to overshoot final htlc amount and expiry

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/Paginated.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/jdbc/JdbcUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/receive/InvoicePurgerSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ExtraDirectives.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Invoice.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/OnChain.scala

Fixes https://github.com/ACINQ/eclair/issues/2450
cc: @ShahanaFarooqui

Add pagination on listInvoices

---

README.md
docs/release-notes/eclair-vnext.md
eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunder.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
pom.xml

This release of bitcoind contains several bug fixes that let us simplify our fee bumping logic:
- fixed a bug where bitcoind dropped non-wallet signatures
- added an option to fund transactions containing non-wallet inputs
It also has support for Taproot, which we obviously love.

Update to bitcoind 23.0

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/Paginated.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPaymentsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/receive/InvoicePurgerSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/directives/ExtraDirectives.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Fees.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Invoice.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Node.scala

The default values for the `from` and `to` parameters of some API requests were generated once when the eclair node starts instead of being recomputed for every request.
We also add `count` and `skip` argument to `listPendingInvoices` since it was added to `listInvoices`.
Fixes https://github.com/ACINQ/eclair/issues/2475

Fix static default `from` and `to` pagination

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/CommonCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala

Fixes a circular dependency between `OfferCodecs.scala` and `LightningMessageCodecs.scala` by putting feature codecs in `CommonCodecs.scala` instead.
This bug did not prevent compilation of the whole project but did prevent running tests for Bolt12Invoice independently of the rest.

Fix circular dependency

---

eclair-core/eclair-cli

in "short/compact mode" (-s), eclair-cli was not getting short channel ids from the right place and they were always set to null.

Make `eclair-cli -s` display short channel ids correctly

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala

In case of a zero-hop blinded route, the final blinding point is not in the `UpdateAddHtlc` but in the payload itself.

Accept payments to zero-hop blinded route

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/BlindedRouteCreation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BlindedRouteCreationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/RouteBlindingSpec.scala

We'd like to avoid having the `wire` package depend on data types defined in the `router` package, the other way around is better as suggested by @thomash-acinq.

Move route blinding construction to RouteCalculation

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala

This is a follow up to #2360 which was actually buggy: the channel actor doesn't stop itself immediately after going into the CLOSED state, so it received a `WatchFundingTxSpent` event that was handled in the global `whenUnhandled` block, logged a warning and went back to the CLOSING state.
We now go through the normal steps to close those channels, by waiting for the commit tx to be confirmed before actually going to CLOSED.

Fix closing channel state when nothing at stake

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingCreatedStateSpec.scala

According to the dual funding specification, the peer that has [contributed the smaller amount](https://github.com/niftynei/lightning-rfc/blob/nifty/dual-fund/02-peer-protocol.md#requirements-4) of `tx_add_input` must sign first. We incorrectly used the contributions to the funding output instead of the sum of the inputs values. This requirement guarantees that there can be no deadlocks when nodes are batching multiple `interactive-tx` sessions.
When building the first version of a dual-funded transaction, we should use `error` instead of `tx_abort` if we encounter a failure. It makes it more explicit to our peer that the channel should be closed at that point, whereas `tx_abort` can be used in RBF attempts to abort a secondary `interactive-tx` sessions without closing the channel. …

Implement correct ordering of `tx_signatures`

---

eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/zeroconf/ZeroConfAliasIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

The introduction of `scid-alias` broke the ability to create a valid route to our own node using `FinalizeRoute` for private or unconfirmed channels because we use our local alias as the shortChannelId of the graph edge in both directions.
Using the same identifier for both directions makes sense, because it's a stable identifier whereas the remote alias could be updated by our peer. It's generally not an issue, except when we are building a route, because our peer will not know how to route if we give them our local alias in a payment onion (they expect their own local alias, which from our point of view is the remote alias).
The only way to build routes to ourselves is by using `FinalizeRoute`, so we fix the issue only in this handler by looking at our private channels when we notice …

Create routes to self using remote alias

---

README.md
docs/Configure.md
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala

Starting with bitcoind 23.0, a new `changetype` parameter was introduced. If not specified, bitcoind will generate a change output with a type that matches the main output to make it harder for chain analysis to detect which output is the change.
The issue is that lightning requires segwit utxos: if an on-chain payment is sent to a non-segwit address, we still want our change output to use segwit, otherwise we won't be able to use it. We thus must set `addresstype` and `changetype` in `bitcoin.conf` to ensure we never generate legacy change addresses.

Test change address type generation

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala

When a channel is pruned, it is removed from our graph and thus isn't found by `d.resolve()`, but it shouldn't create a warning in the logs, this isn't an unknown channel.

Remove warning for pruned local channel update

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala

We used to store UNIX timestamps in the waitingSince field before moving to block count. In order to ensure backward compatibility, we converted from timestamps to blockheight based on the value.
This code has shipped more than a year ago, so we can safely remove that compatibility code since it only applies during the channel open or close period, which cannot last long anyway.
Fixes #2125

Remove compatibility code for waitingSince

---

eclair-core/src/main/scala/fr/acinq/eclair/db/jdbc/JdbcUtils.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/CompareDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/migration/MigrateDb.scala

We weren't correctly closing SQL statements when comparing DBs and migrating them. All the DB handlers for normal operation (read/write channels, payments, etc) are already correctly closed after execution.
@DerEwige the issue was only in those migration handlers, otherwise we correctly use `using` everywhere which closes DB statements and their corresponding `ResultSet`.
Fixes #2425

Close SQL statements during migrations

---

eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala

When wallet transactions are evicted from the mempool (because their fee is too low), we have a strong dependency on bitcoind's behavior: it must not double-spend the inputs of the evicted transaction, otherwise it could break 0-conf channels.
We verify that behavior in a unit test where we set the mempool to 5MB (the minimum authorized mempool size) and simulate this eviction scenario.

Add mempool eviction tests

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

When sending an outgoing multi-part payment, we forward the preimage back to the sender as soon as we receive the first `update_fulfill_htlc`. This is particularly useful when relaying trampoline payments, to be able to propagate the fulfill upstream as early as possible.
However this meant that callers of the HTTP API would receive this preimage event instead of the final payment result, which was quite bad. We now disable this first event when used with the `--blocking` argument, which ensures that the API always returns the payment result.
Fixes #2389

Improve `payinvoice` API response

---

eclair-core/src/main/scala/fr/acinq/eclair/io/MessageRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerReadyNotifier.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerReadyNotifierSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

We add an actor that waits for a given peer to be connected and ready to process payments.
This is useful in the context of async payments for the receiver's LSP.
@remyers you can start building the mechanism to trigger a pending async payment on top of that branch.

Add `PeerReadyNotifier` actor

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala

We use router data to resolve both private and public channels, even when scid-alias is used.
When a channel cannot be found, we simply skip it since adding it to the ignore list wouldn't have any impact.
@rorp @DerEwige can you verify that this is what you expect?
Supersedes #2483
Fixes #2346 and #2426

Improve `findRoute` ignored channels behavior

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxPublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxTimeLocksMonitor.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Sync.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala

Reduce the amount of logs generated by default by moving logs that are redundant or only used for targeted debugging to `debug` level or removing them entirely.
I focused on logs that generate some volume and that I never personnally use for day-to-day log browsing, but let me know if some of these logs are important for you and it would be annoying to have to turn on `debug` level for their respective component.

Remove redundant log messages

---

eclair-core/src/main/scala/fr/acinq/eclair/DBChecker.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala

This is just refactoring, there is no feature change. The goal is to later be able to add an upper layer that manages several commitments and acts as a "meta commitments".

Move `Commitments` methods from companion to class

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala

We remove utxos locks that were previously set, otherwise we may have utxos that stay locked indefinitely. This may happen if we started funding a channel and restarted before completing the funding flow: the channel will be safely forgotten but the corresponding utxos stay locked.
The only drawback that this may have is if we have funded and signed a funding transaction but didn't publish it and we accidentally double-spend it after a restart. This shouldn't be an issue because:
- locks are automatically removed when the transaction is published anyway
- funding transactions are republished at startup if they aren't in the blockchain or in the mempool
- funding transactions detect when they are double-spent and abort the channel creation
- the only case where double-spending a funding …

Unlock utxos at startup

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

⚠️  While the change is minor, this is a very sensitive part of the code. Commits should be reviewed separately.
We first factor all handlers for all states in commit 0905619f8eba4ae787c8d59dac01551ce84e4383. Critically, note that tests are left unchanged.
The second commit changes tests, but it is about a corner case.

Factor funding spent handlers

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/zeroconf/ZeroConfActivationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/RustyTestsSpec.scala

When using zero-conf, we wait for the transaction to be published before using a channel. This guarantees that the bitcoind wallet has successfully recorded the transaction and won't double-spend it.
Otherwise if the transaction fails to publish and the utxos are unlocked, or if bitcoind is restarted, we may accidentally double-spend it which would break the channel and be very painful to recover.

Wait for tx to be published for zero-conf

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/DualFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/SingleFundingHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala

The handling is mostly the same in connected/disconnected states. This does some refactoring to make them as similar as possible.
NB: we don't make a difference between previous/latest commitment being confirmed.

Factor funding tx acceptance

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/OnChainWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunder.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/DummyOnChainWallet.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

We must *always* lock inputs selected for funding, otherwise locking wouldn't work at all, as the following scenario highlights:
- we fund a transaction for which we don't lock utxos
- we fund another unrelated transaction for which we lock utxos
- the second transaction ends up using the same utxos as the first one
- but the first transaction confirms, invalidating the second one
This would break the assumptions of the second transaction: its inputs are locked,  so it doesn't expect to potentially be double-spent.

Always lock utxos when funding transactions

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/InteractiveTxBuilder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

When our peer doesn't contribute to an `interactive-tx` session, we don't need to wait for their `tx_signatures`: they will be empty anyway, so we can create them locally and publish the transaction immediately.
Since Phoenix sends an encrypted channel backup in `tx_signatures`, we may need to explicitly update the stored backup when we receive what appears to be a redundant `tx_signatures`.

Skip waiting for empty `tx_signatures`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala

In preparation for splices, we make `makeFirstCommitTxs` more generic:
- expose the `commitmentIndex`, which was hardcoded to `0`
- take the funding/push amounts arithmetic out
We rename the existing method to `makeCommitTxsWithoutHtlcs` and define a new `makeFirstCommitTxs` with the exact same signature as before, making the change transparent from the outside.

Make creation of first commit tx more generic

---

docs/release-notes/eclair-vnext.md
eclair-core/eclair-cli
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/PathFinding.scala

Add a new API to return information about a specific node: its announcement, number of active channels and total capacity. This has been requested several times by node operators.

Add `GetNode` router API

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/DualFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/SingleFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/WebSocket.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

Emit an event when a channel is opened and ready to process payments. This event is distinct from the `ChannelCreated` event which is sent earlier, once we think a funding transaction has been successfully created (but cannot guarantee when we're not the initiator).
I've regularly worked around the lack of such an event, and I think it's useful to have, especially for plugins that would like to know when a new channel is really available without having to watch all state transitions.

Add `ChannelOpened` event

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

While working on #2552 I realized that the new  `Router.GetNode` message should have a `replyTo` field to allow for interaction and testing with typed actor adapters. I wish I had caught this in my initial `GetNode` review.
If `ActorRef.noSender` is passed in the `replyTo` field, `GetNode` will reply to `sender()` as before. This is also how  `CMD_GET_CHANNEL_DATA` and other classic actor messages work.
Update: fixed to replace the `ActorRef.noSender` hack with a properly typed `replyTo`

Add `replyTo` field to Router.GetNode

---

eclair-front/src/main/resources/eclair-front.sh
eclair-node/src/main/resources/eclair-node.sh

To avoid bash interpreting '&' as background job metacharacter, properly quote the string containing it.
Otherwise you get output like the following:
eclair-node[3517981]: No java installations was detected.
eclair-node[3518011]: Please go to https://adoptopenjdk.net/?variant=openjdk11
eclair-node[3518012]: /usr/bin/eclair-node: line 285: and: command not found

Properly quote in bash scripts

---

eclair-core/src/main/scala/fr/acinq/eclair/DBChecker.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala

Fixes #2478.
I tried to keep the changes minimal, but had to move the _read_ from `Setup` to `Setup.bootstrap`, otherwise we would have kept a reference of the initial channels list forever.
Checking the db now happens a bit further in the startup procedure, but it is still blocking, and before the actors are initiated.

Read channels db only once at restart

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala

Even when there is a path that is a lot cheaper, we still want to use the local channel.

Absolute priority to local channels

---

eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/Postman.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/OnionMessagesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala

In case we are the introduction node of a message blinded route, we would not be able to send a message to that route. We now unwrap the first hop in case the route starts with us.

Allow sending message to route that starts with us

---

CONTRIBUTING.md

It isn't obvious when a contributor should rebase a PR. Hopefully the additional paragraph clarifies the rules around rebasing.

Clarify contribution guidelines around rebasing PRs

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/DualFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version3/ChannelCodecs3.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala

It makes sense to store the params with each `rbf` attempt (as opposed to the last one currently), and allows us to remove `DATA_WAIT_FOR_DUAL_FUNDING_CONFIRMED.fundingParams`.
Note that I used error codecs to (not) deal with migration, I think it's appropriate in this particular case.

Store `fundingParams` with the `sharedTx`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxFunder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptDualFundedChannelStateSpec.scala

We previously inflated the funding amount to always exceed the dust limit, otherwise bitcoind would reject the funding attempt. It complicated the code for a scenario that doesn't make sense in practice, so it's better to just let the funding attempt fail in that case.
We also randomize the order of inputs and outputs, which is a common privacy best practice.

Remove unnecessary dust limit hack in interactive-tx

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptDualFundedChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenDualFundedChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingInternalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

That additional event lets subcribers know when a channel was closed without ever being used.
The possible flows for a channel lifecycle are now:
- ChannelCreated -> ChannelOpened -> ChannelAborted (when we don't have funds in the channel)
- ChannelCreated -> ChannelOpened -> ChannelClosed (when we have funds in the channel)
- ChannelCreated -> ChannelAborted (when we don't have funds in the channel)
- ChannelCreated -> ChannelClosed (when we have funds in the channel)
- ChannelAborted (when we don't have funds in the channel)
- ChannelAborted -> ChannelClosed (when we have funds in the channel)

Add `ChannelAborted` event

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala

After calling this method, we perform actions at several places that only make sense if the correct behavior happened. Instead of assuming things went ok, we use proper typing and make the result explicit.
This is a follow-up to #2598.

Make `updateLocalFundingStatus` method return `Either`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/DualFundingHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala

If we didn't plan on using zero-conf, but our peer sends us an early `channel_ready`, we can opportunistically switch to zero-conf. But we can only do that if we're sure that our peer cannot double-spend the funding transaction. We previously checked their contribution to the funding output, but that's not enough: they may add inputs to the funding transaction even if they don't contribute to the funding output.
We were also setting duplicate `WatchPublished` in case we were already using zero-conf, which is now fixed.
The second commit fixes an issue where we think we're doing opportunistic zero-conf, but the transaction is actually confirmed. Please have a look at the commit message for more details. I don't know if we should move that change to `updateLocalFundingStatus` (instead of …

Fix opportunistic zero-conf

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/IncomingConnectionsTracker.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/IncomingConnectionsTrackerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

Limit the number of incoming connections from nodes we don't have channels with.
- when an incoming connection comes in, the `switchboard` checks if we have channels with that peer
- if we have channels with an incoming peer, do not  track it
- if an incoming peer is on the `sync-whitelist`, do not track it
- otherwise, track the connection 
- when we reach our configured limit of tracked peers without channels, disconnect the oldest tracked peer
- when a tracked peer disconnects or creates a channel, we will stop tracking that peer
We do not track peers we initiate outgoing channel connections to

Add limit for incoming connections from peers without channels

---

eclair-core/src/main/scala/fr/acinq/eclair/router/BlindedRouteCreation.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BlindedRouteCreationSpec.scala

The lengths of the encrypted recipient data leak the base fees as they are encoded with a variable length, to compensate for that we always add padding.

Add padding to blinded payment routes

---

eclair-core/src/main/scala/fr/acinq/eclair/io/OpenChannelInterceptor.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/OpenChannelInterceptorSpec.scala

This PR makes it easier for open channels plugins to make decisions based on peers' IP addresses.

Pass remote address to InterceptOpenChannelPlugin

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/ChannelTlv.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

This is the official tlv type used in the [dual funding specification](https://github.com/lightning/bolts/pull/851), and was added in https://github.com/lightning/bolts/pull/851/commits/da9a87ee2a6e5a9f7900ac02519f7a53a6d5e146

Use tlv type 0 for `next_funding_txid`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala

So it can be called from `InteractiveTx` for new commitments.

Define `channelReserve()` methods in `ChannelParams`

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala

We're creating an index on the `remote_node_id` based on the channel's JSON serialization, which isn't very robust. The data model changes for splicing have changed the JSON format and thus broken that index.
I'm not sure how to test this and prevent future regressions...it would probably be best to add a dedicated `remote_node_id` column if we want to preserve that index instead of relying on JSON.
Thanks @rorp for reporting this bug.

Fix JSON Postgres index on channel's `remote_node_id`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

It seems like lnd sends this error whenever something wrong happens on their side, regardless of whether the channel actually needs to be closed. We ignore it to avoid paying the cost of a channel force-close, it's up to them to broadcast their commitment if they wish.
See https://github.com/lightningnetwork/lnd/issues/7657 for example.

Ignore lnd's internal errors

---

pom.xml

`bitcoin-lib` 0.28 uses the same `secp256k1-kmp` and `bitcoin-kmp` libraries as `lightning-kmp` after https://github.com/ACINQ/lightning-kmp/pull/427

Use bitcoin-lib 0.28

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/MessageRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala

According to the spec, option_onion_messages signals that the node can forward onion messages which is different from being able to send or receive them (there is no feature bit for that). We now allow nodes with this feature disabled to still receive messages and remove the NoRelay relay policy as it is redundant.

Fix interpretation of option_onion_messages

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala

When performing a mutual close, we initially rejected fees that were higher to the commit tx fees. This was removed from the specification for anchor output channels, and doesn't make a lot of sense for standard channels either: even at a higher fee, it makes sense to do a mutual close to avoid waiting for relative delays on our outputs.
Fixes https://github.com/ACINQ/eclair/issues/2646

Accept closing fee above commit fee

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

If we force-close with HTLCs that have just been signed by our peer but for which we haven't received their revocation, we should ignore them. We have not relayed those HTLCs so they can't be fulfilled. It is our peer's responsibility to claim them on-chain (using their HTLC-timeout), but if for some reason they don't claim it, we don't want the channel to be stuck in the closing state.
This is a subtle and dangerous change, please review carefully!
Note that we don't fix existing channels that are already in that state (they will have an entry `Outpoint -> None` in `localCommitPublished.htlcTxs`). It is a bit dangerous to fix them automatically, I'd rather either wait for the peer to claim the HTLC on-chain or let impacted node operators (only @DerEwige as far as I know) manually fix it …

Ignore non-relayed incoming HTLCs when closing

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

And add tests for splice disconnection/reconnection scenarios.

Fix splice reconnection while signing

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelsDbSpec.scala

Previous implementation had the advantage of being all in one place, but it left holes:
- `last_connected_timestamp` was only set after the first disconnection
- in some corner cases the `closed_timestamp` was never set (nothing at stake, funding tx timeout, post-restart)

More robust channels timestamps

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala

When we want to add new types of inputs/outputs that contain specific tlvs, we will need to store them alongside standard inputs/outputs.
We will use traits and case classes inside `InteractiveTxBuilder`, and need to thus add a discriminator when encoding them.
Note that this is a backwards-incompatible breaking change for dual-funded channels or splices that are still unconfirmed. We should make sure that we don't any such channels before deploying that change.
An open question is whether we should also version the shared input and output?

Make shared transaction codecs more future-proof

---

eclair-core/src/main/scala/fr/acinq/eclair/io/ClientSpawner.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala

In cluster mode, outgoing connections are initiated by frontend nodes. If there are no frontend node available, we fail the connection attempt with a dedicated error.
The `initial-random-reconnect-delay` should be configured to allow enough time for the front nodes to bootstrap at reconnection.

Ignore outgoing connection requests if front not ready

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala

The spec says that we must return an error if:
- cltv_expiry < outgoing_cltv_value
- cltv_expiry < current_block_height + min_final_cltv_expiry_delta
For the second check, we actually tested if:
- cltv_expiry < max(outgoing_cltv_value, current_block_height) + min_final_cltv_expiry_delta
But that check should only verify that our `min_final_expiry_delta` requirement is fulfilled, which is unrelated to the `outgoing_cltv_value`.
It was redundant with the first check, which already guarantees that intermediate nodes inside the blinded path cannot cheat by using a higher `cltv_expiry_delta` than what the recipient intended.
For context, see https://github.com/lightning/bolts/pull/1066 and https://gist.github.com/t-bast/b1371d357a2c5f3e8c09514a62db7079

Fix blinded path `min_final_expiry_delta` check

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerChannelsCollector.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerReadyNotifier.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/TwoNodesIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerChannelsCollectorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerReadyNotifierSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/AsyncPaymentTriggererSpec.scala

The `Peer` actor can now directly be queried for the list of its channels. This makes this feature more reusable than the previous actor that was customized for the peer-ready scenario.

Move channel collector inside Peer actor

---

eclair-core/src/main/scala/fr/acinq/eclair/io/PendingChannelsRateLimiter.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PendingChannelsRateLimiterSpec.scala

This fixes the failing test "receive events during the restore" by directly calling `ReplaceChannelId` and `RemoveChannelId` commands that should be stashed during `restoring` and are normally processed through the event stream. We also now stash the `CountOpenChannelRequests` command during `restoring` so we can count the channels just after restore, and compare those counts to after the stashed replace/remove commands have been applied after the restore.
Are there any other places where I should simplify or clarify these tests?
See #2687 for context of the fixed test and other recent tests added.

Fix failing test for `PendingChannelsRateLimiter` 

---

Dockerfile
contrib/arm64v8.Dockerfile

We were previously relying on mvn 3.6.3 which has reached EOL. Building with mvn 3.9.2 creates some warnings that some of our existing build plugins won't be compatible with mvn 4.x, but we can ignore that.
I ran two eclair nodes built with mvn 3.9.2 on regtest, opened channels and made payments, and everything is looking good.

Update maven version

---

Dockerfile
contrib/arm64v8.Dockerfile

We're verifying the checksum of the gradle archive we fetch before building the docker image with it. I forgot to update that checksum in #2690

Update docker gradle checksum

---

eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala

It turns out that #2688 broke the JSON serialization of the `channels` API by introducing a new `ActorRef`. We never want to surface `ActorRef` in JSON responses, so we're defining serializers to filter them out.

Never serialize `ActorRef`

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/Postman.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/OfferPayment.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/BalanceEstimate.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/StaleChannels.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/send/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BalanceEstimateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRouterIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Message.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Payment.scala

When sending a message, the postman can now ask the router to find a route using channels only. The same route is also used as a reply path when applicable.

Find route for messages

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala

When restarting, we weren't checking whether it was using blinded paths. If we were an intermediate node in the blinded path, we were incorrectly returning a normal failure: it should be ok, since the introduction node is supposed to translate those failures, but it's safer to assume that they don't.

Correctly fail blinded payments after restart

---

Dockerfile
contrib/arm64v8.Dockerfile

The previous repository we used removed the binaries for mvn 3.9.2, which broke our docker build. It looks like `archive.apache.org` keeps artifacts longer and hopefully won't break our docker build again soon.

Use apache archives for mvn in docker build

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

After exchanging `tx_complete`, we validate the splice transaction before sending our `commit_sig`. If we consider the transaction invalid, we send `tx_abort`. But if our peer thinks the transaction is valid, they will send their `commit_sig`, which we must ignore until they've acked our `tx_abort`.

Ignore `commit_sig` for aborted splice

---

README.md
eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/test/resources/integration/bitcoin.conf
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

This lets us use the new `gettxspendingprevout` instead of fetching the whole mempool when looking for txs spending one of our channels.
I had to change many of the test values in `InteractiveTxBuilderSpec` because `bitcoind` updated the way it generates the change output in https://github.com/bitcoin/bitcoin/pull/24494 which had mostly an impact on outputs around the 50k sat threshold. Bitcoin Core tries to create a change output with an amount similar to the main output for privacy reason (and has done so for a few versions already). While this makes sense for most users, it creates more liquidity churn for LSPs: ideally that's something we'd like to turn off (we probably don't want to pay for privacy). We may want to start using our own fork of `bitcoind` with small `coinselection` …

Update to bitcoind 24.1

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/package.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/PackageSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
pom.xml

This makes eclair compatible with https://github.com/ACINQ/lightning-kmp/releases/tag/v1.5.1 and https://github.com/ACINQ/lightning-kmp/releases/tag/v1.5.2

Use bitcoin-kmp 0.13.0

---

eclair-front/pom.xml
eclair-front/src/main/resources/eclair-front.sh
eclair-node/src/main/resources/eclair-node.sh

It will fix the error we get when we start with `-with-kanela`

Update kanela-agent version in starter scripts to match the version set in pom.xml

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonHandlers.scala

This is a follow up to #2565, more precisely to the _caveat_ here: https://github.com/ACINQ/eclair/pull/2565#issuecomment-1397052582.
We now create a fresh shutdown script even if one was already generated at channel creation, if the channel doesn't have the mandatory `option_upfront_shutdown_script` negotiated.
The (reasonable) assumption is that other implementations will ignore our pre-generated script if they didn't support the `option_upfront_shutdown_script` feature.
This "on-the-fly" approach is simpler and safer than a db migration.
Postgres request to keep track of channels that will have to stick to their pre-generated script:
```sql
SELECT COUNT(*)
FROM local.channels
WHERE NOT is_closed AND json->'commitments'->'params'->'channelFeatures' ? 'option_upfront_shutdown_script'
```

Ignore pre-generated shutdown script when possible

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/testutils/PimpTestProbe.scala

We start watching funding outputs once the corresponding funding transaction has been confirmed with 3 confirmations. We may have already spent that transaction with a child splice transaction by that time: providing hints with the corresponding txids to the `ZmqWatcher` improves the performance when that happens.

Set child splices as hints in watch-funding-spent

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

When reconnecting in the middle of signing a splice, we must ensure that `splice_locked` is sent *after* `tx_signatures`. Otherwise when using 0-conf we may retransmit `splice_locked` before `tx_signatures`, which our peer will ignore because they don't have a corresponding fully signed commitment.
This may eventually lead to a mismatch where one side thinks that the splice has been locked and the other doesn't, so one side will send more signatures which results in a force-close.
It should never happen though, because we only send `splice_locked` once the transaction has been published (zero-conf) or confirmed. Once that happened, we will never retransmit `tx_signatures` (because we run into [that condition](https://github.com/ACINQ/eclair/blob/404e3d5ea6e004c1874ddf4cc0eb2ba04f7369aa/ecl …

Don't send `splice_locked` before `tx_signatures`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunder.scala

We were previously signing twice (with makes a call to `bitcoind`), just to get the final weights and adjust the change outputs. This was unnecessary, as we can adjust the weights before adding inputs.
We were also duplicating the checks where we verify that `bitcoind` is malicious. We only need to check that once, during the final signing step.
This PR targets #2613, but we can also integrate it *after* #2613 if you prefer.

Simplify replaceable tx funding

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/StartupIntegrationSpec.scala

We make the distinction between _not_ defining a bitcoin wallet name, and using an bitcoin wallet with an _empty_ name.
This remains mostly backward compatible, as:
- by default `eclair.bitcoind.wallet` is undefined so we keep using the default loaded wallet as before
- if user already set `eclair.bitcoind.wallet`, then eclair will use that wallet.
- only in the case where the user left `eclair.bitcoind.wallet` undefined, and if bitcoin had only one wallet with a non-empty name, then eclair will fail right at startup with an explicit error

Allow specifying a bitcoin wallet with an empty name

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala

Some tests related to bitcoind's funding behavior have been randomly failing since we updated to bitcoind 24.1. They now have more sensibility over the exact set of available utxos, so we needed to fine-tune them accordingly.
I also imported some tests that were added to feature branches but never backported to `master`.

Fix flaky channel funding tests

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

If we disconnect before receiving our peer's `tx_signatures`, we expect them to re-send it on reconnection (by filling the `next_funding_txid` field in `channel_reestablish`). In that case, our peer may also retransmit their corresponding `commit_sig` first (if they cannot be sure that we've received it). If we've already received that `commit_sig`, we should ignore it. But we must make sure we don't end up ignoring *other* `commit_sig` messages!
Eclair wasn't spec-compliant and wouldn't retransmit their `tx_signatures` if the transaction was already confirmed. We now store our `tx_signatures` even after confirmation or publication (if using 0-conf) to make sure we can retransmit them when requested.

Fix `tx_signatures` retransmission

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/OnChainFeeConf.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPrePublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/TxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/TxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

This is a follow-up for #2743
When manually bumping the fees of a force-close (to help wallet users recover their funds more quickly), we also want to handle the case where they were the one publishing the commit tx and bump their remote commit. It can also be helpful for node operators who set `eclair.on-chain-fees.spend-anchor-without-htlcs = false` and want to recover their liquidity on a case-by-case basis.
We also fix two issues in #2743:
- we weren't persisting the manual fee-bump to the DB: if the node was restarted, we wouldn't keep on bumping the fees
- we didn't have an ordering on `ConfirmationPriority`, which means `fast` wasn't replacing a previous `medium` or `slow`

Use `bumpforceclose` RPC to also bump remote commit fees

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeProvider.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

A minor fix needed after updating the test `"disconnect (tx_signatures received by alice, zero-conf)"` in #2720. It should not trigger a fee rate update after reconnecting when using anchors outputs, but does if the minimum feerate is the same as the other feerates.

Fix tests that expect network minimum feerate to be less than other rates

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/StartupIntegrationSpec.scala

https://github.com/lightning/bolts/pull/1092 makes some features compulsory and lets us assume that other nodes have support for them.

Assume widely supported features

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/OnChainFeeConf.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelFeatures.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/OnChainFeeConfSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala

The `ChannelFeatures`->`ChannelType` conversion is problematic for the following reasons:
- It creates an implicit bidirectional mapping between the two classes, which is illogical and error-prone because both directions must be kept in sync.
- Not only must the conversions be kept in sync, it must also be stable over time.
- From the spec p.o.v., the scope of `ChannelType` is really limited to channel opening negotiation, while we currently make it a permanent concept.
- It has weird semantic side effects where we would check channel types in places where we really meant to check commitment formats.

Remove `ChannelFeatures`->`ChannelType` conversion

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/StartupIntegrationSpec.scala

When we start, bitcoind may not be ready to handle requests if we restarted it around the same time. We thus poll it for 30 seconds before giving up. This is especially useful for tests (e.g. on regtest).
@tee8z this should fix the start-up issue you're seeing for https://github.com/tee8z/doppler

Poll bitcoind at startup instead of trying only once

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

We assumed that once quiescent, the local and remote commitment index would be the same, but that's not true. Those two indices may diverge because of concurrent updates. We need to keep using the right index for each commitment during and after a splice, otherwise it leads to "invalid commit sig" errors.

Handle splice with local/remote index mismatch

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala

This is best effort but should already be pretty useful.
Please double check the attribution logic, as it's not trivial. 🙏

Add metrics on splicing

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxFunder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

Equivalent to https://github.com/ACINQ/lightning-kmp/pull/542.

Strip witness of interactive tx parents

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala

We added an override and an optional paramter to be used in feature branches, but it was actually unnecessary.

Simplify dual-funded min-depth calculation

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala

We were considering all local outputs as splice outputs, but some may be change.

Fixup! Add metrics on splicing (#2756)

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

This correctly reduces the pending changes and takes HTLC fees into account. This change highlights that we cannot simply compare to the previous commitment, because it will also have taken pending changes into account, so we instead compare to the current `channel_update`, which is actually what we want.
This is a PR for the #2703 PR.

Use `commitments.availableBalanceForSend`

---

eclair-core/src/main/scala/fr/acinq/eclair/io/PeerReadyNotifier.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/AsyncPaymentTriggererSpec.scala

Sometimes the `PeerReadyNotifier` for node A has not been killed before node A connects. This causes an extra `GetPeerInfo` message to be sent to the switchboard and the `assert(request3.remoteNodeId == remoteNodeId2)` check to fail when the `GetPeerInfo` for node A comes before the one for node B. Just waiting to receive the `AsyncPaymentTimeout` message does not guarantee the notifier has been stopped.
If node A connects after node B then this race does not occur.
In the logs the error looked like this:
```
watch two nodes, one connects and the other times out *** FAILED ***
02aaaa00ce2f18a967dc4f25f414e671ba6585f8ef0b8c5fb812c21064f55a2eaa did not equal 02bbbb671d15145722fb8c28d732cddb249bcc6652ed2b297ff1f77a18371b1e63 (AsyncPaymentTriggererSpec.scala:185)
Analysis: …
```

Fix a flaky async payment triggerer test

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala

Whenever we use the local commit, we must use the local dust limit to trim HTLCs. Similarly, whenever we use the remote commit, we must use the remote dust limit.

Use local dust limit in local commit fee computation

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala

If our peer sends us some `tx_signatures` that we already received, we can safely ignore them. This happened with `cln`, which sometimes sends duplicate `tx_signatures`: this something they should fix, but we can also be more robust by ignoring them.

Ignore duplicate dual-funding signatures

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

We were incorrectly splitting the shared input amount based on each peer's balance, but for the signing order the peer that adds the shared input takes credit for the whole amount of that input.

Fix `tx_signatures` ordering for splices

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala

If we abort the interactive-tx protocol while we're waiting for bitcoind to fund the transaction, we must avoid sending an obsolete `tx_add_input` for the funded transaction. There is a [check](https://github.com/ACINQ/eclair/blob/63a3c4297f6575a3f19425fe78eaefedb52220d3/eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala#L1056) in `Channel.scala` to only send an outgoing interactive-tx message if we have an active interactive-tx session, but this isn't sufficient in the following scenario:
- we disconnect and thus abort the interactive-tx session while bitcoind is funding
- we reconnect and restart another interactive-tx session
- bitcoind responds for the first interactive-tx session
In that scenario we would mix `tx_add_input` from the old and the new interactive-tx …

Abort interactive-tx during funding

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

Splicing (and dual funding as well) introduce a new scenario that could not happen before, where the channel initiator (who pays the fees for the commit tx) can end up below the channel reserve, or right above it but any additional HTLC would make it go below the reserve.
In that case it means that most of the channels funds are on the non initiator side, so we should allow HTLCs from the non-initiator to the initiator to move funds towards the initiator (towards a more balanced channel where both sides meet the channel reserve requirements). We allow slightly dipping into the channel reserve in that case, for at most 5 pending HTLCs (to limit our exposure).
We limit this to only a few HTLCs to make sure that the initiator still has funds in the channel, that are close enough to their …

Avoid unusable channels after a large splice

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala

If remote has a positive contribution, we do not check their post-splice reserve level, because they are improving their situation, even if they stay below the requirement. Note that if local splices-in some funds in the same operation, remote post-splice reserve may actually be worse than before, but that's not their fault.

Remove reserve check if splice contribution is positive

---

eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala

`ByteVector.toString()` was meant to be `toHex()`, and there is a size limit on Windows.

Fix wallet name in `BitcoinCoreClientSpec`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

As soon as a channel is transitioning to a closing state (mutual or unilateral close), it cannot be used to relay HTLCs anymore. We should notify the network by sending a disabled `channel_update`.
Fixes #2766

Disable channel when closing

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala

When we receive a `channel_update` in `update_fail_htlc`, we should take it into account to exclude channels or correctly retry with updated fees, but we shouldn't apply it to our routing table.
If we did, that could be exploited to deanonymize our payments. It shouldn't be necessary anyway, as honest nodes should broadcast those `channel_update`s publicly, so we would receive them through the normal gossip mechanism.
Fixes #2767

Don't rebroadcast channel updates from `update_fail_htlc`

---

eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala

This makes it much easier to diagnose incompatibilities.

Add hints when features check fail

---

eclair-core/pom.xml
eclair-front/pom.xml
eclair-node/pom.xml

This version of logback fixes the following CVE:
"a potential denial of service attack on a centralized logback receiver when a third party controlling a remote appender connects to said receiver and could shut down or slow down logging of events."
Eclair isn't affected since we don't use logback receivers, but if there are applications or plugins that depend on eclair and use logback receivers, it's better to use the logback version containing the fix.

Update logback-classic to 1.2.13

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala

#2761 introduced the ability for the HTLC sender to let a remote initiator dip into its reserve to unblock channels after a large splice. However, we relaxed that condition for all channels, even those that don't use splice. This creates compatibility issues with other implementations that are stricter than what the specification requires, and will force-close in those situations.

Dip into remote initiator reserve only for splices

---

docs/CircularRebalancing.md

A few minor grammatical fixes.

Fix some typos in CircularRebalancing.md (#2803)

---

eclair-core/eclair-cli

Last command of eclair-cli is a curl piped to jq. In case of an error with the curl command (for instance, eclair service is not running) the error code is swallowed by the pipe which will return the exit code of the last command of the pipe (here, jq).
Setting `pipefail` ensures that the error code of curl is preserved in case of HTTP issue.
This can come handy, for instance, to check that eclair is not ok:
```
if eclair-cli getinfo
then
echo eclair is answering
else
echo problem communicating with eclair
fi
```

FIX eclair-cli error code in case of HTTP problem

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalQuiescentStateSpec.scala

This PR fixes some issues we found while [porting quiescence](https://github.com/ACINQ/lightning-kmp/pull/558) to lightning-kmp.
We might find more changes, so this should stay in draft until we also have splicing with htlcs ported.

Fixes for quiescence back ported from lightning-kmp

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

If we get disconnected after sending `commit_sig`, we will retransmit that message when reconnecting if our peer has not received it.
When we have multiple commitments, we need to retransmit one message per commitment, and include the `batch_size` tlv.
We incorrectly stored `commit_sig` without the `batch_size` tlv in the next remote commit field, and thus retransmitted without that tlv.

Send `batch_size` on `commit_sig` retransmit

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Recipient.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/RelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/PaymentOnionSpec.scala

Allow trampoline to pay a list of blinded paths instead of a node id. Only the last trampoline hop can target blinded paths, trampoline nodes are still reached with their node id, not with blinded paths.
Followed by #2811

Trampoline to blinded (types only)

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/CompactBlindedPathsResolver.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/OfferPayment.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Recipient.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

Allow trampoline to pay a list of blinded paths instead of a node id. Only the last trampoline hop can target blinded paths, trampoline nodes are still reached with their node id, not with blinded paths.

Trampoline to blinded

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/OnChainWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/AuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgAuditDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/DummyOnChainWallet.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/AuditDbSpec.scala

When a transaction is directly double-spent, bitcoind is able to automatically detect it and free up wallet inputs that are used in double-spent transactions. However, when a transaction becomes invalid because one of its ancestors is double-spent, bitcoind is not able to detect it and will keep wallet inputs locked forever.
The only cases where this can happen are:
- splice transactions when a commitment transaction that is not based on the latest splice is confirmed
- anchor transactions in the above case, or when a different version of the commitment confirms (e.g. remote commit while we're trying to CPFP ou local commit)
When we detect that this happened, we abandon the corresponding transactions, which ensures that we don't end up with unusable liquidity in our wallet.
We also remove …

Abandon transactions whose ancestors have been double spent

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala

We had some cases where channels were staying stuck in the CLOSING state without going to the CLOSED state in previous versions of eclair where we published different versions of our 3rd-stage transactions after a restart and a feerate increase.
This happened in two cases:
- when we published a different version of our claim-main, since we only store the latest (it's an `Option`, not a `Seq`) and put a watch on this specific `txid` instead of watching the corresponding output
- when we re-published 3rd-stage txs after receiving `CMD_FULFILL_HTLC` because we replaced the previous `claim-htlc-delayed` transactions
This was on my backlog for a while, and I wanted to take another look at it after the splicing implementation. Fortunately, this was fixed as part of the splicing changes, but …

Add closing test reconnect with 3rd-stage txs

---

eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala

When transactions are being evicted from the mempool, we want to make sure that bitcoind keeps the corresponding wallet inputs locked to avoid accidentally double-spending ourselves. We update our unit tests to be closer to common scenarios (chain of unconfirmed splice txs, commit txs replaced by the remote version, anchor tx RBF and htlc txs conflicts).
These tests confirm that:
- if our wallet transaction is directly double-spent by another transactions (either a wallet transaction or an external one), bitcoind automatically frees up inputs when the competing transaction confirms
- if our wallet transaction is invalidated by one of its parents being double-spent, bitcoind keeps wallet inputs locked, and we have to call `abandontransaction` ourselves to free up utxos

Test bitcoind wallet behavior during mempool eviction

---

eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgChannelsDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala

Fixes a regression caused by https://github.com/ACINQ/eclair/pull/2705 reported by @fishcakeday.

fixup! Asynchronously clean up obsolete HTLC info from DB (#2705)

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ErrorHandlers.scala

In the case where we have not sent our `TxSignatures`, and our peer replies with an error at reconnection, we can safely unlock our local inputs.

Unlock utxos on reconnect when signatures haven't been sent

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/ChannelTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/InteractiveTxTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

This was missing from the spec, but is more flexible and clearer than inheriting values from the previous attempt. The dual funding specification added this in https://github.com/lightning/bolts/pull/851/commits/27ffef47aee985d37dcef85d528719f9a4608400
Fixes #2782

Add `require_confirmed_inputs` to RBF messages

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/DualFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala

When funding a transaction that contains inputs that are external to our bitcoin wallet, bitcoin core will add a lock to those external inputs, thinking that they may be wallet inputs that it doesn't know about yet. In our case, those are never wallet inputs, they are instead:
- the current channel output, when creating a splice transaction
- an output of the commitment transaction, when force-closing
We previously explicitly filtered those inputs before calling `unlock`, which was wrong. We now also unlock those utxos.

Unlock non-wallet inputs

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPrePublisher.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala

When we detect that the remote commit has been published, we spend our anchor output from that commit if the fees are too low and we have funds at risk. But if the remote commit is then evicted from our mempool, we cannot publish our anchor tx and must instead skip it, since we don't provide the fully signed remote commitment to the publisher.
We otherwise error when calling `fundrawtransaction`, where `bitcoind` fails because it cannot find the external non-wallet utxo. This change gets rid of those errors that can be quite confusing for node operators.

Skip anchor tx when remote commit has been evicted

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/OnChainFeeConf.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/OnChainFeeConfSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala

When there is a mismatch between the feerate of a channel and the feerate we get from our estimator, we may want to force-close because that could be exploited by our peer to steal HTLCs. But that's only the case if the feerate is too low, not if it's too high. We previously force-closed in both cases, whereas we only need to do it when the feerate is too low.
This should avoid some unnecessary force-close that we've observed and are due to buggy fee estimators (fee estimation is hard!), or to peers who simply do some smoothing and slightly delay lowering the feerate of our channels.

More fine grained support for fee diff errors

---

eclair-core/src/main/scala/fr/acinq/eclair/PluginParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/OpenChannelInterceptor.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/OpenChannelInterceptorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

We support dual funding, but we cannot decide for the node operator when to contribute to channels that are being opened to us. Node operators may want very different policies depending on their goals. Instead of trying to figure out a general set of policies, we let plugins decide when to contribute to channels and how much. Node operators are thus free to implement whatever logic makes sense for them in a plugin.

Allow plugins to set a dual funding contribution

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/DummyOnChainWallet.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/TwoNodesIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala

Activate dual funding by default

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/zeroconf/ZeroConfActivationSpec.scala

We started using dual-funding by default in some integration tests. One of the changes is that we consider the channel created once we send our commitment signatures. At that point, we are not yet in a state where we have fully signed commitments: that will happen once we receive our peer's signatures.
Some tests assumed that when receiving the `ChannelCreated` event, we would have fully signed commitment. We update those tests to handle the case where we are actually still exchanging signatures.

Fix flaky test

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala

We should use the quiescence timeout value instead of the revocation timeout value (copy-paste error) when initiating a splice.
Found this while doing integration testing with LND.

Fixup quiescence timeout when initiating splice

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala

If the peer had `option_shutdown_anysegwit` enabled when they initially sent their `remoteScriptPubkey`, but reconnected later with `option_shutdown_anysegwit` disabled, then `isValidFinalScriptPubkey` may not pass anymore.

Remove redundant check on `remoteScriptPubkey`

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala

https://github.com/lightning/bolts/pull/1092 initially made the `gossip_queries` feature mandatory and assumed: however it generally doesn't make sense for mobile wallets. It was thus relaxed in the last commits of this BOLTs PR, so we revert our change to `mandatory` to make this optional and avoid sending gossip queries to nodes who don't activate the feature.
The code we're reverting was introduced in #2732

Relax assumptions about `gossip_queries`

---

eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/OnionMessages.scala
eclair-core/src/main/scala/fr/acinq/eclair/message/Postman.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt12Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/OfferPayment.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PaymentsDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/MessageRelaySpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/OnionMessagesSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt12InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/offer/OfferManagerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/send/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/MessageOnionCodecsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/OfferTypesSpec.scala
eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala

To save space in the offer, we can skip the node id for offers that use blinded paths.
The node id used to sign the invoice will be the last blinded node id of the path used to request the invoice.

Implicit node id in offers with blinded paths

---

eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

TransactionsSpec reads test cases from the spec, however the spec was recently updated (https://github.com/lightning/bolts/commit/91f4bd2383cc2fc7a0a43b697e209f9eb9f5183c#diff-6bed824879b760d329ec379b16a1d0e78ffba034fdfa13b95cf0480e09fa7c4b) to remove half of the test cases.

Fix TransactionsSpec tests

---

eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/BlindedPathsResolver.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/OfferPayment.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Recipient.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/send/BlindedPathsResolverSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/send/OfferPaymentSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala

We use resolved paths in `BlindedHop`s, since we need to potentially unwrap the first hop in the route if we're the introduction node. This lets us refactor resolved paths to clearly distinguish the case where we are the introduction node, for which we need to include a blinding in our `update_add_htlc` message.
We also include a small hack in the second commit to improve support for MPP with blinded paths (see commit message).
This is a PR on top of #2858

Use resolved paths in `BlindedHop`

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala

We do log all incoming/outgoing messages, including `TxAddInput`, but the `toString()` prints the whole serialized tx, not the txid, making grepping more difficult.

(Minor) Log local inputs in interactive-tx

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerEvents.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/RegisterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/MessageIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

We add a `ForwardNodeId` command to the `Register` to forward messages to a `Peer` actor based on its `node_id`.

Register can forward messages to nodes

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala

Fix flaky test for punishing a published revoked commit
A race exists because node C can publish the txs to spend the htlcs from the revoked commitment *before* F publishes their txs to spend two of the htlc outputs. 
Instead we handle the rare case of a `txn-mempool-conflict` failure. 
We will sometimes miss testing that C claims those two htlcs via 3rd stage txs.

Fix flaky test for punishing a published revoked commit

---

README.md
docs/release-notes/eclair-vnext.md
eclair-core/pom.xml
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala

Bitcoin Core 27.1 adds the coingrinder coin selection algorithm which will help lower on-chain fees during feerate spikes.

Update Bitcoin Core to v27.1

---

eclair-core/src/main/scala/fr/acinq/eclair/blockchain/OnChainWallet.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/DummyOnChainWallet.scala

When we require inputs to be confirmed, we can reliably check whether they are unspent. We can't reliably check this for unconfirmed inputs, because they could be valid but simply not in our mempool, in which case bitcoind would incorrectly consider them unspendable.
We want to reject unspendable inputs early to immediately fail the funding attempt, instead of waiting to detect the double-spend later.

Reject unspendable inputs in `interactive-tx`

---

eclair-core/src/main/scala/fr/acinq/eclair/io/MessageRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala

Improve metrics for for onion messages.
We count messages sent and received, throttled and that couldn't be relayed.

Monitor onion messages

---

eclair-core/src/main/resources/reference.conf

We support those two features and they have been added to the BOLTs. We start advertising that we support them by default. Having `route_blinding` disabled by default means we won't relay blinded payments unless they're using trampoline, which is an issue.

Activate route blinding and quiescence features

---

eclair-front/pom.xml
eclair-node/pom.xml
pom.xml

Also add an exclusion on kamon-prometheus. The exclusion was previously only present in `eclair-node/pom.xml`.

Upgrade kamon to 2.7.3

---

eclair-core/src/main/scala/fr/acinq/eclair/Logs.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/MessageRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala

There weren't any logs when relaying onion messages, which makes it impossible to troubleshoot. While we're working on cross-compatibility, we keep those logs at the `INFO` level, and will change some of them to `DEBUG` once stabilized.

Add logs to onion message relay

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferTypes.scala
eclair-core/src/test/resources/offers-test.json
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/OfferTypesSpec.scala

- Add test vectors from https://github.com/lightning/bolts/pull/798
- Update the TLV ranges for offers and invoice requests

Offer test vectors

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala

Just because `nodeParams.peerWakeUpConfig.enabled` is false shouldn't cause us to drop the `walletNodeId`.

Don't drop `wallet_node_id` when wake-up is disabled

---

eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala

Independently of target and tolerance ratios, transactions must be publishable in our local mempool. We must be careful that fee ranges stay above this min fee level.
In theory we shouldn't need to care about the upper range, but I'm not sure that, depending on the fee estimator, the min fee is always lower than arbitrary block targets.

Take min feerate into account for recommended fees

---

eclair-core/src/main/scala/fr/acinq/eclair/remote/LightningMessageSerializer.scala

The codec that we were using to serialize `LightningMessage`s in the eclair cluster didn't support `UnknownMessage`. This resulted in those messages being dropped by the front and never reaching the backend node.

Make cluster serialization support unknown messages

---

eclair-core/src/main/scala/fr/acinq/eclair/router/BalanceEstimate.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BalanceEstimateSpec.scala

The balance estimates are sometimes outside the range [0, 1] which should never happen. We add some logs to help debug it. We also stop calling `TimestampSecond.now()` multiple times during the computation and reuse the same value which may fix the issue.

Add logs for balance estimate

---

eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PeerStorageCleaner.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PeersDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala

The three commits can be reviewed separately. This PR targets #2888

Peer storage follow-up and fixes

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/DualDatabases.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PeerStorageCleaner.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/PeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PeerStorageTlv.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/PeersDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

Implements https://github.com/lightning/bolts/pull/1110

Peer storage

---

commit.md
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/BalanceEstimate.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/channel/GossipIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/fixtures/MinimalNodeFixture.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BalanceEstimateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRouterIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

See issue #2437
When an external channel is spent, the router will add it to a new `spentChannels` map instead of immediately removing it from the graph. 
If after 12 blocks an entry in the `spentChannels` map is not part of a splice, it will be removed as before.
When a newly added channel is validated, if it spends the shared output of a recently spent channel then it is a splice.
A splice will update the `shortChannelId` and `capacity` of graph edges of the parent channel instead of removing the parent's edges and adding edges for a new channel. A splice will also reuse and adjust the parent edge's low/high balance bounds information based on the splice.

Delay considering a channel closed when seeing an on-chain spend

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/BlindedPathsResolver.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/PaymentOnion.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/RouteBlinding.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/PaymentOnionSpec.scala

`OutgoingNodeId` was assumed to be a wallet. While it probably shouldn't cause problems, it's better to keep both cases distinct.

`OutgoingNodeId` in a blinded path may not be a wallet

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/remote/EclairInternalsSerializer.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/zeroconf/ZeroConfAliasIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

Refactor the route finding to share the same code for payment routes and onion message routes.

Refactor route finding

---

eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferTypes.scala
eclair-core/src/test/resources/format-string-test.json
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/OfferTypesSpec.scala

Enforce formatting defined in https://github.com/lightning/bolts/blob/master/12-offer-encoding.md#encoding

Validate offers format

---

eclair-core/src/main/scala/fr/acinq/eclair/router/BalanceEstimate.scala

We already know th balance of local channels, we don't need to estimate it.

Do not estimate balance for local channels

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/channel/GossipIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala

A splice tx could involve more than one parent channel. The Router must track the set of channels spent by a given tx until matching channel announcements are received that splice the parent channels or the spend tx is deeply buried.
If a splice tx spends more than one parent channel between the same nodes, then there's no way to know which new channel announcement corresponds to which parent channel. We simply update the first one found.

Add router support for batched splices

---

eclair-core/pom.xml

Instead of SHA1+MD5.
This allows us to directly use the values in the official SHAS256SUMS file (provided that the signature is valid).

(Minor) Use SHA256 checksum to verify bitcoind download

---

.mvn/checksums/checksums-central.sha256
eclair-core/pom.xml
eclair-core/src/test/resources/logback-test.xml
eclair-front/pom.xml
eclair-node/pom.xml
eclair-node/src/main/resources/logback.xml

As logback 1.2.x is unmaintained: https://logback.qos.ch/news.html.
Akka is pulling an old version of slf4j which makes the build fail, we explicitly request slf4j-api 2.0.16, which should be a drop-in replacement: https://www.slf4j.org/faq.html#changesInVersion200
~~@sstone I think we should use SHA256 instead of SHA512, those long hashes are annoying and don't bring more security. And we are using SHA256 everywhere else.~~

Update logback to 1.5.16

---

eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeProvider.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

There is no functional change, the goal is to minimize future diffs if a new provider is implemented.

(Minor) Add a feerate method for funding/closing

---

eclair-core/src/main/scala/fr/acinq/eclair/balance/BalanceActor.scala
eclair-core/src/main/scala/fr/acinq/eclair/balance/CheckBalance.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/test/scala/fr/acinq/eclair/TestBitcoinCoreClient.scala
eclair-core/src/test/scala/fr/acinq/eclair/balance/CheckBalanceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala

This PR:
- uses _outpoints_ instead of _txids_ to track on-chain utxos, the later being insufficient when transactions have more than one output that belongs to us
- prints a detailed diff between two balance checks, by utxos and channels.

Compute detailed diff of balance

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala

This reverts #2411. `ChannelOrigin` is not used anymore in feature branches.

(Minor) Remove `ChannelOrigin`

---

eclair-core/src/test/scala/fr/acinq/eclair/testutils/MyCapturingAppender.scala
eclair-core/src/test/scala/fr/acinq/eclair/testutils/MyContextSelector.scala
eclair-core/src/test/scala/fr/acinq/eclair/testutils/MySlf4jLogger.scala

The lack of properly initialized `MDCContext` made `prepareForDeferredProcessing()` crash in `MyCapturingAppender`.

(Minor) Fix capturing logs in tests

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala

They are logically independent.

Make wallet resolution independent of wake-up config in `NodeRelay`

---

eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

There are no functional changes, this PR just adds low-level methods to create taproot lightning transactions.
The scripts used in this PR are slightly different from the ones included in the "simple taproot channels" proposal at ttps://github.com/lightning/bolts/pull/995/commits/e25132d8de0164224578964fcd3f7328ddfc3281, because they have been generated with miniscript (the "miniscript code" is included in the comment).  We expect the the taproot channels PR will also be modified to become "miniscript compatible".

Add scripts for taproot channels

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenDualFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/CommonFundingHandlers.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/ChannelTlv.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/LightningMessageTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForChannelReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LightningMessageCodecsSpec.scala

This TLV is relevant for splice funding txs only.
When the `my_current_funding_locked_txid` TLV attribute confirms the latest funding tx we prune previous funding transaction similarly to receiving `splice_locked` from our peer for that txid.
When we receive `your_last_funding_locked_txid` that does not match our latest confirmed funding tx, then we know our peer did not receive our last `splice_locked` and retransmit it.
For public channels, nodes also retransmit `splice_locked` after `channel_reestablish` if they have not received `announcement_signatures` for the latest confirmed funding tx. This is needed to prompt our peer to also retransmit their own `splice_locked` and `announcement_signatures`.
For public channels, nodes respond to `splice_locked` with their own `splice_locked` if …

Add support for using last_funding_locked tlv in channel_reestablish

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala

When generating a bolt12 invoice, we may need to find a payment path using only nodes that support route blinding. We also add a crude way to select an introduction node that is central in the network.

Add path finding for blinded routes

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/RestoreSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingReadyStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala

When the remote node supports the `your_last_funding_locked` tlv we do not need to always resend `channel_ready` when there are no channel updates. The tlv removes the ambiguity about whether our last `channel_ready` was received.

Use channel_reestablish tlv when sending channel_ready

---

README.md

these links seem to be no longer reachable

Remove ln explorer links from README.md

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala

We do not send splice `channel_reestablish` TLVs to peers that do not advertise splice support to avoid an issue with CLN using the splice TLVs for testing the (experimental) channel upgrade feature.

Gate new splice tlvs for channel_reestablish on remote support for splicing

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/ChannelStateTestsHelperMethods.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/OpenChannelInterceptorSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala

This is the first step before we make the change to always assume option_channel_type.
See https://github.com/lightning/bolts/pull/1232
Removed tests that depend on a node without the option_channel_type feature set.
Updated some tests that must explicitly set the init features to include option_channel_type.

Make option_channel_type mandatory

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForDualFundingConfirmedStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

`SingleKeyOnChainWallet` will sometimes use p2tr inputs when [`fundTransaction`](https://github.com/ACINQ/eclair/blob/24e397a9ce2f8761150f7895ed83faa54591c8b8/eclair-core/src/test/scala/fr/acinq/eclair/blockchain/DummyOnChainWallet.scala#L185) is called. This creates a slightly higher feerate that makes some tests fail.
```
// We randomly use either p2wpkh or p2tr.
val script = if (Random.nextBoolean()) p2trScript else p2wpkhScript
```
I ran the test suite with funding inputs always using  the `p2trScript` to see which tests fail and bumped the max feerate so both p2tr and p2wpkh pass.

Fix tests that fail due to a higher feerate because sometimes they get p2tr inputs

---

eclair-core/src/main/scala/fr/acinq/eclair/SpendFromChannelAddress.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/ChannelOpenSingleFunded.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fund/InteractiveTxBuilder.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunder.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/ChannelKeyManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/crypto/keymanager/LocalChannelKeyManager.scala
eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxFunderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/publish/ReplaceableTxPublisherSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TestVectorsSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala

This is needed to sign inputs that spend taproot outputs.

ChannelKeyManager: add optional list of spent outputs to sign() methods

---

README.md
docs/release-notes/eclair-vnext.md
eclair-core/src/main/resources/reference.conf
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala

This change enables custom signets by allowing the user to specify the txid of a transaction to check or "" to skip this check for signet. Fixes issue #3078.

Add an option to specify a custom signet tx to check

---

eclair-core/src/test/scala/fr/acinq/eclair/integration/basic/payment/OfferPaymentSpec.scala

Payment splitting is randomized which can lead to flaky tests. Tests requiring MPP used `maxAttempts = 3` which fails in a bit less than 1% of runs, increasing to `maxAttempts = 4` should reduce the failure rate to less than 1 per thousand.
We also increase the timeout for propagating channel updates.

Increase limits for flaky offer tests

---

eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalSplicesStateSpec.scala

During splice interop testing I added new channel_reestablish tests to splice_tests.md of the splice spec.
Some tests correspond to tests in splice_tests.md. I added the corresponding test name from splice_tests.md and test flow diagram to the matching spec tests.

Add more splice channel_reestablish tests

---

docs/release-notes/eclair-vnext.md
eclair-core/src/main/scala/fr/acinq/eclair/json/JsonSerializers.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/offer/OfferCreator.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/json/JsonSerializersSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt12InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/OfferTypesSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Offer.scala

The `payoffer` API requires an amount but the user has currently no way to read the amount from the offer. We add `parseoffer` so that the user can read the offer amount (among other things). Since the user needs to specify the amount they want to pay, we allow paying offers with a currency (other than BTC).

Parse offers and pay offers with currency

---

.mvn/checksums/checksums-central.sha256
eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
pom.xml

There are no functional changes. `bitcoin-lib` 0.41 and its dependencies (`bitcoin-kmp`, `secp256k1-kmp`) have all been published with the new Central Publisher APIs. 
There is one breaking change in the `bitcoin-kmp`'s `Musig2.generateNonce()` method, which was included in https://github.com/ACINQ/lightning-kmp/pull/791`, so eclair forks that also use `lightning-kmp` should both merge this commit and update `lightning-kmp`.

Upgrade to bitcoin-lib 0.41

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelData.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/OnTheFlyFunding.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
eclair-core/src/main/scala/fr/acinq/eclair/reputation/Reputation.scala
eclair-core/src/main/scala/fr/acinq/eclair/reputation/ReputationRecorder.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalQuiescentStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/db/LiquidityDbSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/ChannelRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/OnTheFlyFundingSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/RelayerSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/reputation/ReputationRecorderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/internal/channel/version1/ChannelCodecs1Spec.scala

Add an outgoing reputation in addition to the incoming reputation. It should protect against the "sink attack".

Add outgoing reputation

---

eclair-core/src/main/scala/fr/acinq/eclair/router/Sync.scala

In a network Alice -- Bob - Carol, we could have
- Alice creates a channel update, Bob and Carol do not know it yet.
- Carol syncs with Bob and sends a `GossipTimestampFilter` with the current timestamp
- Bob receives the channel update from Alice but does not propagate it to Carol because it is too old for the `GossipTimestampFilter`
To prevent this from happening, we add a buffer of one minute to allow gossip to propagate.
This is unlikely to happen in real life but was making some tests flaky.

Add `GossipTimestampFilter` buffer during gossip queries to fix flaky tests

---

eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinCoreClient.scala
eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeProvider.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/DustExposure.scala
eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreClientSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FeeProviderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/DustExposureSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/InteractiveTxBuilderSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/internal/channel/version4/ChannelCodecs4Spec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/LiquidityAdsSpec.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Channel.scala
eclair-node/src/main/scala/fr/acinq/eclair/api/handlers/Control.scala

It saves tedious double parentheses, especially in tests: `FeeratePerKw(FeeratePerByte(1 sat))` -> `FeeratePerByte(1 sat).perKw`.
Just a scratch that was hitching for a long time.

(Minor) Use helpers for feerates conversions

---

eclair-core/src/main/scala/fr/acinq/eclair/channel/fsm/Channel.scala
eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForDualFundingSignedStateSpec.scala

They were previously ignored because we don't yet have a commitment.

Catch close commands in `Offline(WaitForDualFundingSigned)`

---

eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
eclair-core/src/test/scala/fr/acinq/eclair/message/PostmanSpec.scala

The previous timeout of 100ms was creating a lot of tests failures.

Increase timeout for flaky onion message tests

---

eclair-core/src/main/scala/fr/acinq/eclair/payment/Bolt12Invoice.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/CommonCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferCodecs.scala
eclair-core/src/main/scala/fr/acinq/eclair/wire/protocol/OfferTypes.scala
eclair-core/src/test/scala/fr/acinq/eclair/payment/Bolt12InvoiceSpec.scala
eclair-core/src/test/scala/fr/acinq/eclair/wire/protocol/OfferTypesSpec.scala

Offers or invoices where the fields `offer_chains`, `offer_paths`, `invoice_paths`, `invoice_blindedpay` are present but empty are considered invalid. While the spec does not necessarily rejects them explicitly, they can't be paid.

Reject offers with some fields present but empty
