- eclair-node/src/main/resources/gui/main/main.fxml
- eclair-node/src/main/resources/gui/modals/openChannel.fxml
- eclair-node/src/main/resources/gui/modals/receivePayment.fxml
- eclair-node/src/main/resources/gui/modals/sendPayment.fxml
* Modals width/height must be set in FXML to prevent initial display issues in ubuntu
> (gui) fix issue with initial size of modals in ubuntu

- eclair-node/src/main/resources/application.conf
- eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala
- eclair-node/src/main/scala/fr/acinq/eclair/blockchain/peer/PeerClient.scala
Bug in #43 was caused by PeerClient not recognizing `testnet` conf parameter and failing to initialize, thus entering in an infinite loop caused by the supervisor's restart strategy.
> Use chain getblockchaininfo.chain to infer the magic value

- eclair-node/src/main/resources/application.conf
- eclair-node/src/main/scala/fr/acinq/eclair/Globals.scala
- eclair-node/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-node/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-node/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-node/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-node/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-node/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-node/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-node/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-node/src/test/scala/fr/acinq/eclair/db/ChannelStateSpec.scala
there can be a significant gap between the fee rate estimated by different bitcoin
clients (see estimatesmartfee) so we must set a reasonably high value for the threshold
above which we consider htat local and remote fee rates are too different and close the
channel.
> make max-feerate-mismatch configurable and set default value to 500%

- eclair-node/src/main/resources/application.conf
- eclair-node/src/main/resources/gui/main/channelPane.fxml
- eclair-node/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-node/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
- eclair-node/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-node/src/test/scala/fr/acinq/eclair/TestConstants.scala
We attempt to reconnect every minute to peers for which we have a channel in OFFLINE state (optional, enabled by default).
The "Reconnect" button in the gui has been removed
> Automatic reconnection

- eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala
`localCommit` is checked twice instead of `localCommit` & `remoteCommit`?
> HTLCs in remote commit tx are not taken into account upon receiving Shutdown

- eclair-node/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-node/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-node/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
`remoteScriptPubKey` validity is only checked if we don't have a previously sent `Shutdown`, should not it be moved one line up?
> Validity of remote final script is not checked when a Shutdown was already sent

- eclair-node/src/main/scala/fr/acinq/eclair/io/Client.scala
- eclair-node/src/main/scala/fr/acinq/eclair/io/Peer.scala
This fixes a regression introduced in 75e4923002bdca8b04c2703cf6682a4b5da3ddf8 (#45).
Note:
- Supervisor strategy of `Client` should probably be `Escalate` instead of `Stop`
- client/server handling should be factored in one place
> Client must die when transport dies

- eclair-node/src/main/resources/gui/main/main.fxml
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
* also renamed `channelIdHex` to `channelId`
* fixed inconsistency when copying channel id in gui
> Fixed type cast issue with `peers` rpc service

- eclair-node/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-node/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-node/src/main/scala/fr/acinq/eclair/router/Router.scala
Currently router doesn't remember what peer sent each annoucement, and broadcasts new announcements to all peers, resulting in unnecessary spam.
> Make router not broadcast announcements back to sender

- eclair-node/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-node/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
As per lightningnetwork/lightning-rfc/pull/151
The implementation is simplistic, we don't really acknowledge the switch but rather keep both ids in memory. On node restart, only stored channels (=with a final channel id) will be restored, so the clean up will happen at that time.
> Channel id switch

- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
Note that we are not using `StateTimeout` anymore, instead we rely on timers set in the `onTransition` method.
We also disconnect switch connections when a new handshake is detected with the same host (note that this only occurs when local peers didn't detect that remote peer was disconnected).
> Use an exponential backoff timeout for connection retry

- README.md
Description is mandatory when using receive as method to generate payment request.
> Update with description to receive method

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/test/resources/logback-test.xml
- eclair-core/src/test/scala/fr/acinq/eclair/Pipe.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/FuzzyPipe.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/FuzzySpec.scala
Most notably, *we do not anymore discard previously signed updates*.
Instead, we re-send them and re-send the exact same signature. For that to
work, we had to be careful to re-send rev/sig in the same order, because
that impacts whatever is signed. OTOH, we still discard unsigned updates, but
we do it explicitly by sending a new `AddHtlcDiscarded` message.
This makes fuzzy testing far easier because now we know what updates were discarded.
Fuzzy testing has also been improved by disconnecting every x messages 
instead of every x seconds (which is unreliable on slow boxes).
NB: this breaks storage serialization backward compatibility
> Improved reconnection logic and fuzzy tests

- eclair-core/src/main/scala/fr/acinq/eclair/PortChecker.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-node-javafx/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
- eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala
Eclair wasn't stopping anymore when two instances were started with the
same ports.
Note: we should probably go one step further and put a lock in the datadir
directory.
> Bugfix: regression in init

- README.md
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- can be used to send up to 2x higher amount than requested according to BOLT11
- should be used for payment requests without amounts
> Add API method to accept requests with custom amount

- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/CoinFormat.scala
The user interface does need to display the millisatoshis part in a channel's balance/capacity.
This PR fixes an issue where msat part was truncated but still displayed, with a value equals to `000`.
see #139
> (gui) Remove millisatoshis part from milli-bitcoin amounts

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
When a node returns a `TemporaryChannelFailure` for its outgoing
channel, along with an unchanged `ChannelUpdate`, we temporarily
exclude this channel from route calculation.
Note that the exclusion is directed, as we expect this will mostly
happen when all funds are on one side of the channel and the channel
remains available in the other direction.
The duration of the exclusion can be configured by setting the
key `eclair.channel-exclude-duration`. Default value is 60s.
> Temporarily exclude channels from routes

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
This fixes two things:
- A peer  won't try to reconnect to a remote if there are no live/pending channels (e.g. if the last channel was closed).
- A peer won't set up reconnect timers if it does not have the ip address of the remote node
NB: 
There is a possible race condition when a new channel request arrives at the same time of a disconnection, resulting in the connection never being attempted again. However this is a corner case and not a huge concern.
Overall the connection handling is over-complicated and error prone. I think the `Switchboard` should probably not keep a map of `nodeId`->`connection`, it should delegate connection handling entirely to the corresponding `Peer`.
> Better handling of connection lifecycle in Peer

- eclair-core/src/main/scala/fr/acinq/eclair/db/ChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PeersDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala
It is less performant but our `ResultSet`->`Iterator` implementation
was buggy due to java/scala iterators requiring look-ahead capabilities
when iterating over the result, which `ResultSet` does not support.
This is a quick fix in the meantime.
> Replaced sqlite result iterators by lists

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/spv/BitcoinjKit.scala
- pom.xml
Related to [this commit](https://github.com/ACINQ/bitcoinj/commit/aed15e067adae7b34aba04c5983d1a6f306490ec).
> Skip `Wallet.isRelevant` when bitcoinj is used as a watcher

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
We previously skipped the `handleSync` function when we had to re-send
`funding_locked` messages on reconnection. This didn't take into account
the fact that we might have been disconnected right after sending the
very first `commit_sig` in the channel. In that case we need to first
re-send `funding_locked`, then re-send whatever updates were included in
the lost signature, and finally re-send the same `commit_sig`.
Note that the specification doesn't require to re-send the exact same
updates and signatures on reconnection. But doing this allows for a single
commitment history and allows us not to keep track of all signatures
sent to the other party.
This was reported in #165.
> Re-send htlc/sigs after `funding_locked`

- eclair-core/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
The scenario was already tested at a lower level, but this is
more realistic, with a real bitcoin core.
Note that we currently only steal the counterparty's *main output*,
we ignore pending htlcs. From an incentive point-of-view, it is an
acceptable tradeoff because the amount of in-flight htlcs should
typically be far less than the main outputs (and can be configured
with `max-htlc-value-in-flight-msat`).
> Added an integration test on revoked tx handling

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/WriteAckSender.scala
- eclair-core/src/test/scala/fr/acinq/eclair/crypto/TransportHandlerSpec.scala
Current implementation was simplistic, which resulted in writes
being rejected when OS buffer was full. This happened especially
right after connection, when dumping a large routing table.
It is not clear whether we need read throttling too.
> Added ACK-based TCP write back-pressure

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
The current trimming logic [1] as defined in the spec only takes
care of 2nd level txes, making sure that their outputs are greater
than the configured dust limit. However, it is very possible that
depending on the current `feeRatePerKw`, 3rd level transactions
(such as those claiming delayed outputs) are below the dust limit.
Current implementation wasn't taking care of that, and was happily
generating transactions with negative amounts, as reported in #164.
This fixes #164 by rejecting transactions with an amount below the
dust limit, similarly to what happens when the parent output is
trimmed for 2nd level txes.
[1] https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#trimmed-outputs
> Added a check amount>dust on `ClaimDelayedOutputTx`

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
~Channels only registered to `CurrentBlockCount` and `CurrentFeerate`
events at `WAIT_FOR_FUNDING_LOCKED`->`NORMAL` transitions.~
~We need to subscribe to those events upon reconnection, more precisely at
`SYNCING`->`NORMAL` and `SYNCING`->`SHUTDOWN` transitions.~
~Note: the `subscribe` method is idempotent, it will just return false if
sender has already subscribe to the same event.~
Instead of only subscribing to those events when we reach certain states,
we now always subscribe to them at startup. It doesn't cost a lot because
we receive an event only when a new block appears, and is much simpler.
Note that we previously didn't even bother unsubscribing when we weren't
interested anymore in the events, and were ignoring the messages in the
`whenUnhandled` block. So it is more …
> Have channels subscribe to blockchain events at creation

- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteChannelsDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteNetworkDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqlitePeersDbSpec.scala
This table was missing a primary key, which caused it to grow
indefinitely. It was deduped when loaded by the router but made
the startup time longer.
Also added duplication tests to other tables.
> Add primary key to channel_updates table

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
The way the store data currently doesn't allow for easy testing of this.
It will be improved in a later iteration.
This fixes #200.
> Always store channel state when a revocation is received

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentHop.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/HtlcGenerationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
Unlike `Hop` from `Router`, `ExtraHop` from `PaymentRequest` has a pre-calculated fee for a given amount, otherwise they are pretty similar so it makes sense for them to inherit a same `PaymentHop` trait and use it in `PaymentLifecycle.buildPayloads` instead of `Hop`. 
This way it's possible to build a payment by getting a `Seq[Hop]` from `Router` and then just `PaymentLifecycle.buildPayloads(..., Seq[Hop] ++ Seq[ExtraHop])`
> Support building payments with extra hops

- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/Handlers.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/SendPaymentController.scala
when sending an HTLC, we now use the optional min expiry that is specified in the BOLT11 payment request
> Use `min_final_cltv_expiry` included in payment request (if any)

- README.md
- eclair-core/src/main/resources/reference.conf
* Options in eclair configuration follow the HOCON syntax and it should be mentioned in the README file.
* the `chain` option should mention the available values: `test` and `regtest`. See https://github.com/ACINQ/eclair/issues/209
> [README] Added help for options syntax

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
> Handle remote `error` in `SYNCING` state

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
We may receive their announcement sigs before our watcher notifies us that the channel has reached min_conf (especially during testing when blocks are generated in bulk).
Also, always re-send our `announcement_signatures` in response to remote's `announcement_signatures`.
This fixes https://github.com/cdecker/lightning-integration/issues/8.
> Delay `announcement_signatures` when received early

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TestVectorsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala
(see https://github.com/lightningnetwork/lightning-rfc/pull/272)
We previously used the `payment_key` both for our main output, and to sign
the local `htlc_success`/`htlc_timeout` transactions.
With this change we can keep the `payment_privkey` offline, which is far
better from a security point of view because an attacker getting control
of a node wouldn't be able to just publish the current commitment
transaction and get the funds. The attacker would only be able to get our
`htlc_privkey`, which we only use in a 2-of-2 multisig with our
counterparty, so it is useless except if the attacker and the counterparty
are the same person, and even in that case only the pending htlcs would be
at risk.
Note that this implementation is a first step and actually keeps the
payment key to spend our …
> Use a separate `htlc_key` to sign 2nd stage htlc txs

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BitcoinJsonRPCClient.scala
use a local queue for outgoing rpc requests. this should be a better solution than
inceasing the number of concurrent requests (#221).
see https://doc.akka.io/docs/akka-http/current/scala/http/client-side/host-level.html#using-the-host-level-api-with-a-queue
for more information.
> bitcoin rpc client: queue requests locally

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/WatcherTypes.scala
Instead of extracting the parent output's redeem script from the witness.
>  Use tx-output pubkeyscript as hint for electrum watcher

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoinj/BitcoinjSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsBatchValidationSpec.scala
This was a workaround because bitcoin-core could produce malleable funding
transactions.
We now:
1) assume that all existing funds in bitcoin core are in segwit P2S addresses
2) manually create segwit change addresses when we create new transactions
This greatly simplifies implementation and integration tests.
> Removed bitcoin-core parent-tx hack

- README.md
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/package.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/ExtendedBitcoinClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
to avoid malleability issues, ask users to only have p2sh-of-p2wkh outputs.
on testnet, on startup we check that all UTXOs are p2sh (we cannot check that the
p2sh script is a p2wpkh script). it is not needed on regtest since there is no
chance that wallet tx will be malleated.
> Check that all UTXOS are p2sh on testnet

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
- eclair-node-gui/src/main/resources/gui/modals/openChannel.fxml
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala
We check that channel parameters are compliant with [BOLT 2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md) (this fixes #236).
We make sure that the counterparty chooses a decent `dust_limit`
because we want them to be able to publish their commitment, e.g. in a
data loss scenario. We also make sure that our configurable `dust_limit` isn't too low (this
fixes #234).
Also fixed our min `dust_limit` (542->546).
> Added more checks on `open`/`accept` messages

- BUILD.md
Building the `eclair-node` module only is a valid use case and the maven command to do it is not obvious. Added it to BUILD.md.
Also the `install` goal should be favored instead of `package`.
> Maven command to build eclair-node only

- .dockerignore
- Dockerfile
- eclair-core/pom.xml
- eclair-node-gui/pom.xml
- eclair-node/pom.xml
- pom.xml
Made by @pm47 , improve on https://github.com/ACINQ/eclair/pull/251.
--------------
Dependency to `git` has been removed, we now use `notag` when building without
a git directory.
In order to reliably fetch all dependencies, we do a first blank commit
(with no source files), then we copy the sources and do a real commit.
This is a simpler and more robust approach.
Also, fixed the .dockerignore to filter out IDE files.
> Docker support with repeatable builds

- Dockerfile
- pom.xml
This is a regression caused by 0794fb8d5a289a3c4e5a180cc203b4f8565c04bb,
because default values provided for `git.commit.id` `git.commit.id.abbrev`
are not overriden by git-commit-id-plugin plugin.
Instead we specify these variables when doing the docker build.
> Removed default values for commitid in pom

- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
The `relayer` wasn't correctly handling failures from the `register`, which led to `htlc` lingering without being failed. Sender would see payments stuck in `PENDING` state until they eventually timeout and cause the channel to be unilaterally closed.
> Handle corner case when relaying to an unknown channel

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
The `relayer` was missing failures sent by the `channel`, which led to `htlc` lingering without being failed. Sender would see payments stuck in `PENDING` state until they eventually timeout and cause the channel to be unilaterally closed.
This is a regression caused by f47ea72369c7bb9d01986ce9dbba00e37b83197d.
This fixes #264.
> Catch `channel` errors in `relayer`

- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- can now use `channelId` or `shortChannelId` in calls `channel`/`close`
- added a `channelsto` `nodeId` method
> Added more methods in API

- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/JsonSerializersSpec.scala
For some reason, eclair wasn't always able to serialize it correctly:
```
Error during processing of request: 'Do
not know how to serialize key of type class fr.acinq.bitcoin.OutPoint. Consider implementing a CustomKeySerializer.'. Completing with 500 Internal Server Err
or response. To change default exception handling behavior, provide a custom ExceptionHandler.
org.json4s.package$MappingException: Do not know how to serialize key of type class fr.acinq.bitcoin.OutPoint. Consider implementing a CustomKeySerializer.
```
Note: I wasn't able to reproduce.
> Add a custom json serializer for `OutPoint`

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
In commit 2e2a47e5fdd670af5edfa1cb3adfd2cfe94d2135 we inverted the
`local`/`remote` `toSelfDelay` when building the commitment tx, but forgot
to do the same when claiming the outputs.
Updated integration tests to reproduce the issue.
This fixes #290.
> Use the correct `toSelfDelay` when claiming funds

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/BasicBitcoinjIntegrationSpec.scala
When a `WatchSpent` is set, and the `watcher` detects the tx has already been spent, it will try to find the spending tx.
We previously looked forward starting at the block in which the funding tx was confirmed.
We now look backward starting from now. It is faster because most of the time the spending tx was published recently and we just shutdown/restarted the node.
> Faster search of spending tx when using bitcoind

- README.md
- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/DBCompatChecker.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- pom.xml
This PR is built upon https://github.com/ACINQ/eclair/pull/312
This PR fixes https://github.com/ACINQ/eclair/issues/282
The `Service` class is reworked (especially the route pattern maching) to have a more readable code. Route completion is handled on a case by case basis, for each call, which enable granular response/errors.
HTTP code should now be consistent with the error returned.
> Improve JSON RPC API error handling

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsBatchValidationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
Our current pruning logic is very basic, we just clean up channels once every day. It is not very effective, because inbetween two pruning operations nodes can send us the same stale announcements we just removed.
This change makes the `router` filter out stale channels *before* processing them. As a consequence, it only processes a `channel_anouncement` if there is at least a corresponding `channel_update`.
> Pre-validation announcements pruning

- README.md
- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/NodeURI.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Server.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/BasicBitcoinjIntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/Handlers.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/GUIValidators.scala
- connection and channel opening are now separated, simplified
`switchboard`
- use a single authenticator for both incoming and outgoing connections
- `peers` api call now returns current state and channel count
> Reworked peer management

- README.md
- eclair-core/eclair-cli
- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Announcements.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteNetworkDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala
- eclair-node-gui/src/main/resources/gui/splash/splash.fxml
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxPreloader.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
- removed old `channels` case that shadowed the new one
- `connect` case was using `open` method
> Fixed eclair-cli

- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/NodeURI.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/BasicBitcoinjIntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/NodeURISpec.scala
- eclair-node-gui/src/main/resources/gui/main/main.fxml
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/Handlers.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/ContextMenuUtils.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/GUIValidators.scala
The IP address of a lightning node can be IPV6 which has a different validation ruleset than IPV4.
NodeURI is updated to be able to parse IPV6 adresses.
Note: the host should be enclosed with brackets `[` `]` if the address is IPV6 and it doesn't have brackets.
This is compliant with [RFC 3986, section 3.2.2](https://tools.ietf.org/html/rfc3986#section-3.2.2)
Thanks to @Sgt-Miller for pointing this out in #343
> Handle ipv6 addresses

- README.md
Updated username and password so now you don't get the following error:
```
Could not connect to Bitcoin Core using JSON-RPC
Make sure that Bitcoin Core is up and running and RPC parameters are correct.
```
Also explicitly stated the port for testnet, this is redundant if you haven't got it set to anything but for those who have already defined `rpcport` they now know to change it.
> Updated username, password and port in readme

- eclair-node/src/main/scala/fr/acinq/eclair/Textui.scala
Reference PR #381 
As requested, I applied the change to `wip-android`.
I didn't change the comment on this line (as requested) although I think it should mention `bitcoind`:
https://github.com/ACINQ/eclair/blob/e28ac3990ea86e16398538176a87652abee91663/eclair-core/src/main/resources/reference.conf#L18
The reason why I think it makes sense on `wip-android` but not in the `master` branch is because `watcher-type` is `bitcoind` by default.
> Fix a comment

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-node-gui/src/main/resources/gui/main/main.fxml
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
Payment preimage is important for the sender of the payment as it proves that he actually paid the request. 
This PR adds a `paymentPreimage` field to the `PaymentSent` event.
The GUI also shows a _payment preimage_ column in the _sent_ table in the Activity tab.
> Include payment preimage in PaymentSent event

- README.md
The sample value for eclair.bitcoind.zmq, used as is, with no quotes, throws an error:
2018-01-22 21:40:26,190 ERROR fr.acinq.eclair.gui.FxPreloader   - An error has occuredcom.typesafe.config.ConfigException$Parse: /Users/dimitris/.eclair/eclair.conf: 8: Expecting end of input or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:482)
at …
> Added quotes to sample parameter value in README.md

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumEclairWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSimulatedClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
Setup can be given a seed that is used by eclair, instead of generating one and writing it to file. This seed is also used by the embedded electrum wallet if this is the chosen watcher. Mnemonics based methods are removed from ElectrumWallet.
Eclair with electrum watcher can not be started if the seed is not provided to the setup.
> Added an optional seed to Setup

- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/GUIValidators.scala
- Replace "url" by "uri" in GUI
- Remove the port part of hostRegex
The ending of hostRegex does nothing since commit af7d7b1.
It also made negative port numbers valid.
- Invalidate ports below 0 and above 65535
Ports out of range cause errors in the console but do nothing in the
GUI.
**Here are some examples:**
`03da7b53368bbdbfe0d413d14237646897a1ac73a7687dfe0530240ed72cb65578@127.0.0.1:65536`
`03da7b53368bbdbfe0d413d14237646897a1ac73a7687dfe0530240ed72cb65578@127.0.0.1:-1`
**Both of these URIs cause these errors in the console:**
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLo …
```
> Invalidate ports below 0 and above 65535

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/NetworkEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteNetworkDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
We previously revalidated all channels on startup, which was very inefficient and took a long time.
With this pr, announcements are also stored in a separate sqlite database `network.db`.
> Store channel funding txid with announcements db

- eclair-core/src/main/scala/fr/acinq/eclair/PortChecker.scala
- eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala
When using eclair-node, a 'null' message is displayed to the user when TCPException is thrown. This PR sets a message so that a useful message is printed instead.
Added a last resort clause where the exception class name is displayed if the exception message is null.
fixes #399
> TCPException message error should be defined

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
For consistency with existing `ChannelSignatureReceived`.
> Publish a `ChannelSignatureSent` for each outgoing commitment sig

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/LocalKeyManager.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/crypto/LocalKeyManagerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/RustyTestsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
We restore the old nodeid key path so nodes will keep the same id after an upgrade
> Restore node id key path

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
This is a simplification that we can do following 24dadff6253278662d95bd1bc4871cddff706fe4.
> Use default seed for electrum if none is provided

- README.md
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-node-gui/src/main/resources/gui/main/channelPane.fxml
- eclair-node-gui/src/main/resources/gui/main/main.css
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
As soon as we receive a valid closing signature, we will publishing the
resulting closing tx instead of our commitment tx if we need to
immediately close the channel (before end of negotiation, e.g. in case
of errors, or in case the counterparty goes OFFLINE).
When the closing signature didn't correspond to one we sent ourselves, we
weren't properly recognizing the publishing tx and went into
`ERR_INFORMATION_LEAK` state.
> Better handling of force-closing of channels

- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/Handlers.scala
- eclair-node/src/main/resources/application.conf
- eclair-node/src/main/resources/logback_colors.xml
Both the GUI and the API should handle AskTimeoutException failures as specific cases: GUI should ignore them, API should print a pretty response.
Increased ask timeout to 60s ; increased akka http server timeout to 120s. This fixes #414 where eclair-cli would fail to parse the server timeout response.
> Future timeouts should not be handled as failures in frontend

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
Private channels need specific handling because we can't rely on
`WatchEventSpentBasic` event for tracking whether they are still up.
> Proper cleanup of private channels

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
Implementation should guarantee that in case of a
`BITCOIN_FUNDING_PUBLISH_FAILED` event, the funding tx will *never* be
published (see `commit` method in trait `EclairWallet`).
With that in mind, there is no need for a `ERR_FUNDING_PUBLISH_FAILED`
state, instead we can just permanently close the channel. Note that the
user will receive an error "couldn't publish funding tx".
> Close channel on `BITCOIN_FUNDING_PUBLISH_FAILED`

- README.md
And specify that we will soon drop support for older (< 0.16) versions of Bitcoin Core
> Update link to latest release

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumEclairWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletBasicSpec.scala
It will use all available utxos, including unconfirmed and locked utxos, and return a signed transaction and fee it pays to the bitcoin network.
> Electrum: add a `send all balance` method

- README.md
- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
checkinvoice parses an invoice/PaymentRequest and returns the JSON object. Usecase is that you need to be 100% sure that Eclair is paying the amount you expect! Easy to be factor of 1000 out if someone has a bug!
checkroute takes an invoice and checks if we have a route to pay at that moment. Is useful when you do not want to accept a request for payment you know you can not make.
Includes tests for checkroute.
> Addition of API calls checkinvoice and findroute

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
This regression caused in 438d8e3d4b35e781ccb760199576f952f45c1b05 is what caused flaky tests during the past few days.
Calling `sender()` inside a `Props()` leads to undefined behavior.
> Fixed race condition in `ElectrumClient`

- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
Result returned by the API for payment failures did not contain the error message. Added a serializer for `Throwable` (local failures), and a serializer for `FailureMessage` (remote failures).
> Added json serializers to handle payment failures

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/ChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/test/resources/logback-test.xml
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteChannelsDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
Previously we were only stealing the remote's main output when they publish a revoked commit, and were relying on a sufficiently high `channel_reserve` do deincentivize cheating.
In order to also steal the htlc outputs, we need to handle both cases:
- they only publish their revoked commit tx => we claim the htlc outputs directly from the commit tx
- they publish their revoked commit tx, and their 2nd-stage HTLCSuccessTx and HtlcTimeout txes => we claim the output of these htlcs tx
To do that, we need to be able to reconstruct htlc scripts (`htlcOffered` and `htlcReceived`), therefore we need to store `paymentHash` and `cltvExpiry` for each htlc we sign. Note that this won't be needed in the future when we have MAST.
> Extend penalty to stealing HTLC outputs

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
Regression caused signature to use wrong utxo amount which means it would not be valid, and the
funding tx could not be published.
> Electrum: fix signature bug

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumEclairWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/package.scala
- eclair-core/src/test/resources/integration/bitcoin.conf
- eclair-core/src/test/scala/fr/acinq/eclair/PackageSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
Our android wallet will now be able to send funds to bech32 addresses.
We still need to add integration tests with bitcoin core
> Accept bech32 addresses

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/WatcherTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/WatcherSpec.scala
When publishing delayed txes, we need to first watch the parent
transaction in order to know how many confirmations it has.
Electrum relies on hashes of `pubkeyScript`s in order to track
transactions.
In order to do this without having the parent transaction at hand,
we recompute the `pubkeyScript` from the child transaction witness data
and give it to Electrum.
But if the script was a `pay2wsh`, we were using the `redeemScript`
instead of computing the `pubkeyScript`.
This is the root cause of https://github.com/ACINQ/eclair-wallet/issues/17.
> Correctly extract `pubkeyScript` from witness data

- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/JsonSerializersSpec.scala
Fixes #565
The rendering of addresses can be checked with: 
```curl -X POST -H 'content-type: application/json' -u :bar -d '{"jsonrpc": "2.0","method": "allnodes"}' http://127.0.0.1:8080```
> Add json serializers for `NodeAddress` type

- eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
- pom.xml
It provides additional key BIP32/44/49/84 related functions, including a method to check mnemonic codes checksum (see https://github.com/ACINQ/eclair-wallet/issues/52)
> Update bitcoin-lib to 0.9.17

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
Fallback on-chain address could be provided but was not used in payment request generation.
> Use fallbackAddress tag

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
- eclair-core/src/test/resources/application.conf
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
This PR fixes [issue #576](https://github.com/ACINQ/eclair/issues/567) which is not critical, but extremely annoying.
> Remove utxo lock when call to `signrawtransaction` fails

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
If the closing tx is already in `mutualClosePublished`, it means that we
already know about it and don't need to re-handle it again. Everytime we
succesfully negotiate a mutual close, we end up publishing ourselves the
closing tx, and right after that we are notified of this tx by the
watcher. We always ended up with duplicates in the
`mutualClosePublished` field.
This fixes #568.
> Check if closing tx is known before handling it

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala
Because we keep sending them as part of announcements.
Using `CacheBuilder.weakKeys` will cause the serialized messages to be
cleaned up when messages are garbage collected, hence there is no need
to set a maximum size.
> Cache serialized network announcements

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
Closing transactions were getting rejected on regtest because min feerates were not enforced.
> Enforce min feerate per byte on regtest

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
Fixes #599 . In this PR we make sure we don't consider watch-only addresses when performing initialization checks on bitcoind.
> Filter out non-spendable outputs from bitcoind 'listunspent' call during setup 

- Dockerfile
This PR fixes the docker build by downgrading maven to version 3.3.9 as specified in the build instructions. Also updates the docker base images to newer java versions.
> Fix maven version to 3.3.9 in docker build

- eclair-core/src/main/resources/electrum/servers_testnet.json
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPool.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPoolSpec.scala
Use the latest electrum testnet server list, and make sure we have selected a stable server before we start our client pool test.
> Update electrum testnet server list, and fix flaky client pool tests

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/package.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/PackageSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
We currently use feerate-per-kw = feerate-per-kb / 4, which gives 250 for 1000 sat/kb, which can result in transactions that are below the minimum relay fee of 1000 sat/kb.
This is because bitcoin core checks minimum relay fees using a transaction's virtual size (and not its actual size in bytes).
So we want :
fee > 1000 * virtual size
feerate-per-kw * weight > 1000 * (3 * weight / 4)
feerate_per-kw > 250 + 3000 / (4 * weight)
With a conservative minimum weight of 400, we get a minimum feerate_per-kw of 253
> Set a minimum feerate-per-kw of 253 (fixes #602)

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
This is a second attempt based on suggestions from https://github.com/ACINQ/eclair/pull/594 since I've deleted my fork for that one.
`path("ws")` is moved inside `handleRejections` block, having it in `authenticateBasicAsync` yields `Missing` credentials even if I try to connect using `ws://eclair:pass@127.0.0.1:8080/ws`
> Inform clients about incoming payments via websocket connection

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPool.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSimulatedClientSpec.scala
The `ElectrumReady` message is changed to contain the address of the electrum server which the eclair electrum client connects to. This will provide feedback to the user (esp. the eclair wallet app on android) as to which electrum server is currently used.
> Add server address in ElectrumReady object

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
Remove the final expiry check when we send payments (we still keep this check when we receive an HTLC).
Fixes #626
> Routing: remove final CLTV expiry check on outgoing HTLCs

- README.md
- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
Add option to have 3rd parameter to receive API call so you can set the expiry.
> Adding ability to set expiry when creating a new invoice

- eclair-core/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
Added an optional routing parameter to the `ReceivePayment` object to be able to create a `PaymentRequest` with extra routing information, which is useful for nodes that are not announced on the network but still want to receive funds.
> Generate payment request with extra routing information

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/test/resources/logback-test.xml
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala
In order to reduce unnecessary back-and-forth in case an outgoing
channel doesn't have enough capacity but another one has, the relayer
can now forward a payment to a different channel that the one specified
in the onion (to the same node of course).
> Relay payments to preferred channels

- eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/PruningSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RoutingSyncSpec.scala
When we receive a reply to a channel query, we check whether channels that we have
but they don't are stale and can be pruned.
> Router: prune channel that our peer does not have

- eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
- eclair-core/src/test/scala/fr/acinq/eclair/PackageSpec.scala
Java Longs are signed, and we cannot use Long.compareUnsigned() which is not available in JDK7
> Use "unsigned long" comparison for short channel ids

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
This allows e.g. the mobile app to know why a channel got closed.
Depending on whether the error is local or remote, a
`Throwable`/`wire.Error` will be attached to the event.
> Send an event when an error occurs in a channel

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
This can happen in an unilateral close scenario, when local commit
"wins" the race to the blockchain, and some outgoing htlcs weren't yet
signed by remote.
This fixes #649.
> Fail unsigned outgoing htlcs at CLOSING

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
Our recovery logic didn't handle the case were our local commit is
up-to-date, but we don't know their local commit (probably because we
just lost the last state were we sent them a new `commit_sig`).
Also, process all cases in the same `channel_reestablish` handler, like we do
everywhere else.
Moved the sync tests in `Helpers` so that they are more understandable.
> Handle unknown remote commit in recovery logic

- eclair-core/src/main/scala/fr/acinq/eclair/router/NetworkEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
as requested by BOLT 7, and add a event to follow the synchronization progress.
> Send `query_short_channel_ids` sequentially

- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
`ChannelPersisted` is sent everytime a channel data is stored to disk, this is useful for the Android Eclair Wallet.
> Fixed some logs and added `ChannelPersisted` event

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/SmoothFeeProvider.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitcoinCoreFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/SmoothFeeProviderSpec.scala
It will return the moving average of fee estimates provided by its internal fee provider, within a user defined window that can be set with eclair.smooth-feerate-window. The default value is 1 which doe not change the current behaviour.
This should help prevent channels from getting closed when fees rise quickly and we send an `update fee` message that our peer disagrees with.
> Add a "smooth" fee provider

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-node/src/main/resources/application.conf
This is required because since f3676c6 we retrieve multiple full blocks in parallel.
Also added minor improvements.
> Removed max body size in http client

- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
There are two different expiry checks:
(a) relative checks: when relaying an htlc, we need to be sure that
the difference of expiries between the outgoing htlc and the incoming
htlc is equal to the `cltv_expiry_delta` that we advertise in the
`channel_update` for the outgoing channel;
(b) absolute checks: we need to make sure that those values are not too
early or too far compared to the current "blockchain time".
The check for (a) needs to be done in the `Relayer`, which is the case
currently. This means that we will check the expiry delta *after* having
signed the incoming htlc, and we will fail the htlc (not the channel) if
the delta is incorrect.
The check for (b) was done in the `Commitments.receiveAdd` method. This
seems to make sense, because we would want to make sure as early as …
> Fixed htlc absolute expiry checks

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/resources/logback-test.xml
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
This greatly facilitates debugging because we can correlate diag messages with current commitment, all in INFO.
> Switched commitment log level to info (minor)

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
This event includes the block height at which we will be able to claim
our main output, which comes in handy for user interfaces.
> Added `LocalCommitConfirmed` event

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
If we don't have the origin, it means that we already have forwarded the fulfill so that's not a big deal.
This can happen if they send a signature containing the fulfill, then fail the channel before we have time to sign it.
> Ignore 'origin htlc not found' in CLOSING

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
When we receive a recent update for a channel that we had marked as stale we must send a query to the underlying transport, not the origin of the update (which would send the query back to the router).
> Fix handling of born again channels

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
This is a simple optimisation, we don't have to keep all `update_fee`, just the last one.
cf BOLT 2:
> An update_fee message is sent by the node which is paying the Bitcoin fee. Like any update, it's first committed to the receiver's commitment transaction and then (once acknowledged) committed to the sender's. Unlike an HTLC, update_fee is never closed but simply replaced.
> Replace `update_fee` in commitments

- eclair-core/eclair-cli
This should fix #695, and also adds the channel point in the default channel output.
```bash
$ ./eclair-cli channel 00fd4d56d94af93765561bb6cb081f519b9627d3f455eba3215a7846a1af0e46
{
"nodeId": "0232e20e7b68b9b673fb25f48322b151a93186bffe4550045040673797ceca43cf",
"shortChannelId": "845230006070001",
"channelId": "00fd4d56d94af93765561bb6cb081f519b9627d3f455eba3215a7846a1af0e46",
"state": "NORMAL",
"balanceSat": 9858759,
"capacitySat": 10000000,
"channelPoint": "470eafa146785a21a3eb55f4d327969b511f08cbb61b566537f94ad9564dfd00:1"
}
```
> Improved eclair-cli

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
Previously it was only possible to update relay fee in NORMAL state,
which is not very convenient because most of the time there are always
some channels in OFFLINE state.
This works like the NORMAL case, except that the new `channel_update`
won't be broadcast immediately. It will be sent out next time the
channel goes back to NORMAL, in the same `channel_update` that sets the
`enable` flag to true.
Also added a default handler that properly rejects the
CMD_UPDATE_RELAY_FEE command in all other states.
> Handle update relay fee in OFFLINE state

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
When updating relay fee in state OFFLINE, the new channel_update must
have the disabled flag on.
This caused tests to be flaky, added necessary checks to always make
them fail in case that kind of regression happens again.
> Fixed regression caused by 7a4f175

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-node/src/main/resources/logback.xml
Use one file per day, keep 90 days of logs with a total maximum size capped at 5 Gb.
> Logging: use a rolling file appender

- README.md
Bitcoin Core 0.17.0 deprecates the `signrawtransaction` RPC call, which will be removed in version 0.18.0, you need to enable it call if you want your eclair node to use a 0.1.70 node. 
See #730
> Add instructions for Bitcoin Core 0.17.0 [ci skip]

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/ChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteChannelsDbSpec.scala
We persist htlc data in order to be able to claim htlc outputs in
case a revoked tx is published by our counterparty, so only htlcs
above remote's `dust_limit` matter.
Removed the TODO because we need data to be indexed by commit number so
it is ok to write the same htlc data for every commitment it is included
in.
> Only persist htlcs above remote's `dust_limit`

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
We add one block in order to not have our htlc fail when a new block has just been found.
This fixes #651.
> Always add 1 block to the `finalCltvExpiry`

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
Allows a user to bypass the default servers list and force eclair to always connect to a specific electrum server. This feature has been requested by users of the mobile node.
This PR adds an optional `overrideElectrumServers` parameters to the `Setup` class. This optional parameter, which is an `InetSocketAddress` object, will always supersede the default list of electrum servers. If this parameter is set, eclair will always attempt to connect to this particular server.
> Support for custom Electrum server

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/HtlcGenerationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TestVectorsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
> Reject received payments where PaymentRequest Expiry Tag time has been exceeded.

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
We need to put back watches on restart in "future remote commit published" scenarii, otherwise we will never consider the channel closed if we restart before the "claim main output" tx is confirmed. Note that there was no risk of losing funds, but the channel would have lingered forever.
> Watch future remote commit on restore

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
The number of channels in LN keeps increasing, and so does the initialization time of the router. Uninitialized `Router` prevents `TransportHandler` from processing the wire messages. I added a `Promise` to track `Router`'s initialization progress to make sure that all connections are established  after that.
> Wait for Router to be initialized

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzyPipe.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
Previously we weren't updating them since the channel creation, which
was wrong: both local and remote features may change after a
reconnection.
> Update connection-level features at reconnection

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
`NioEventLoopGroup` is expensive to create and should be shared with all clients. This also prevents issues when several event loop groups are created and are not shutdown correctly.
> NioEventLoopGroup is shared with all clients in ElectrumClient

- eclair-core/src/main/resources/electrum/servers_mainnet.json
Some servers in this list are unresponsive, or connection always fails. Removing these servers improves startup performances when using electrum.
> Cleaned up mainnet electrum servers list

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
Turned on `TCP_NODELAY` to improve latency.
> Tweak parameters to optimize ElectrumClient connections

- eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
- eclair-core/src/test/scala/fr/acinq/eclair/ShortChannelIdSpec.scala
This PR implements the new human readable format proposed in the BOLT1.1 for the short_channel_id.
> Use BOLT specific formatting for short channel id

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/AuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/ChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PeersDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePeersDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala
Note that there is no risk of corruption currently (concurrent writes would just fail with `SQLITE_BUSY`), but with this we make sure that there is only one instance of eclair using the same `eclair.sqlite` db file at any time.
From https://www.sqlite.org/pragma.html: 
> There are three reasons to set the locking-mode to EXCLUSIVE.
> 1. The application wants to prevent other processes from accessing the database file.
> 2. [...]
> 3. [...]
> Add exclusive locks to channels sqlite db

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
The goal is to reduce attempts from other nodes in the network to use
channels that are unbalanced and can't be used to relay payments.
This leaks information about the current balance and is a privacy
tradeoff, particularly in this simplistic implementation. A better way
would be to add some kind of hysteresis in order to prevent trivial
probing of channels.
> Disable local channels below reserve

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
As per the spec 1.1 we should not offer a to_self_delay value greater than 2016, nor accept a channel that offers such a high value.
> Limit CLTV value to 2016

- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/CommandBuffer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/ChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/HtlcReaperSpec.scala
If we have stopped eclair while it was forwarding HTLCs, it is possible
that we are in a state were an incoming HTLC
was committed by both sides, but we didn't have time to send
and/or sign the corresponding HTLC to the downstream node.
In that case, if we do nothing, the incoming HTLC will
eventually expire and we won't lose money, but the channel
will get closed, which is a major inconvenience.
This check will detect this and will allow us
to fast-fail HTLCs and thus preserve channels.
> Detect broken HTLC links at startup

- README.md
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
Compute the routes backward from the target and with the correct channels cost, nodes that are 'neighbor' to the local node (direct channel) will have a routing cost of 0.
> Compute routes backward

- eclair-core/pom.xml
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/ChannelSelectionSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
Our current channel selection is very simplistic: we relay to the
channel with the largest balance. As time goes by, this leads to all
channels having the same balance.
A better strategy is to relay to the channel which has the smallest
balance but has enough to process the payment. This way we save larger
channels for larger payments, and also on average channels get depleted
one after the other.
> Relay to channel with lowest possible balance

- eclair-core/src/test/scala/fr/acinq/eclair/payment/ChannelSelectionSpec.scala
akka.http.impl.util.DefaultNoLogging is not available in akka 2.3 which we use on Android.
> ChannelSelectionSpec: use akka.event.NoLogging

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
We previously assumed that the `gossip_timestamp_filter` only applied to
future messages, so we set `first_timestamp` to 0 in order to have a
pass-all filter.
But BOLT 7 actually says that the remote peer:
> SHOULD send all gossip messages whose timestamp is greater or equal to
first_timestamp, and less than first_timestamp plus timestamp_range
Which means that the way our filter was set, the remote peer would dump
the entire routing table on us.
By setting `first_timestamp` to the current time, we achieve what we
want. The synchronization of older messages is done by sending a
`query_channel_range` and then one or several `query_short_channel_ids`.
> Set timestamp filter lower bound to current time

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
If we are reconnecting to a peer, and receive a `Peer.Connect` to the same peer using the same address, we shouldn't initiate a second connection.
> Ignore reconnections requests to the same peer with the same address

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/WatcherTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsBatchValidationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
While it makes sense to exclude from the routing table channels for
which there is a spending tx in the mempool, we shouldn't blame our
peers for considering the channel still opened if the spending tx hasn't
yet been confirmed.
Also, reworked `ValidateResult` with better types. It appears that the
`NonexistingChannel` error wasn't really useful (a malicious peer would
probably point to an existing funding tx, so there is no real difference
between "txid not found" and "invalid script"), so it was replaced by
`InvalidAnnouncement` error which is a more serious offense (punished
by a disconnection, and probably a ban when we implement that sort of
things).
> Proper handling of gossiped channels being spent

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/db/WalletDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/db/sqlite/SqliteWalletDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletBasicSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSimulatedClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/db/sqlite/SqliteWalletDbSpec.scala
Persist a partial view of our wallet to enable faster startup time.
Users will be able to create transactions as soon as we've checked that we're connected to a "good" electrum server. In the unlikely event where they were able to create and try to publish a transaction during the few seconds it took to finish syncing and their utxo was spent (because they were trying to use an unconfirmed utxo that got double spent, or if they spent their utxo themselves from another wallet initialized with the same seed  while his one was offline), publishing the tx will fail.
> Improve Electrum start-up time

- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/JsonRpcServiceSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
When we are disconnected and we don't have any channel with that peer,
we can stop it and remove its address from db.
We also need to handle the case where we are in `DISCONNECTED` or
`INITIALIZING` state and we are notified that the last channel we had
with that peer just got closed.
~Note that this opens a race condition in the switchboard, if we receive
an incoming connection from that same peer right after we stopped it,
and before the switchboard received the `Terminated` event. If that
happens, then `Peer.Connect` or `Peer.OpenChannel` will timeout. We
could also have the switchboard listens to deadletter events, but that
seems a bit over the top.~ Not anymore since eea7253.
> Stop disconnected peer when it has no channels

- eclair-core/src/main/resources/reference.conf
See: https://github.com/lightningnetwork/lightning-rfc/wiki/Lightning-Specification-1.1-Proposal-States
> Increased max-to-local-delay-blocks to 2016

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
This is a regression caused by 884812ade0060aa09c5fe97bbd70cac0fdf66ca8, added a test.
> Support all-uppercase payment requests

- eclair-core/src/main/scala/fr/acinq/eclair/router/NetworkEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/MainController.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/IndexedObservableList.scala
The GUI took a very long time to startup because nodes and channels were
stored in javafx `ObervableList` which doesn't allow random access. We
can't easily use `ObservableMap` because `TableView` do not support
them.
As a workaround, created an `IndexedObservableList` which keeps track of
indices in `ObservableList` so that we can still have fast random
access.
Also, now grouping announcements in `Networkevent` instead of sending
them one by one.
> Faster gui startup

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/db/sqlite/SqliteWalletDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSimulatedClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/db/sqlite/SqliteWalletDbSpec.scala
- clear history status when we get disconnected and still have pending history requests
- represent block heights as signed integers
- prepend a version number to persisted electrum wallet data
> Electrum fixes

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSimulatedClientSpec.scala
This PR updates the prefix of electrum xpub to `upub` for testnet and `ypub` for mainnet, since we support BIP49.
> Use ypub prefix for Electrum xpub

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
It sounds like a more reasonable default value, 144 was too short.
> Set default `to-remote-delay-blocks` to 720

- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
- pom.xml
Use bitcoin-lib v0.10 which has finally been synced to maven central.
Fix transactions unit test (the check in the test was using the whole locktime and not the last 24 bits).
> Minor fixes (dependencies, unit tests)

- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
With fe31f2d9d2754d6dd979bc1f454ae4bee7fc8b6d the heuristics introduced a cost function that is not monotonic and that led scenarios where the path-finding would produce an invalid result and even get stuck in an endless computation. This PR fixes that by making sure the cost function is monotonic.
> Ensure the cost function in path-finding is monotonic

- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPoolSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
This PR removes Electrum unit tests that connect to an actual testnet Electrum servers. This test was flaky because Electrum testnet servers are not very reliable, and we already test against a real ElectrumX server in our Docker tests.
This PR also speeds up tests that use a bitcoind daemon by generating 150 blocks instead of 500 to initialise bitcoind.
> Improve unit tests

- eclair-core/src/main/scala/fr/acinq/eclair/payment/Autoprobe.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
Cleanup of the SendPayment command in which there was a leftover field 'randomize' currently replaced by its analogous in the RouteParams.
> Remove unused param 'randomize' from SendPayment command

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
We mistakenly implemented `Peer.timestampInRange` as opt-out whereas it
should be opt-in.
> Don't send updates if no filter has been set

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
Instead of iterating over watches, we use a map indexed by the `OutPoint` we are watching.
> Check `WatchSpent` in constant time

- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
Channels with feeBase=0 and feeProportional=0 cause issues to the path-finding algorithm, this PR makes eclair consider those channel as feeBase=1msat when computing a route but then when the payment is sent out we use its actual fee (zero).
> Deal with channels with fees=0 when computing a route

- README.md
This PR fixes the link in the README for the old API documentation.
> Fix the broken link to old API documentation

- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
The `/channels`  API had an inconsistent name in its parameter, this PR renames it to `nodeId`. Among the rename the parameter has been factored out since it's now used in many places in the API definition. 
TODO: update doc.
> Rename 'toRemoteNodeId' to 'nodeId' in /channels API

- eclair-core/pom.xml
- eclair-node-gui/pom.xml
- eclair-node/pom.xml
- pom.xml
We have enough major changes from the last release to justify switching to 0.3.
> Set version to 0.3-SNAPSHOT

- eclair-core/src/main/resources/electrum/servers_mainnet.json
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPool.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPoolSpec.scala
Update  mainnet server list, properly deal with nodes that do not comply with the version of the protocol that they advertise, and increase timeout for our client pool test (which sometimes fails on travis).
> Electrum: fixes and improvements

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/TestWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
Otherwise the UTXOs will stay locked, and the channel will stay to `OFFLINE` forever because it doesn't have a commitment.
> Rollback funding tx if disconnected in WAIT_FOR_FUNDING_SIGNED

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
This avoids herd effect that occured when all peers were synchronized.
> Add random delay to rebroadcast 

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPool.scala
(At least on testnet), when using 3.3.2 or below, some servers will send back errors with a message that says "no errors but please upgrade". 
Also specify in our logs when we get disconnected from our master Electrum server or from a backup server.
> Electrum: update client name

- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumxService.scala
There was an obscure Docker error when trying to start an Electrum
server in tests.
It appears that there is a [conflict between Docker and Hyper-V](https://github.com/docker/for-win/issues/3171) on some range of ports.
A workaround is to just change the port we were using.
> Make electrum tests pass on windows

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
Our `open` API calls expects an optional fee rate in satoshi/byte, which is the most widely
used unit, but failed to convert to satoshi/kiloweight which is the standard in LN.
We also check that the converted fee rate cannot go below 253 satoshi/kiloweight.
> API: fix fee rate conversion

- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
This PR fixes the broken behavior of the websocket when used over HTTP POST together with basic auth. A test has been added to verify we can use the socket WITH authentication.
> Expose the websocket over HTTP GET

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/db/sqlite/SqliteWalletDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/db/sqlite/SqliteWalletDbSpec.scala
Locks held on utxos that are used in unpublished funding transactions should not be persisted.
If the app is stopped before the funding transaction has been published the channel is forgotten
and so should be locks on its funding tx utxos.
> Electrum: do not persist transaction locks

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
Note that this doesn't mean that we will buffer 1M objects in memory:
those are just pointers to (mostly) network announcements that already
exist in our routing table.
Routing table has recently gone over 100K elements (nodes,
announcements, updates) and this causes the connection to be closed when
peer requests a full initial sync.
> Set `MAX_BUFFERED` to 1,000,000

- Dockerfile
The Maven 3.6.0 SHA256 checksum was invalid and cause the docker build to fail( the current checksum is for Maven 3.5.4)
References: 
Old checksum: https://checker.apache.org/sums/89eea39183139e5f8a0c1601d495b3b6
New checksum: https://checker.apache.org/paths/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz.html
> Fix Dockerfile Maven Sha checksum

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/AuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Auditor.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
We now keep track of all local/remote channel errors in the audit db.
> Add channel errors in audit db

- README.md
- eclair-core/pom.xml
- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/BackupHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/BackupHandlerSpec.scala
Backups are handled by a custom actor that listens to persistence events sent by channels. They are done in 2 steps:
- create a sqlite backup in a temporary file
- rename the temporary file, which should be atomic (though it actually depends on the OS and file system).
Users would typically rename/move the backup file then make a safe copy of it.
Backups are sequential. If backup requests pile up while a backup is still in progress, only the last one will be kept.
> Live channel database backup

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/db/BackupHandler.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/BackupHandlerSpec.scala
We now specify that we want to atomically overwrite the existing backup file with the new one (fixes
a potential issue on Windows).
We also publish a specific notification when the backup process has been completed.
> Backup: explicitely specify move options

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
In order to improve startup time, electrum wallet would dispatch its "ready" event even though if it was still syncing, which could sometimes make the wallet have an incorrect state. This PR fixes that.
Note that this fix is already embedded in version `0.2-android-beta22` used by Eclair Mobile `0.4.5`
> ElectrumWallet should not send ready if syncing

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
Log local channel parameters, and our peer's open or accept message.
This should be enough to recompute keys needed to recover funds in case of unilateral close.
> Channel: Log additional data

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
Instead of logging all headers when we download header chunks, we just logs the first and last ones.
> Electrum: make debug logs shorter

- eclair-node-gui/src/main/scala/fr/acinq/eclair/JavafxBoot.scala
- eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala
This PR partially reverts the behavior introduced with #949, now in case of error at boot we print only a friendly message to stderr, logs however still contain the full stack trace.
> Do not print the stacktrace on stderr when there is an error at boot

- README.md
- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
This removes any ambiguity about the content of the file.
> Rename `eclair.bak` to `eclair.sqlite.bak`

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/LocalPaymentHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Announcements.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqlitePaymentsDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
This PR standardizes the way we compute the current time as unix timestamp 
- Scala's Platform is used and the conversion is done via scala's concurrent.duration facilities
- Java's Instant has been replaced due to broken compatibility with android
- AuditDB events use milliseconds (fixes #970)
- PaymentDB events use milliseconds
- Query filters for AuditDB and PaymentDB use seconds
> Various fix and improvements in time/timestamp handling

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/ExtraDirectives.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
Add support for querying a channel information by its `shortChannelId`
> API: support query /channel info by short channel id

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/OldService.scala
- eclair-core/src/main/scala/fr/acinq/eclair/package.scala
This is a regression caused by #971, because `Duration` has a max value of `Long.MaxValue` *nanoseconds*, not *seconds*.
> Fixed overflow issue with max duration

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Auditor.scala
There was actually a change introduced by #944 where we used
`ClosingType.toString` instead of manually defining types, causing a
regression in the audit database.
> Use proper closing type in `ChannelClosed` event

- contrib/eclair-cli.bash-completion
- eclair-core/eclair-cli
This PR updates the bash autocompletition for eclair-cli to suggest all the correct endpoints (updated for the new APIs).
> Update bash autocompletition for eclair-cli

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/ChaCha20Poly1305.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/Noise.scala
- eclair-node/src/main/resources/logback.xml
The wireshark lightning-dissector used a hack to work with eclair: it read our log file in debug mode and parsed the encryptions keys via a very brittle regex. Unfortunately our log format had changed, thus breaking the regex.
The recommended way to integrate with the dissector is to write keys to a log file whenever key rotation happens (see https://github.com/nayutaco/lightning-dissector/blob/master/CONTRIBUTING.md).
This PR adds a new logger dedicated to that task, disabled by default. I also made the necessary changes to the `lightning-dissector` lua plugin and will send a PR upstream once we agree on the eclair changes.
> Wireshark dissector support

- README.md
- eclair-core/src/main/resources/reference.conf
Eclair is now configured to run on mainnet by default.
> Set default chain to "mainnet"

- eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
So that it fails before the ask/api time out.
> Set tcp client timeout to 20s

- .codecov.yml
- .travis.yml
- README.md
- pom.xml
This PR adds support for the scala test coverage tool ([scoverage](http://scoverage.org/)), it will help providing info on how much the coverage changes for each pull request, also a badge indicating the current coverage is added to the readme.
> Add bot support for code coverage (codecov)

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
LND sometimes sends a new signature without any changes, which is a
(harmless) spec violation.
> Accept `commit_sig` without changes

- .codecov.yml
Ignore subprojects *eclair-node* and *eclair-node-gui* when generating a coverage report (codecov).
> Restrict scope of the code coverage report

- eclair-core/pom.xml
- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
Improves the API test to match the ~80% test coverage that we have on eclair, it also add the test-scoped dependency of [mockito](https://github.com/mockito/mockito-scala) to simplify mocking services in the tests.
> Increase Service and EclairImpl test coverage

- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
The way we handle requests to `Switchboard` assume that all children are `Peer`s. This led the `peer` API request to timeout.
> Make `htlc-reaper` a top-level actor

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
Those are not fatal errors for channels.
> Set `handleCommandError` to `WARN`

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ReceivePaymentController.scala
It was obsole since
https://github.com/lightningnetwork/lightning-rfc/commit/068b0bccf94e8cdaf5f298dade0fcc8cc8421ef6.
Note that we use a signed long, but it doesn't matter since 2^64
milli-satoshis is greater than the total number of bitcoins.
> Removed `PaymentRequest.MAX_AMOUNT`

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
`Globals.feeratePerKB` is an [atomic reference initialized to `null`](https://github.com/ACINQ/eclair/blob/master/eclair-core/src/main/scala/fr/acinq/eclair/Globals.scala#L39) and is asynchronously set by the fee provider handler only once the provider is ready. This means that it is possible to retrieve a null object from `feeratePerKB`, scenario that must be handled separately to prevent any issues.
This PR initializes `Globals.feeratePerKB` with the default fee rates retrieved from the configuration file. This makes sure that the node's fee rate is always set to a meaningful value.
> Initialize global feerate with default from conf

- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/ChannelSelectionSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
When relaying a payment, we look in the onion to find the next
`shortChannelId`. But we may choose a different channel (to the same
node), because the requested channel may not have enough balance, of for
some other reasons, as permitted by the spec.
Currently we limit ourselves to only two attempts: one with a
"preferred" channel, and one with the originally requested channel if is
different from the preferred one. This has drawbacks, because if we have
multiple channels to the same node, we may not be able to relay a
payment if the "preferred" channel is currently unavailable (e.g.
because of an htlc in-flight value that is too high).
We now retry as many times as there are available channels, in our order
of preference, and if all fail, then we return a failure message for the …
> Smarter relay logic

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
Instead of going to state `ERR_FUNDING_TIMEOUT`.
This only happens when we are fundee. We *could* have some funds at
stake if there was a non-zero `push_msat`, but we already allows 5 days
for the funding tx to confirm so the best option is probably to forget
about the channel.
> Close channel if funding tx times out

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
This PR enriches the `/payinvoice` and `/sendtonode` API to accept extra parameters for path-finding, now it's possible to specify the `feeThresholdSat` which puts a hard limit on how much the payment route can pay in terms of fees, and `maxFeePct` which is a proportional limit for the fees (note this is ignored if fees are below the threshold). Both parameters are optional and if not specified eclair will use the values from the configuration.
Fixes #1021
> Add feeThresholdSat and maxFeePct parameters to payments API

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/FormParamExtractors.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/NetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestkitBaseClass.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteNetworkDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpecWithLogging.scala
Currently the node address information in `node_announcement` messages is not used when establishing a connection. Peer's addresses are known only when the user initiated the connection providing a destination address, in case of incoming connection the peer's address is blanked out and we can't reconnect. According to the [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-node_announcement-message) the `addresses` field of `node_announcement` should contain the network addresses where a peer expects an incoming connection, this PR leverages this information to provide the following enhancements:
- Connect-to a pubkey (no address specified, will use `node_announcements`)
- Reconnect to peers using their `node_announcements` address as fallback in …
> Peer reconnection address from node announcements

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Auditor.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
If the closing type is known:
- there is no need to watch the funding tx because it has already
been spent and the spending tx has already reached min_depth
- there is no need to attempt to publish transactions for other
type of closes.
> Smarter restore logic for closing channels

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/CommandBuffer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqlitePendingRelayDbSpec.scala
We store `CMD_FULFILL_HTLC`/`CMD_FAIL_HTLC`/`CMD_FAIL_MALFORMED_HTLC` in
a database (see `CommandBuffer`) because we don't want to lose
preimages, or to forget to fail incoming htlcs, which would lead to
unwanted channel closings.
But we currently only clean up this database on success, and because of
the way our watcher works, in a scenario where a downstream channel has
gone to the blockchain, it may send several times the same command. Only
the first one will be acked and cleaned up by the upstream channel,
causing the remaining commands to stay forever in the "pending relay
db".
With this change we clean up the commands when they fail too.
> Clean pending htlcs db

- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/api/JsonSerializersSpec.scala
For ease of use this PR improves the transaction serializer to output the transaction id along with the serialized transaction, previously we outputted only the serialized transaction.
> Output txid and serialized tx in transaction json serializer

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientSpec.scala
This allows getting a transaction id from a short channel id.
Also cleaned up some nit static analyzer warnings.
> Electrum: add id_from_pos

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
Since MAX_PAYMENT_AMOUNT has been removed we may now get payment requests without multiplier which means a whole bitcoin is requested.
> Correctly decode requests without multipliers

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientSpec.scala
To make the response usable, we need to copy the request input (block height and transaction position).
Otherwise an actor receiving the response can't map the received transaction id to a set of short channel ids.
> Electrum: add data to TxIdFromPosResponse.

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
In the event when we receive an unexpected message, the `Peer` was just logging a warning and not sending an `Ack` to the `TransportHandler`. This resulted in a stuck connection, because no more data was read on the connection.
See #1037.
> Ack unhandled lightning messages

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestUtils.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/ChannelSelectionSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/HtlcGenerationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
Currently balances can be obtained from `channels` call but this requires a lot of work on caller side and also some specific knowledge (reserves, commit tx fee, in-flight payments), so this new `balances` endpoint only returns a correct balance info for each channel. 
Data is taken from `Relayer` actor which already has exactly what we need: a map of `OutgoingChannel` objects which now contain correctly calculated `can send / can receive` balances for each `NORMAL` channel. Additionally, obtaining balances this way has a minimal performance hit when compared to querying each channel used in `channels`.
> Add `balances` API endpoint

- pom.xml
This fixes stack overflow error at compile time.
> Added more memory for scoverage

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
Check the `initialblockdownload` flag from `getblockchaininfo` bitcoin RPC during startup, this is an additional check to ensure we're using a fully synced bitcoin instance.
> Enhance bitcoind checks during startup

- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/ChannelSelectionSpec.scala
It is functionnaly the same but it's cleaner and removes the need for
tuples in the success case.
> Use a `RelayResult` class instead of an `Either`

- Dockerfile
- README.md
Add the command line tool `eclair-cli` to the eclair docker image, this will allow users to easily interact with their eclair instance via `docker exec`.
cc: @Kukks
> Add eclair-cli to eclair's docker image

- eclair-core/src/main/scala/fr/acinq/eclair/wire/CommonCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/TlvCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/TlvTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/CommonCodecsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/TlvCodecsSpec.scala
This PR adds support for truncated integers as defined in the spec.
The test vectors are updated to include all test vectors from rusty's spec PR.
It also provides many changes to the tlv and tlv stream classes:
- The tlv trait doesn't need a `type` field, the codec should handle that
- A TLV stream should be scoped to a specific subtrait of `tlv`
- Stream validation is done inside the codec instead of the tlv stream: it makes it more convenient for application layers to create tlv streams and manipulate them
I'm starting a thread on `scodec`'s gitter to see if we can do something better than the `tag` function that encodes the tlv to extract the discriminator, if that yields something I'll update the PR.
> TLV improvements and full spec compatibility

- eclair-core/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
It is better suited for composition of features.
This  paves the way for #1026.
> Replace traits by bitfield for ChannelVersion

- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
This PR fixes bug https://github.com/ACINQ/eclair-mobile/issues/207 which was caused by an incorrect channel cost evaluation against its `htlcMaximumMsat`. The fix is to consider the correct channel cost.
> Use correct cost comparison when evaluating candidate channels

- eclair-core/src/main/scala/fr/acinq/eclair/package.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
Fee check during route computation is:
- fee is below maximum value
- OR fee is below amout * maximum percentage
The second check was buggy and route computation would fail when fees we above maximum value but below maximum percentage of amount being paid.
> Route computation: fix fee check

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
We must consider `nextRemoteCommit` when applicable.
This is a regression caused in #784. The core bug only exists when we
have a pending unacked `commit_sig`, but since we only send the
`AvailableBalanceChanged` event when sending a signature (not when
receiving a revocation), actors relying on this event to know the
current available balance (e.g. the `Relayer`) will have a wrong
value in-between two outgoing sigs.
> Fix regression in `Commitments.availableForSend`

- .travis.yml
We used a mirror in France, which doesn't make sense since Travis builds run on VM in GCP US.
Also upgraded to maven 3.6.2.
> Fix maven mirror

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
https://github.com/lightningnetwork/lightning-rfc/pull/656 introduced invoice feature bits as a pre-requisite for AMP and other advanced payment use-cases.
This spec PR was merged yesterday and lnd and c-lightning have already merged their own implementations.
Getting that out of the way will help make the future AMP implementation PR a bit less daunting ;)
> Implement Bolt 11 invoice feature bits

- Dockerfile
Update the docker build to use maven 3.6.2 and JDK11 base images, fixes #1113.
> Update docker build

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
https://github.com/ACINQ/eclair-mobile/issues/209 mentions that we don't check invoice expiry on the sender side.
I'm adding that check at the http API level, but I think it also needs to be added inside eclair-mobile (which directly uses the Java interface if I'm not mistaken).
> Api: reject expired invoices

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
Instead of satoshi, which could introduce rounding errors.
Also, we check first the balance before the max-inflight amount, because
it makes more sense in terms of error management.
> Check funds in millisatoshi when sending/receiving an HTLC

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedInternalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/RustyTestsSpec.scala
Instead of hardcoding the channel version when we instantiate the
`Commitments` object, we rather define it when the channel is
instantiated. This is saner and prepares future usage.
> Don't hardcode the channel version

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/Sphinx.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/crypto/SphinxSpec.scala
When a downstream node sends us an onion error with an invalid length, we must forward the failure.
The recipient won't be able to extract the error but at least it knows the payment failed.
Fixes #1110 (I'm having a quick look at lnd and c-lightning to see which one has the bug of creating these invalid errors in the first place)
> Sphinx: accept invalid downstream errors

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
Since we can't check if bitcoind is indexing during setup we had a string based match to detect it during the execution. The check occurs only in the `doubleSpent()` call of `BitcoinCoreWallet`, and it's currently not working because the response from bitcoind does **not** contain the word "indexing" anymore [source](https://github.com/bitcoin/bitcoin/blob/v0.18.1/src/rpc/rawtransaction.cpp#L197).
> Update string to match on bitcoind while it's indexing

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
The previous behavior had a poor error response and caused the `Router` to restart which is a performance issue, this PR catches the exception and handles it with the proper `Status.Failure` response.
> Improve error handling for /sendtoroute

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/KeyManager.scala
- eclair-core/src/test/scala/fr/acinq/eclair/crypto/LocalKeyManagerSpec.scala
We currently use 64 bits from the funding pubkey to compute a channel key path made of 4 uint32 values, so the last 2 are always 0. This PR fixes this by using 128 bits instead, and also includes a backward-compatibility check.
> Fix and expand channel keypath

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
Our balance computation was slightly incorrect. If you want to know how much you can send (or receive), you need to take into account the fact that you'll add a new HTLC which adds weight to the commit tx (and thus adds fees).
> Commitments: take HTLC fee into account

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletBasicSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
This PR changes how we select UTXOs when funding transactions, and fixes an issue where trying to use the amount returned by "spend all" with only 1 utxo and a low fee rate would result in an incorrect "insufficient funds" error (see #1146)
> Electrum: improve coin selection (fixes #1146)

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/KeyManager.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/LocalKeyManager.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/crypto/LocalKeyManagerSpec.scala
Our random funding key path is now 8 * 32 bits plus a 1' (funder) or 0' (fundee).
Channel key paths are computed from the sha256 of the funding public key (we take all 256 bits).
> Extend funding key path to 256 bits

- eclair-core/pom.xml
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ExtendedBitcoinClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsBatchValidationSpec.scala
Upgrade the version of bitcoin used in the test, this is preparation work to drop support for bitcoin 0.17. The most notable change is the deprecation of `generate` RPC call which is replaced by `generatetoaddress`, all the test have been updated accordingly.
> Use bitcoin 0.18.1 in the test

- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
We had 2 open PRs, one that added new tests using the 0.API, one that switched to 0.18.1, when they
were merged the new tests failed since they had not been upgraded....
> Upgrade new unit tests to bitcoin 0.18.1 API

- .semaphore/semaphore.yml
We have a few flaky tests that sometimes block the build.
The default expiry in that case is 1 hour, so we pay for a semaphore VM for no reason.
We should fail earlier than that (15 minutes sounds reasonable).
We should also fix the flaky tests, but that's for another PR :innocent:
> Add execution time limit

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala
CRC32C is not available in JDK 7 which we target on Android.
> Use guava to compute CRC32C checksums

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
When sending a payment, if a node on the route answers with an
`UPDATE`-type error, we update our routing table with the new
`channel_update` that is attached to the error message.
But additional routing info (provided by receiver in payment requests)
take precedence over whatever data is in the routing table. If one of
the nodes contained in the routing info replies with a newer
`channel_update`, we will indeed update our routing table, before
retrying, but then we will override it by the (untouched) assisted routes.
We know also update the assisted routes.
> Update assisted channels

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
We now check the loaded configuration for obsolete keys (that have been moved to a new section)
and throw an error if any are found, which will prevent eclair from starting.
> Check configuration for obsolete keys in startup

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/CommitmentSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
Using `.map()` on a `Set` can have surprising results: in our case we end up ignoring htlcs that have the same amount, so the htlc-value-in-flight may be less than what it should be.
Credits to @btcontract for finding the bug (this PR supercedes #1163 because of build issues)
> Fix ignored duplicate amounts in htlc-value-in-flight

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/SynchronizationPipe.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/ChannelSelectionSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
This is a small refactoring of how we handle upstream/origin HTLC.
This is in preparation of Trampoline where we'll add a `NodeRelayed` origin that will contain a list of incoming HTLCs (of potentially only one HTLC if MPP isn't used).
This isn't a very impacting change but doing it on master saves me from painful rebases in my long-lived trampoline branch and will help the review of the trampoline branch (better to separate refactoring from new feature code).
At some point I wanted to remove the distinction between `Origin` and `Upstream`, but the retry logic in HTLC relay requires `Upstream` to contain the whole `UpdateAddHtlc` whereas we want to store something much lighter in the DB (`Origin`).
> Refactor Upstream/Origin

- .codecov.yml
The `ci` tag was unknown to codecov and I suspect that's why they weren't honoring the `ignore` on eclair-node and GUI.
I also changed our target range to 70-90% (impacts the colors of the badge, it's nit).
> Fix codecov unknown tag

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
Add a simple API that calls `getfinaladdress` on EclairWallet, this can be used to obtain a new on-chain deposit address from your bitcoin-core wallet. Fixes #1006
> Add 'getnewaddress' API

- eclair-core/src/main/scala/fr/acinq/eclair/PimpKamon.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BatchingBitcoinJsonRPCClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
This adds metrics on bitcoin rpc calls and on scodec.
> More metrics

- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/PaymentHandler.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
It was only working with one custom receive handler, but what we really want is the ability to stack multiple handlers.
> Fixed composition of receive handlers

- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/PaymentHandler.scala
When an actor sends a message to itself as part of its class definition,
there is no guarantee that this message will be processed first. Relying
on that to set the default payment handler is problematic and causes
race conditions in tests.
> Fixed race condition in payment handler init

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
This is due to a callback being executed after the parent actor has been
cleaned up. We don't really care about the result anyway, so we can
safely ignore, even if the issue only arises in tests.
The root problem here is that we are making references to actor methods
from a callback, which we shouldn't do, because whatever we reference
may have disappeared by the time the callback tries to access it. A
better pattern would be to `pipe` the results of the `Future` to
oneself, but that would require more work and possibly change the FSM,
which seems overkill for the issue at hand.
> Ignore NPE in tests

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
#1160 updated netty, and `ElectrumClient` now uses `TLSv1.3` when using the custom electrum server feature. However mobile devices may not support TLS 1.3 (for android, only from 10/API 29):
- https://developer.android.com/reference/javax/net/ssl/SSLContext.html
- https://developer.android.com/about/versions/10/features
As such trying to enable `TLSv1.3` in `ElectrumClient` raises an exception on older Android. It does not gracefully fallback to `TLSv1.2` as was expected.
This PR fixes that by checking support beforehand.
> Check TLS version support in ElectrumClient

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
I found a few things than can be improved in the MPP retry behavior.
Those will be particularly helpful for Trampoline-MPP to a remote peer (take into account the fact that a Trampoline node will likely have many channels).
It doesn't make any sense to let the `PaymentLifecycle` retry when we're forcing the choice of the first hop and the recipient is on the other end of that channel.
This is fixed by setting `maxAttempts=1` when sending child payments via direct channels to the recipient.
When the recipient isn't a direct peer, it's very unlikely that choosing a route prefix with an unannounced channel will succeed. Most unannounced channels Endurance/Horizon has are with mobile wallets. We ignore them when sending to remote nodes.
We're choosing the first hop without looking at the …
> MPP routing improvements

- eclair-core/src/main/scala/fr/acinq/eclair/PimpKamon.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-node/src/main/resources/application.conf
This includes a bit of refactoring in `MultiPartPaymentLifecycle`. Note
that we can't use the `onTermination` handler to finish the spans,
because it is asynchronous and may not be called after a long time.
That's why we use a dedicated `myStop` function.
In Kamon 2.0, by default spans are automatically generated for tracked
actors, which we don't want because we define our own spans. That's why
there is an additional configuration in `application.conf`.
> Improved tracing of single/multi-part payments

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartPaymentFSM.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/PaymentHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/CommandBuffer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/RustyTestsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/HtlcReaperSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentFSMSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
We previously had some logic where we would fail incoming HTLCs
for which we were the final recipient when a channel would come online.
That made sense when we didn't have MPP, but with MPP we cannot do that.
There is a risk that we would be failing HTLCs that are considered received by the MPP FSM.
Instead we need to use the CommandBuffer when we are the final recipient.
This way pending commands cannot be lost and HTLCs are cleaned-up on restart.
> Fix MPP post-restart HTLC clean-up

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/Onion.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
MPP implies payment secret.
Payment secret feature implies that there actually is a payment secret in the invoice.
It's still a bit awkward to use because `paymentSecret` still has to be an `Option`.
It's safe to call `.get` when `features.allowPaymentSecret` but it's not enforced by the type system.
Can we make this better at the type level without making the `PaymentRequest` unnecessarily complex?
> Avoid incoherent payment request features.

- eclair-core/src/main/scala/fr/acinq/eclair/wire/Onion.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/TlvCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/OnionCodecsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/TlvCodecsSpec.scala
The spec defines tu64 (and friends) without the length prefix.
Multi-part uses a tu64 without a length prefix inside the PaymentData record.
Our previous implementation only supported using tu64 alone in a TLV record.
We make this more flexible by separating the length encoding.
> Rework truncated integers codecs

- eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqlitePaymentsDbSpec.scala
This PR add a method to get a high level/high performance overview of the payments from the payment database.
The `PaymentDb` interface is impacted to add two objects: `PlainIncomingPayment` and `PlainOutgoingPayment`. These objects only contains the most basic data about the payments. 
Notably, the payment request attribute in these object is the raw serialized value stored in the DB which helps with performances on Android. Two methods have been added to the `PaymentRequest` object to allow for the fast reading of a serialized payment request's description and expiry.
This PR supercedes #1169
> High level payments overview method

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
If a chain re-org happens and a new ShortChannelId is assigned,
the `Relayer` kept both entries (new and old).
This resulted in an incorrect balance because we effectively counted this channel twice.
> Handle chain re-org in balance computation

- eclair-core/src/main/scala/fr/acinq/eclair/Logs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Server.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/ForwardHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartPaymentFSM.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/PaymentHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/resources/logback-test.xml
- eclair-core/src/test/scala/fr/acinq/eclair/TestUtils.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentHandlerSpec.scala
- eclair-node/src/main/resources/logback.xml
- eclair-node/src/main/resources/logback_colors.xml
Filtering by package is sometimes not enough because some events (e.g. routing table sync) spans over multiple packages.
> Added a 'category' in logs

- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePaymentsDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqlitePaymentsDbSpec.scala
Payments overview aggregates outgoing payments by `parent_id` using a `group by`. If there are several attempts, there is no guarantee that the output aggregated payment will hold the most recent/pertinent status.
See SQLite doc on bare columns in aggregate queries: https://www.sqlite.org/lang_select.html#bareagg
By using the `max` function we can force the aggregate output to be the most recent attempt.
> Fix outgoing payments order in payments overview

- eclair-node/src/main/resources/application.conf
This allows us to only use logback.xml to control the log level.
From akka docs [1]:
> If you set the loglevel to a higher level than DEBUG, any DEBUG events
will be filtered out already at the source and will never reach the
logging backend, regardless of how the backend is configured.
> You can enable DEBUG level for akka.loglevel and control the actual
level in the SLF4J backend without any significant overhead, also for
production.
[1] https://doc.akka.io/docs/akka/current/logging.html
> Set `akka.loglevel` to `DEBUG`

- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
We can't guarantee with the current algorithm that the last HTLC won't be
a small one (the leftovers).
If we see that happen in real scenario, we'll need to add heuristics to avoid it.
> Fix MPP flaky test

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/EarnDotComFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FallbackFeeProvider.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/EarnDotComFeeProviderSpec.scala
We configure a timeout of 5 seconds, applicable to all fee providers. If a provider times out we switch to the next one in our list.
Our mobile app needs a feerate to start properly and currently waits too long when a fee provider is online but very slow to respond.
> Add a configurable time-out to onchain fee provider requests

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
This message is sent by the `Peer` in answer to a `Peer.Disconnect` command.
> Minor: ignore "disconnecting" message in Channel

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
Randomization is necessary, otherwise if two peers attempt to reconnect
to each other in a synchronized fashion, they will enter in a
disconnect-reconnect loop.
We already had randomization for the initial reconnection attempt, but
further reconnection attempts were using a deterministic schedule
following an exponential backoff curve.
Fixes #1238.
> Better randomization of reconnection delay

- eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala
This pull request fixes an issue where creating concurrent database connection could deadlock.
An exclusive lock was added to `eclair.sqlite` to prevent running several instances of eclair using the same sqlite database. The code obtaining the exclusive lock is a succession of [three SQL queries](https://github.com/ACINQ/eclair/blob/synchronized-exclusive-lock/eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteUtils.scala#L102-L108), and is not thread-safe. If two threads try to obtain the lock at the same time, none of these locks will succeed, and subsequent locks will fail because the database is deadlocked.
This can happen on the eclair mobile application where several background jobs (that need exclusive lock on the `eclair.sqlite` db) may be launched at the exact same time …
> Add synchronization when locking database connection

- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/CommandBuffer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/CommandCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/CommandCodecsSpec.scala
Add type with upper bound to make `asInstanceOf` unnecessary.
Split `HasHtlcId` from `Command`: they are orthogonal traits.
> Improve CommandSend type

- TOR.md
*.tor.auth defaults to password and cookie auth folks may not notice without log crawling.
> Added some instructions for TOR auth

- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
Mockito sometimes throws an unnecessary stubbing exception.
I wasn't able to reproduce it frequently enough to troubleshoot
and it doesn't provide enough data for investigation.
I chose to re-write the tests without mockito to make them more flexible.
In case they randomly fail we should hopefully get more useful data
to help troubleshooting.
> Remove mockito from switchboard tests

- eclair-core/src/main/scala/fr/acinq/eclair/JsonSerializers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/JsonSerializersSpec.scala
We now use tx id instead of tx hash, so it can be copy/pasted into an explorer.
> Fix Outpoint JSON serialization

- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
This is safer for now since the splitting algorithm isn't working
well on nodes with a large number of channels and we don't
expect too many payments from Phoenix to non-Phoenix to
actually need MPP in the short term.
> Disable Trampoline-MPP to non-Phoenix recipients

- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ExtendedQueriesCodecsSpec.scala
For compatibility with c-lightning & lnd.
This is a simpler alternative to #1275.
> Always encode empty list of scids as uncompressed

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/ShortChannelId.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RoutingSyncSpec.scala
We currently split in fixed-size chunks, which means that channel ids with the same block height may end up in different replies. Though this is not explicitly forbidden in the specs, it is implicitly required otherwise it becomes difficult to know when you've received all the replies you asked for and send another query.
> Fix how we split channel ids in channel queries

- pom.xml
It exposes an API that we need if we want to implement lnurl
> Dependencies: use bitcoin-lib 0.17

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
We currently only print the exception, but don't explain the context.
Closes #1281
> Improve error message when invalid funding tx

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
Otherwise eclair-mobile can't pay using MPP.
This heuristic was only here to help Trampoline nodes with a lot of
channels relay using MPP, but we disabled that in #1271 anyway.
We will reactivate Trampoline-MPP once split is done inside the router.
> MPP: allow using unannounced channels

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala
lnd expects ids ranges in reply_channel_range messages to strictly follow each other, without gaps.
For example, using block heights and not ids, [1,2,4,5] would be split into (first=1, num=2, [1,2]) :: (first=3, num=2, [4, 5])
This is arguably a limitation of lnd (c-lightning does not requires this and it's not needed to properly process replies) but is easy to implement.
> Make sure that ids chunks strictly cover the requested range, without gaps

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
The error message produced now provides the user with a solution.  Of course it's temporary until they receive another non-segwit UTXO.
> Better Non-segwit UTXOs assert message.

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/InitTlv.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/TlvTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala
Implement https://github.com/lightningnetwork/lightning-rfc/pull/682
This is a good opportunity to setup the infrastructure for a TLV stream in the Init message, which we can leverage for optional, un-speced features.
> Add networks to init message

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
If our initial random deconnnection delay is 0 (unlikely but possible) then all "exponential backoff" reconnection delays will be 0 too, so we set a minimum value of 200 milliseconds.
> Peer: use a minimum reconnection delay of 200 ms

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/FailureMessage.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/FailureMessageCodecsSpec.scala
We add new errors that let senders know they need to raise the trampoline fee/ctlv.
When the error is downstream, we select the best error to forward.
> Improve NodeRelayer errors

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
When paying an invoice, we weren't properly checking our own features.
If the invoice supported MPP, we would use it all the time.
If MPP isn't enabled in our features, we now default to a legacy payment.
> Allow deactivating MPP

- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala
c-lightning fails to decode empty arrays of scids or timestamps with an encoding type set to COMPRESSED_ZLIB.
The spec is not specific enough on whether this is valid or not, so we'll set the encoding type of empty arrays to UNCOMPRESSED.
This is PR supersedes #1280
> Channel queries: Encode empty arrays as UNCOMPRESSED

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
There was a rounding issue with the availableForSend/Receive calculation.
Because CommitTx fee and Htlc fee were computed separately,
but each was individually rounded down to Satoshis, we could
end up with an off-by-one error.
This resulted in an incapacity to send/receive the maximum amount available.
We now allow computing fees in msat, which removes rounding issues.
> Fix availableForSend/Receive

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
It would be great if I could connect the Eclair mobile wallet to my Tor only electrs server using Orbot. Sadly I can't because it requires a valid SSL certificate. Please make an exception if the custom Electrum server address is an onion domain.
As suggested from others in my initial PR https://github.com/ACINQ/eclair-mobile/pull/229, I created this PR to cover up eclair-core and not only eclair-mobile.
> Turn off SSL when custom Electrum server address is a hidden service

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/ChannelsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteChannelsDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteChannelsDbSpec.scala
The old name (addOrUpdateHtlcInfo) was misleading.
This method only adds, and can even handle adding duplicate lines.
Closes #1233
> Clarify ChannelsDb htlc info method

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/OpenTlv.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/LightningMessageCodecsSpec.scala
We don't implement the `upfront_shutdown_script` feature yet.
However we update our encoding to always specify its field and support reading it.
This allows extending `OpenChannel`/`AcceptChannel` with tlv streams while staying compliant with the spec and other implementations (lnd just started to add the `upfront_shutdown_script` field to their `OpenChannel` message, even if we don't activate the feature bit).
There is one caveat: Phoenix shipped with a version that's incompatible because it interprets the `upfront_shutdown_script` fields as a TLV stream.
So we use a workaround to identify unpatched Phoenix versions and send them the old encoding.
This PR can be applied and deployed safely today.
Once Phoenix is upgraded with that code in the next release, and enough users have updated, …
> UpfrontShutdownScript field

- BUILD.md
- eclair-core/pom.xml
- pom.xml
This PR adds support for deterministic builds of the eclair-core artifact by updating the necessary maven plugins (maven-source-plugin and maven-jar-plugin) to version 3.2.0 which support deterministic builds and hardcoding the property `project.build.outputTimestamp` to a fixed date (this can be updated at each release) . The deterministic build only works with the submodule `eclair-core` due to some quirks with the maven-capsule plugin, also the build is *not* deterministic across different OSs because of the way maven packages files with system-dependent newline markers. The SHA256 of eclair core at commit 93c2683 is: `db3064fc4fc9e20c141770294186fbb82b50190ffc13f6bcc09379db2fb33b2b`. 
This is a first step toward deterministic builds for the mobile apps.
> Support deterministic build of eclair-core artifact on ubuntu

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
Update the API to allow users to easily use MPP and/or Trampoline.
Note that the second commit is completely unrelated: it fixes a small race condition in an E2E test and adds debug output (see commit message).
> Trampoline/MPP API changes

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
Handle correctly the case where the remote peer force-closed,
and afterwards we received a preimage from downstream for
an HTLC in this channel.
> Fix force-close next commit then fulfill

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala
Watcher now handles WatchConfirmed watches where min depth is set to 0: the watch event will sent when the tx enters the mempool
> Electrum: allow watcher to watch for mempool transactions

- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
The DB ordering is not deterministic.
For multi-part payments, the first timestamp is taken.
This can vary depending on which record is listed first.
Using the same timestamp avoids a failed assertion.
> Fix AuditDb flaky test

- eclair-core/src/main/scala/fr/acinq/eclair/crypto/ChaCha20Poly1305.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
- eclair-core/src/test/scala/fr/acinq/eclair/crypto/ChaCha20Poly1305Spec.scala
We currently rely on `require`, which is convenient, but doesn't allow
fine-grained exception control.
Also, in case of errors, logging is done at the supervisor level, where
we lose the remote `node_id`.
Instead, we type some crypto-related errors and log them in the
`TransportHandler`, which already has the correct MDC.
> Better logging for transport handler

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
networkstats API call failing in 0.3.3 due to change in Router API.
Tests miss this as Router is Mocked...
> Fix for change in Router API

- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentError.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
These two commits are best reviewed individually.
`06faa52` is a small refactoring of payment errors to make it simpler for Phoenix/Eclair-Mobile to classify errors.
`2e48792` is an improvement for trampoline HTLC fulfills.
We were previously waiting for the whole downstream payment to be settled (all individual HTLCs).
We can do better and fulfill upstream as soon as we get the preimage (which only needs one downstream fulfill).
> Node relayer faster fulfill

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClientPool.scala
We use the same socks5 proxy that is optionally enabled in the configuration and is typically used to connect to LN nodes running as TOR hidden services.
This will allow eclair:
- to connect to .onion Electrum servers running behind TOR
- to connect to regular Electrum servers through TOR
> Electrum: add support for socks5 proxies

- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
Writing the PaymentRelayed event to the DB is not atomic.
Each part is written independently of the others (one row per part).
This is fine as nothing relies on this event being written atomically.
However tests were expecting that and we would observe rare test failures on travis.
> Fix random trampoline test failure

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
SendToRoute previously didn't accept invoice routing hints.
This was a limitation when paying a wallet invoice.
Invoice hints are now correctly taken into account.
> SendToRoute with routing hints

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
Currently, those methods throw exceptions, and we rely on `Channel` to
call them within a `Try(...)`. It puts more burden on `Channel` and
isn't very functional.
Some methods were returning an `Either[]`, which seem to play the role
of a `Try` but isn't used. It seems the idea was to not fail the channel
upon receiving a `fulfill`/`fail` for an unknown htlc, but it is not
fully wired, and isn't compliant (BOLT 2):
> A receiving node:
> if the id does not correspond to an HTLC in its current commitment
transaction:
>    MUST fail the channel.
For signature-related methods, I went with the minimal change of
encapsulating portions of the code inside a `Try {...}` to minimize risk
of regression. We could also make `CommitmentSpec` methods return
`Try[]` but I suspect that would be more …
> make Commitments method return Try[]

- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartPaymentFSM.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentFSMSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
Add an abstraction of a PaymentPart.
Remove unnecessary intermediary case classes.
This allows extending how payment parts can be received.
It's not limited to HTLCs (could be swaps, pay-to-opens, etc).
@araspitzu you also mentioned a missing abstraction necessary for hodl invoice, can you detail? Maybe this is the right PR to also add something like this.
> Refactor MultiPartPaymentFSM

- README.md
- eclair-node/pom.xml
- eclair-node/src/main/scala/fr/acinq/eclair/Plugin.scala
~~This PR rewords the way we load plugins providing a stricter and safer way to load them. We now require plugins to exhibit a MANIFEST file with some well defined entries:~~
~~- `Main-Class` to identify the plugin entry point ( class implementing `Plugin`)~~
~~- `X-Eclair-Supported-Versions` contains a list of all supported eclair version~~
~~The `Main-Class` is mainly used to load the plugin without scanning using `org.clapper.classutils`, this allows us to avoid an illegal reflective call during startup. The list of supported version allows us to check if the plugin we're loading supports the current version of eclair, this prevents from running outdated (and incompatible) plugins.~~
This PR slightly reworks the way we load plugins to avoid doing an illegal reflective call. Instead of …
> Avoid illegal reflective operation during startup

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
As long as we receive messages from our peer, we consider it is
online and don't send ping requests. If we don't hear from the
peer, we send pings and expect timely answers, otherwise we'll
close the connection.
This is implemented by scheduling a ping request every 30 seconds,
and pushing it back every time we receive a message from the peer.
> Send ping if no message received from peer for 30s

- eclair-node-gui/src/main/resources/eclair-node-gui.sh
- eclair-node/pom.xml
- eclair-node/src/main/resources/eclair-node.sh
NB: using `addJava "-javaagent:$lib_dir/kanela-agent-*.jar"` in scripts
to make them update proof doesn't work unfortunately.
> Kanela-agent 1.0.1->1.0.5

- README.md
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
In this PR we force the usage of the default bitcoind wallet (named ""). This is necessary to allow the user to have multiple bitcoind wallets because when there are more than one we need to specify which wallet to use in the RPC calls. Fixes #1330.
Note for reviewers: the extra path in the bitcoin RPC URL identifies the wallet to be used and can be used in all the others RPC too. By default bitcoind has an unnamed wallet `""` and eclair always expect to have that, users can add new wallets but should never rename or remove the default wallet (maybe we can add a few lines in the README for this).
> Allow users to have multiple wallets in bitcoind

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-node/src/test/resources/api/getinfo
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
This PR adds some extra information in the `/getinfo` API response such as version, color and features, the version string uses a truncated commit and is also used to _log_ the version during boot.
> Add more information to GetInfoResponse

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
Previous implementation in #1317 wasn't working because of a bug in the
transition. Added a test and fixed it.
cc @t-bast @btcontract
> Re-send ChannelUpdate on reconnection (vol 2)

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
See https://github.com/lightningnetwork/lightning-rfc/issues/728 and https://github.com/lightningnetwork/lightning-rfc/pull/740.
Add an additional reserve on the funder to prevent emptying and then being stuck with an unusable channel.
As fundee we don't verify funders comply with that change.
We may enforce it in the future when we're confident the network as a whole enforces that.
Note that c-lightning has already implemented the same logic. We can merge this regardless of spec inclusion as a safety measure for our nodes (and I think we should). The spec may bikeshed some details (like the factor) which we can update later.
@pm47 this is now ready for review.
> Funder reserve for future fee increase

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BatchingClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/main/scala/fr/acinq/eclair/tor/TorProtocolHandler.scala
Also removed string interpolation for some of the more expensive debug
lines. It's a trade-off performance vs readability and is probably not
worth changing for info level logs, which will be enabled anyway.
NB: for grizzled logging (used e.g. in Noise/Chacha20Poly1305), there is apparently no performance impact with using string interpolation on debug lines, because the arg of `debug()` is a function, not a String, meaning that nothing will be executed if log level is greater than DEBUG. I tested to make sure. From their [website](http://software.clapper.org/grizzled-slf4j/): 
```
It’s simpler to use than direct SLF4J, primarily because it uses Scala’s call-by-name magic so that you can use make logger calls easily, without incurring any overhead.
For example, the various logging methods …
```
> Minor: Reduced some log levels

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
We were allowing users to set htlc-minimum-msat to 0, which directly
contradicts the fact that we must never send an HTLC for 0 msat.
We now explicitly disallow that behavior: the minimum is 1 msat.
In case the remote side of a channel had set its htlc-minimum-msat to 0,
we would forward HTLC with a value of 0 msat if a sender crafted such a
payment. The spec disallows that, so we now explicitly check for that
lower bound.
> Harden requirements on htlc-minimum-msat

- eclair-core/src/main/scala/fr/acinq/eclair/PimpKamon.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BatchingBitcoinJsonRPCClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Authenticator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Server.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Auditor.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/Monitoring.scala
Centralize metrics to avoid bloating the business logic (some metrics were unused, like `peers.count`).
This is a first step before adding new metrics and extend existing ones to provide more alerting capabilities (in follow-up PRs).
> Centralize metrics per package

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/ExtendedBitcoinClient.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestBitcoinClient.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsBatchValidationSpec.scala
Replace the usage of `String` with the more precise `ByteVector32`
> Use correct type for parameters in ExtendedBitcoinClient

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/Onion.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/TlvCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/OnionCodecsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/TlvCodecsSpec.scala
This PR adds the possibility to attach extra TLV records when sending a payment, the feature is meant to be used by plugin developers and experimentally via API (although this PR is missing the API part). It will allow to support features like `keysend` (invoiceless payments) and/or custom messages attached as TLV record to final onion packet.
I've chosen to not support this feature in trampoline/mpp payments for the moment because i'm not aware of any custom protocol built on top them. 
Users willing to experiment with this feature must take care of properly sorting the extra TLV records.
> Support additional TLV records in SendPayentRequest

- eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala
If our latest successful connection attempt was less
than 30 seconds ago, we pick up the exponential
back-off retry delay where we left it. The
goal is to address cases where the reconnection
is successful, but we are disconnected right away.
> Do not reconnect immediately if we keep getting disconnected

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala
Track all channel states (cardinality shouldn't be too high).
Prevent duplicate transitions that messed up the gauge.
Also the `withoutTags` in the ctor wasn't such a good idea.
It's better to explicitly track each state with its own tag.
> Better tracking of channels count metric

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
Revert #1278. The correct way to handle that is to add more ways for
users to choose their SSL behavior in phoenix/eclair-mobile.
In the long run it will be via more checkboxes / a better configuration
panel, but at first it can simply be moving #1278's logic directly in both
Phoenix and eclair-mobile (which is done in https://github.com/ACINQ/phoenix/pull/53 and https://github.com/ACINQ/eclair-mobile/pull/242).
> Revert Electrum Tor disable SSL

- eclair-node/src/test/resources/logback-test.xml
Otherwise we use the default logback.xml file which writes to a
rolling file in the user directory.
NB: when enabling console logging, there are a lot of WARN outputs. Maybe something to look into @araspitzu?
```shell
10:37:33.657 WARN  ActorSystemImpl - withRequestTimeout was used in route however no request-timeout is set!
10:37:33.657 WARN  ActorSystemImpl - withRequestTimeoutResponse was used in route however no request-timeout is set!
10:37:33.683 WARN  ActorSystemImpl - withRequestTimeout was used in route however no request-timeout is set!
10:37:33.683 WARN  ActorSystemImpl - withRequestTimeoutResponse was used in route however no request-timeout is set!         
```
> Add logback config for eclair-node tests

- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
In case a channel has been pruned, and we receive a recent update, we
"unprune" it and immediately request the channel announcement again
(which will cause us to revalidate it). We also discard the update,
assuming that we will receive it again with the channel announcement.
We were using a `GossipDecision.Duplicate` rejection for the channel
update, which is inaccurate. This PR introduces a new
`GossipDecision.RelatedChannelPruned`.
> Add a rejection for update when channel is pruned

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
We update transaction fees at every block (ie every 10 minutes). While this works well when the remote peer is a node that's online for more than 10 minutes, it's an issue for mobile wallets that usually come online for a few minutes and then disconnect.
We want to make sure we send these wallet peers an update_fee when one is needed, so we now check for feerate updates on reconnection.
Fixes #1381.
> Send `update_fee` on reconnection

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
Transaction generation functions used to throw exceptions.
We have a perfectly good `TxGenerationSkipped` type to express potential errors,
so these functions should return an Either to make the contract explicit.
I also did some formatting clean-up in `Helpers`.
If that covid confinement keeps going for too long, I'm pretty sure I'll end up spending more time finding the right memes to go in my PR descriptions than doing the actual code...
> Refactor transaction generation errors

- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
When switching to a new connection while already connected, peer
immediately kills the current connection and sends back the
`PeerConnection.ConnectionReady` to itself. Since #1379, the sender of
this message is assumed to be the `PeerConnection` actor. If peer
doesn't preserve the sender by using a `forward` instead of a `tell`, it
will assume that itself is the `PeerConnection`, which will break
everything.
> fixup! Use sender instead of providing actor refs (#1379)

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteNetworkDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Autoprobe.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteNetworkDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/ChannelRangeQueriesSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/NetworkStatsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RoutingSyncSpec.scala
This is a first step towards more changes to the router/path-finding.
It makes sense for the router to know about channel balances when looking for routes, especially for MPP.
This PR only adds a listener on `AvailableBalanceChanged` and tracks local channel balance in the router's internal maps. The next step will be to add this information to the graph edges. It will also be a good occasion to use the channel `capacity` instead of `htlcMaximumMsat` inside edges; we'll be able to provide more information to the path-finding algorithm.
> Router channel balance

- .travis.yml
- eclair-core/pom.xml
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/package.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ExtendedBitcoinClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitcoinCoreFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/ChannelSelectionSpec.scala
- eclair-node-gui/pom.xml
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/IndexedObservableList.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/utils/QRCodeUtils.scala
- eclair-node/pom.xml
- pom.xml
This builds on #1389, so the changeset is minimal (disregard the first commit).
Main changes:
- relaxed compiler parameters to minimize impact (e.g. allow
deprecated features)
- `scala.collection.JavaConverters` -> `scala.jdk.CollectionConverters`
- `MultiMap` -> `MultiDict`
Compilation is 25% faster on my machine, compiler is a bit more strict
(it found an "invalid comparison" bug).
> Update to scala 2.13 and akka 2.6 (incremental)

- README.md
- eclair-core/pom.xml
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
Update our regtests to use bitcoin-0.19.1, the most notable changes in this release are about fees (especially the CPFP-carve out rule for the dual-anchor commitment format). There are also some RPC changes: the `fundrawtransaction` RPC does not fail when providing a too little feerate but instead bitcoin will fail when broadcasting the transaction with `sendrawtransaction`, the error message is also changed.
I replaced the URLs for our bitcoin-core test instance with bitcoincore.org which is quite faster than bitcoin.org
> Support bitcoin-0.19.1

- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/WatcherSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ExtendedBitcoinClientSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
Instead of waiting for htlc-success txs to be confirmed, eclair also looks at mempool txs to detect preimages as soon as possible.
This has been the case for a very long time, but our integration tests didn't showcase this correctly.
> Test preimage extraction from mempool

- .semaphore/semaphore.yml
- .travis.yml
- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
We've been witnessing random test suites freezes (since ages).
We've observed that when these freezes happen, there are usually a lot of "too many open files" errors raised by the OS.
The backup handler is a likely culprit as the IntegrationSpec is running multiple nodes and exchanging HTLCs at a fast rate.
At least it won't hurt disabling it in tests, and will speed up the test suite.
> Disable backup handler in tests

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelExceptions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
I'd like to get these two simple fixes in the 0.4.0 release as well.
The first commit validates channel announcement signatures in the channel, before it reaches the router; it makes the flow a bit simpler. See the commit message for details.
The second commit is just a variable rename. The fact that it was called `ok` was quite misleading to readers.
> Validate `channel_announcement` sigs early

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
In some cases, funding a tx will work but publishing it may fail (because mempool fees are not met for example). In that case we need to make sure that the tx inputs, which were locked by `fundrawtransaction`, are unlocked.
> Unlock transaction inputs if tx cannot be published

- eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala
This prevents unnecessary warnings to clog up the logs.
> Minor: catch harmless unhandled events

- BUILD.md
when rebuild on different branches, build errors will occur if files are not cleaned
> mvn add note about clean argument

- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
This is a step towards more flexibility for path-finding in the router.
I started wanting to simply add support for channel balance, but as I dived into the code I couldn't help myself and refactored, renamed, improved documentation and fixed some weirdness that I stumbled upon.
I hope the resulting code is easier to read and reason about, but I'm obviously biased so let me know how I can improve.
I split that work into three commits; it may help to review commit-by-commit, or to look at the resulting code instead of looking at the diff.
If you're not familiar with Yen's algorithm, [the example on the wikipedia page](https://en.wikipedia.org/wiki/Yen%27s_algorithm#Example) should make it easy to understand.
The [first commit](https://github.com/ACINQ/eclair/commit/54af0b3544ecf09324b2e3eca …
> Use channel balance in path-finding

- eclair-core/src/main/scala/fr/acinq/eclair/PimpKamon.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqlitePaymentsDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
This is a necessary refactoring prior to MPP v2.
The two commits can be reviewed separately.
This commit extracts the logic of deciding which nodes/channels to ignore in a payment retry.
We enrich the `LocalFailure` so that this can be completely decided by only looking at the generated failures.
The next version of the MultiPartPaymentLifecycle will use these new helpers to ignore faulty nodes/channels from potentially multiple failed partial payments.
It was useless to return `ignoreNodes` and `ignoreChannels` in `RouteResponse`, it's rather the responsibility of the caller (`PaymentLifecycle` and later `MultiPartPaymentLifecycle`) to store and update these sets.
Preparing for the MPP move inside the router, we introduce a `Route` class and let `RouteResponse` return a collection of …
> Payment lifecycle refactor

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FallbackFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeProvider.scala
- Use ConstantFeeProvider only on regtest: it doesn't make sense to fallback to hardcoded feerates on testnet/mainnet, better to stick with the one we previously used
- Fail bootstrap if we cannot retrieve feerates: this will prevent some unnecessary channel closing when starting eclair-mobile with a crappy connection
- Increase feerate providers timeout: 5 seconds was a bit aggressive for mobile connections
> Feerate provider improvements

- BUILD.md
- eclair-core/pom.xml
- pom.xml
Some plugins are only used for tests, like the `download-bitcoind` plugin, tasked with downloading bitcoin-core. Skipping these plugins can save some time especially when we only want to build the library.
Note that this is only used when using the `-Dmaven.test.skip=true` option. `-DskipTests` only skip the test running phase, but still compiles the tests which also takes time.
Impact on my machine:
```shell
[INFO] eclair-core_2.13 ................................... SUCCESS [02:25 min]
[INFO] eclair-core_2.13 ................................... SUCCESS [01:23 min]
```
> Skip executing some plugins when skipping tests

- eclair-node-gui/src/main/resources/eclair-node-gui.sh
- eclair-node/src/main/resources/eclair-node.sh
Update the unix launcher scripts to use the _shebang_ in the first line of the file, as expected by most unix-based systems. Fixes #1422 and #1416
> Use shebang in first line of launcher scripts

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/JavafxBoot.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
- eclair-node/src/main/resources/application.conf
- eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala
This seems to be recommended practice:
https://doc.akka.io/docs/akka/current/general/actor-systems.html#configuration-container.
As a nice side effect, it allows putting akka-related config in eclair.conf.
> Use actor system as conf container

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/TransportHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
Both `Client` and `TransportHandler` were watching the connection actor,
which resulted in undeterministic behavior during termination of
`PeerConnection`.
We now always return a message when a connection fails during
authentication.
Took the opportunity to add more typing (insert
deathtoallthestring.jpg).
> Fix race condition on early connection failure

- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
I've been doing a lot of performance tests on the mainnet graph for the MPP split v2 work, and was wondering if the Scala 2.13 collections performance improvement was noticeable.
Good news: it is! On my laptop, switching to Scala's `HashMap` and `PriorityQueue` yields a consistent 10% performance increase compared to `java.util.HashMap` and the `FibonacciHeap` we were using.
However, merging this would make the merge more painful for android, as on android we still need to use the old collections. So I split the PR into two commits:
- the first one makes the merge to android *easier*, because `ArrayDeque` was not available on Scala 2.11 -> we should definitely apply this one (it's not a hot code-path, the standard `Queue` will not be a bottleneck)
- the second one makes the merge *harder* …
> Path finding standard collections

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
Move the maximum fee computation outside of `findRoute`: this should be done earlier in the payment pipeline if we want to allow accurate fee control for MPP retries.
Right now MPP uses approximations when retrying which can lead to payments that exceed the maximum configured fees. This is a first step towards ensuring that this situation cannot happen anymore.
The way it will work for MPP split v2 is that the MultiPartPaymentLifecycle will compute the total fee budget for that payment request, and when partial payments fail it will be able to compute the available fee budget by subtracting the fees of the pending parts.
I also took this opportunity to slightly refactor `findRoute` to return all the routes it finds instead of selecting only the first one. This way `findRoute` can be used …
> Compute max fee before route calculation

- eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
We were incorrectly resetting channel balances to `None` when announcing a new channel.
> Correctly set new channel balance

- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/GraphSpec.scala
Light clients don't always validate channels by fetching the blockchain tx.
That means they don't have access to the exact capacity.
When that happens, we should fallback to `htlc_maximum_msat` if available, or to a default capacity (otherwise path-finding will ignore these edges).
> Fix edges with empty capacity in the routing graph

- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
It should return stats for all channels (funder and fundee).
The previous code was incorrectly filtering on channels for which we paid
an on-chain fees, excluding the channels for which we were fundee.
Fixes #1449.
> Fix channelstats API

- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
We go to the `CLOSING` if and only if the funding tx has been spent by
one transaction. The `require` is absolutely necessary. We could
probably enforce this constraint at the compilation level by more clever
typing but that's another matter.
> Put back DATA_CLOSING constraints

- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/EclairWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWallet.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumEclairWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/TestWallet.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoinCoreWalletSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
This is a collection of independent commits.
The goal is to add some basic on-chain APIs (that simply forward to Bitcoin Core) to provide a good integration into [RTL](https://github.com/Ride-The-Lightning/RTL).
We clearly don't want eclair to become a wallet for bitcoin core, but adding basic pass-through APIs can be useful for end-users.
Fixes #1457, #1458 and #1459.
> Add on-chain APIs

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Graph.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
Don't be fooled by the relative simplicity of the code, it took me many iterations to get it to that state, every small detail/heuristic plays an important role!
At first I wanted really hard to use [Ford-Fulkerson](https://en.wikipedia.org/wiki/Ford%E2%80%93Fulkerson_algorithm). I'm convinced that finding a good way to split the payment is a circulation problem. But the devil lies in the details, and there are a lot of non-trivial issues when trying to adapt flow algorithms to MPP:
- fees are very hard to correctly handle, especially when using "augmenting paths" to rebalance
- flow algorithms tend to exploit edges' capacity to their maximum, whereas for MPP we ideally want to balance equally between paths
- randomizing a flow is non trivial (and randomization plays an important part in …
> Find multi part route

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/KeyManager.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelTypesSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TestVectorsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
See commits description. They are independent and can be reviewed separately.
> Static key refactoring

- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/CommonCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LegacyChannelCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/db/sqlite/SqliteWalletDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
All LN protocol message must be stored as length-delimited, because they may have arbitrary trailing data.
Took the opportunity to restore byte alignment. It was mainly due to the use of single-bit `bool` codec.
The goal is to play safe and have simple codecs, so the existing codecs have been kept and moved to a `Legacy` inner object.
This is an alternative to #1239.
> Use length-delimited, byte-aligned codecs

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentError.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouterExceptions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
This is based on #1427, so please ignore the first commits.
We re-work the `MultiPartPaymentLifecycle` state machine to leverage the new MPP split algorithm exposed by the router. This greatly simplifies the FSM, removes a few hacks that were added to the `PaymentLifecycle`, and should make MPP split better for both mobile and server nodes.
It also allows re-enabling the use of MPP for trampoline relays to non-trampoline nodes (yay!).
I have done a lot of regtest testing to simulate Phoenix/Eclair-Mobile scenario, but nothing beats the real thing. Once this is approved, we should create testnet builds for Phoenix and Eclair-Mobile and extensively test that everything works.
Since it was already a lot of changes, I refrained from refactoring the `RouteRequest` part. We can improve this …
> Multipart FSM v2

- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
The MultipartPaymentLifecycle FSM sends a message as soon as it receives the preimage.
This allows removing the use of the node-relayer as a passthrough for fulfills, it can now simply listen to this event.
Long term, this could be sent to the event stream to share with more actors.
> MPP preimage received event

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
We were missing some cases where we should exclude temporarily unavailable channels.
The first missing case was when this was the last attempt (which impacts a lot the MPP scenario, since in MPP child payments do a single attempt).
The second missing case was when a channel from the routing hint is unavailable. Since we send the channel update to the router, the router was correctly removing it from the graph, but then we were re-adding it via the routing hints.
> More aggressive channel exclusion

- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
This is a collection of several small fixes/improvements:
- Ignore routing hints for our own channels
- Assume a bigger capacity than just the HTLC amount in routing hints
- Correctly handle balance change events for private channels
> Routing hints balance

- eclair-core/eclair-cli
- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/ExtraDirectives.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
Rename to `nodes`.
Allow filtering for specific `nodeId`s.
Fixes #1460
> Update allnodes API

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
The payment initiator retries trampoline payments by raising the fee/ctlv when the trampoline node couldn't find a route.
If we exhaust all attempts and the trampoline node keep returning a fee insufficient error, it actually means `RouteNotFound`, so we should translate the error for the end user (otherwise it's misleading, they think they should raise the fee but it's a red herring).
> Clarify trampoline route not found error

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/Sphinx.scala
We add two sets of unrelated metrics:
- Onion payload format: this is used to track when we'll be able to completely remove the legacy format. Right now only 3760 of the 5571 public nodes support `var_onion_optin`, so looks like it's not for tomorrow ;)
- HTLCs in-flight: we track the number of HTLCs in flight and the amount, per-channel and globally. This can be used to regularly update `eclair.max-htlc-value-in-flight-msat` and `eclair.max-accepted-htlcs` to the sweet spot between security and maximizing relays
> Onion payload and HTLC in-flight metrics

- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
- Test was not executed (because the "tests" variable was an iterator that was emptied by the call to .size())
- HTLC regex had to be updated to skip over the HTLC number that was added to the reference test vectors
> Fix transaction fee test

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/AuditDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteAuditDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteAuditDbSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
The `channelstats` API only returns results for the *outgoing* channels used when relaying.
It is misleading for users that the *incoming* channels aren't included in that API's results: they may incorrectly conclude that the incoming channels have no activity and should be closed.
This PR raises a couple questions though:
- I chose to attribute the fee only to the outgoing channel: maybe we should also reflect it in the incoming channel, since that channel participated in getting us this fee? But then if you sum the fees from all the results of the `channelstats` the result would be twice the fees you really collected, which may be an issue.
- I changed the trampoline behaviour regarding the `amount` reported compared to before: I now only take into account the amount that goes through …
> Fix channelstats (for real?)

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
This PR improves the way we handle feerate mismatch, giving more configuration flexibility to users and achieving better security while minimizing channel closures.
In https://github.com/ACINQ/eclair/commit/8e7f4916ce2be3bf2273f381b4aed3d1aae6dd98, we split the `max-feerate-mismatch` into two distinct configuration values. A low feerate is more dangerous than a high feerate (especially since it's the remote node that pays that fee).
In https://github.com/ACINQ/eclair/commit/e222318a108a1f9ae03c3afb367265830301c3d0 we relax the conditions for closing a channel when feerates don't match: if a channel has no HTLC, we can accept the remote feerate. It's only when an HTLC will be added to this channel that we need to evaluate whether we agree on feerate or not (in which case we close).
Fixes …
> Rework feerate mismatch

- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
We must not let feeratePerKw be 0, otherwise we trigger FeerateMismatch errors which isn't what we want to test.
This test regression was introduced in #1473
> Fix commitments fuzz test

- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
We handled empty amounts (field not specified at all) but not the case
where the amount was specified and equal to 0.
Fixes #1478
> Handle invoices with 0 amount

- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
Ping interval was hardcoded, the configuration value was ignored.
> fixup! Split the `Peer` in two (#1347)

- .github/workflows/main.yml
The `directory` configuration is ignored:
To my defense, it seems that the [codecov-action documentation](https://github.com/codecov/codecov-action#arguments) is inaccurate.
> Use file filter for scoverage upload

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/Onion.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/OnionCodecsSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
For an explanation of the feature see the PR from [c-lightning](https://github.com/ElementsProject/lightning/pull/3611).
Support for receiving and sending is added. This was tested against each Lightning implementations (`Sender -> Receiver`):
- `Eclair -> Eclair`
- `Eclair -> lnd`
- `Eclair -> c-lightning`
- `lnd -> Eclair`
Sending support [is not currently merged](https://github.com/ElementsProject/lightning/pull/3792) in c-lightning, so testing in this way `c-lightning -> Eclair` cannot be performed yet.
> Implement the KeySend feature, spontaneous payments

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
- eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
~~Currently we always merge the features defined by the user in `eclair.conf` with our `reference.conf` file, this led to some unexpected behaviors as described in #1434.
The PR corrects this behavior by making sure we never merge our default features with the user defined features, if the user provides some value then we use only that and if it doesn't we fallback to our hard-coded default features. Note that this makes impossible for a user to completely disable all features (i.e setting `features { }`) but i think it's okay because it doesn't affect any actual use-case.~~
Because of #1434 we need a way to let the user disable the default features. This PR explicitly allows to disable any feature from the configuration by setting `disabled` near the feature definition, all features are …
> Do not merge user provided features with defaults

- eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/KeyManager.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/LocalKeyManager.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/package.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Scripts.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelTypesSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/RecoverySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TestVectorsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
With this PR, it's possible to activate anchor outputs and have fully operating channels that use the anchor commitment format.
Interop testing has been done with lnd, and there is only one pending issue during mutual close, where they incorrectly compute the closing amounts (we are discussing this on the spec PR, it should be resolved soon).
However, for the sake of simplicity, this PR doesn't handle unilateral close scenario. This will be done in another, separate PR.
We don't do any kind of automatic fee bumping either; this will be done later, once we have PSBT support and once `bitcoind` offers the `psbtbumpfee` RPC (see https://github.com/bitcoin/bitcoin/pull/18654).
> Activate anchor output in channels

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
We previously refused to relay HTLCs that would result in a low expiry delta for the next node.
However it's not our decision to make, it's the remote's.
We should forward these HTLCs and let the remote decide whether they fail them because the expiry is too close or fulfill them.
> Relax relaying requirement on expiry

- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
If our remote peer doesn't correctly set transitive feature dependencies, we close the connection until they fix it.
> Verify feature graph in Init

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/KeyManager.scala
- eclair-core/src/main/scala/fr/acinq/eclair/crypto/LocalKeyManager.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/crypto/LocalKeyManagerSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/ExtraDirectives.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/FormParamExtractors.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
Fixes #1496
`Sign` by -> `Verified` by
```
$> eclair-cli signmessage --msg=$(echo -n 'hello, world' | base64)
{
"nodeId": "02ca7361934233f6d4defd4d792fb2ce2cd0b50c7605e6c5cd16006bcd5be2bf70",
"message": "aGVsbG8gd29ybGQK",
"signature": "1f730dce842c31b692dc041c2d0f00423d2a2a67b0c63c1a905d500f09652a5b1a036763a1603333fa589ae92d1f7963428ff170e976d0966a113f4b9f9d0efc7f"
}
```
```
$> eclair-clir verifymessage --msg=$(echo -n 'hello, world' | base64) --sig=1f730dce842c31b692dc041c2d0f00423d2a2a67b0c63c1a905d500f09652a5b1a036763a1603333fa589ae92d1f7963428ff170e976d0966a113f4b9f9d0efc7f
{
"valid": true,
"publicKey": "02ca7361934233f6d4defd4d792fb2ce2cd0b50c7605e6c5cd16006bcd5be2bf70"
}
```
The signature we return are in hexadecimal format. Lnd & C-lightning use a zbase32 format. To convert from …
> Add API commands to sign & verify arbitrary messages

- pom.xml
From scalatest's doc [1]:
> This minimizes or eliminates the need to search and scroll backwards
to find out what tests failed or were canceled. For large test suites,
the actual failure message could have scrolled off the top of the
buffer, making it otherwise impossible to see what failed.
[1] https://www.scalatest.org/user_guide/using_the_runner
> Show reminder of failed tests at the end

- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/ForwardHandler.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/PaymentHandler.scala
- eclair-core/src/test/resources/logback-test.xml
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
The IntegrationSpec's force-close tests were very hard to work with; I found out (with great pain) that they relied on many unwritten assumptions about event ordering which made them very brittle and hard to extend (in preparation for anchor outputs).
So I decided to re-work these tests to make them more robust and easier to extend, with the following changes:
- we don't need one node per force-close scenario, we can use different channels to the same node which makes the spec simpler.
- force-close tests now have better isolation: they create the channel at the beginning of the test, and the test ends with that channel closed.
- common parts have been refactored to reduce code duplication.
- force-close tests use `push_msat` to ensure both peers have an output in the commit tx, which …
> Refactor integration tests

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/NodeRelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
In preparation of the migration to typed actors, we need to remove the
use of `sender`, which doesn't exist in typed actors (and even returns
dead letters when mixing typed/untyped actors).
This also means that, in the tests, we should stop using the
`TestProbe.send()` method, which also relies on the recipient replying
to `sender`. Instead, we should use `targetActor ! msg` which guarantees
that the sender is void.
Using the `replyTo` pattern doesn't mix well with the `ask` pattern,
because we don't know the reference to the temporary actor. To deal with
that, we set `replyTo = ActorRef.noSender` which is a bit hackish.
NB: the [akka doc](https://doc.akka.io/docs/akka/current/typed/interaction-patterns.html#request-response-with-ask-from-outside-an-actor) shows the proper way of dealing …
> Use the `replyTo` pattern for Register messages

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Register.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/RelayerSpec.scala
This builds on #1514, please ignore the first commit.
Encapsulating error responses in a `Status.Failure` is convenient when
using the `ask` pattern because those messages are automatically
converted to a failed future.
It does however force us to use exceptions, and make things more
complicated, especially when moving to _typed_ actors.
> Remove `Status.Failure` in register responses

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/WatcherTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcher.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/WatcherSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/ZmqWatcherSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcherSpec.scala
- Correctly handle the case where a tx has both a sequence and locktime set (anchor output htlcs)
- Add tx publish tests to ZmqWatcher and ElectrumWatcher
- Add documentation on watcher types
> Improve blockchain watchers

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedInternalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/RustyTestsSpec.scala
Currently, the fundee computes it after receiving the `open_channel`
message, by calling `ChannelVersion.pickChannelVersion`.
Instead, we call this method in the `Peer` and add the resulting channel
version to the initialization parameters.
In the end, the behavior is exactly the same, but:
- it is more consistent with how the funder works;
- it may make sense to compute the channel version a bit earlier in the
process, because we may initiate a different kind of channel actor in
the future for some particular versions (?)
> Set the channel version in the init msg for the fundee

- README.md
- eclair-core/pom.xml
- eclair-core/src/test/resources/integration/bitcoin.conf
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/bitcoind/BitcoindService.scala
The only impactful change is that by default on regtest and testnet the `fallbackfee` (used when there is not enough historical data to correctly estimate the feerate) is now set to 0, whereas it was set to 0.0002 btc in previous versions. This change only impacts regtest and testnet, on mainnet this parameter has always been set to 0.
We set it manually in tests `bitcoin.conf` to preserve the past behavior (as recommended by bitcoind's release notes).
> Update to Bitcoin Core 0.20.1

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/PendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/pg/PgPendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqlitePendingRelayDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/receive/MultiPartPaymentFSM.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/NodeRelay.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/CommandCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/ChannelRelayerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/CommandCodecsSpec.scala
The replies are always ignored currently anyway. A new trait `NoReplyTo`
has been introduced. Those commands have a particular workflow because
they are persisted in the pending relay db.
> Do not reply to htlc settlement commands

- eclair-core/src/test/resources/application.conf
In some tests we are parsing logs to prevent race conditions. This
change adds more leeway to wait for logging events, because they may be
delayed when we run a lot of tests in parallel.
> More leeway for logging events in tests

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/transactions/Transactions.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LegacyChannelCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/transactions/TransactionsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/ChannelCodecsSpec.scala
This PR wraps up experimental support for anchor outputs by correctly handling all unilateral close scenarios.
Anchor outputs can now be activated and should work end-to-end (but we lack support for actually using the anchors and sighash changes to bump the fees - coming next).
It has been tested end-to-end against lnd master:
I had to change the `static_remotekey` behavior, @sstone let me know if that sounds good.
We used a `bitcoind` wallet address which made sense for `static_remotekey` without anchors, because our main output in the remote commitment was directly a p2wpkh to that address.
But with anchor outputs, our main output in the remote commitment is a p2wsh with a CSV-1 delay (`OP_PUSHDATA(paymentPubkey) :: OP_CHECKSIGVERIFY :: OP_1 :: OP_CHECKSEQUENCEVERIFY :: Nil`) so it …
> Anchor output: handle unilateral close

- eclair-core/src/test/resources/application.conf
We use the same timefactor (5x) than for untyped actors.
> Set a timefactor for typed actors tests

- eclair-node/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
Send basic channel events to websockets listeners:
* Channel open initiated
* Channel state change
* Channel closed
We only send basic, high-level data about these events.
If the listener is interested in details, it should call the `channelInfo`
API to get all of the channel's data.
Fixes #1509
> Add some channel events to websocket

- README.md
- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/bitcoind/rpc/BasicBitcoinJsonRPCClient.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/FxApp.scala
It makes sense to allow users to use a different wallet from the default one.
There's one important caveat: once set, users shouldn't change it while they have open channels.
We mention this clearly in the documentation, I don't think we need an explicit mechanism in the code to prevent starting with a different wallet (for example, if no channels are open, it's safe to change your wallet). It's use-at-your-own-risk if users choose to ignore the documented caveats. @darwin is that trade-off ok?
Fixes #1538
> Configure bitcoin wallet

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
We were previously only counting the additional HTLC at twice
the current feerate.
An HTLC in isolation doesn't make much sense: the feerate
applies to the whole commit tx. Our fee buffer needs to account
for a x2 feerate increase on the commit tx + an additional htlc.
Note that this introduces another subtlety. The commit tx fee at twice the
current feerate may actually be lower than the commit tx fee at the current
feerate (if the commit tx contains many htlcs that are only slightly above
the trim threshold).
See https://github.com/lightningnetwork/lightning-rfc/pull/740#discussion_r399740407 for context.
> Fixup funder fee buffer

- eclair-core/src/main/scala/fr/acinq/eclair/db/PaymentsDb.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartPaymentLifecycleSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
When using MPP, if we can't find a route, we need to add an entry to the
DB. Otherwise when users query their payment status, nothing will be
returned which is a bad UX.
Fixes #1512
> Add DB entry for payment router error

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Server.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/CommandCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageCodecs.scala
- eclair-core/src/test/resources/application.conf
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestUtils.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/RecoverySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedInternalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/SynchronizationPipe.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
Commands have to be of type `HasReplyToCommand` or `HasOptionalReplyToCommand`. The latter is mostly for commands which don't need replies except in tests.
With this change, there is no more `replying` in `Channel`, and a lot of `sender.send()` have been removed from tests, in preparation to full akka typed.
Supersedes #1533.
> Make all commands extend `Has*ReplyToCommand`

- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/ChannelRelayerSpec.scala
This makes it more difficult for attackers to "squat" high-capacity channels by sending HTLCs and then hodling them (filling up the 483 available pending HTLC slots).
It results in less locked liquidity during this kind of attacks because we preserve the highest-capacity channels.
Note: I also changed the way we test channel updates in the first commit because I didn't like the dependency on watching for logs, but if you don't like it I can revert that.
> [ChannelRelay] Prioritize lowest capacity channels

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Client.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/ClientSpawner.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Server.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerConnectionSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/SwitchboardSpec.scala
Features are now provided by the `switchboard`, in response to the
`PeerConnection.Authenticated` message.
The `switchboard` will also decide whether or not we sync with that
peer, depending on the `syncWhiteList` configuration.
This is an alternative to #1361. The `features`/`override-features`/`sync-whitelist` remain top-level parameters in `eclair.conf`, which was one of the main issues with #1361.
> Separate configuration for peer-connection

- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelTlv.scala
- eclair-core/src/test/scala/fr/acinq/eclair/wire/OpenTlvSpec.scala
We were previously using an encoding that was incompatible with TLV.
We keep the old format, but also understand the channel version when provided in a TLV field.
For backwards-compatibility, if the old format is provided, it will be preferred.
Since Phoenix only reads `open_channel` messages, it only needs support to *decode* this new TLV.
It will be on the eclair-node side that we will to switch to write the new TLV instead of the old format once we're confident enough Phoenix users have upgraded.
NB: this PR doesn't merge to master, but to `android-phoenix`
> [OpenChannel] Use TLV for channel version

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentLifecycleSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/ExtraDirectives.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
While `sendtoroute` was letting you provide a custom route as a list of nodes, it made it difficult to have fine-grain control over the channels used by payments.
The API now allows choosing the exact channels that will be used for the payment; in particular, this will be helpful when consolidating and rebalancing multiple channels to a given node.
Fixes #1472
We also fix a serialization regression introduced in #1520
> Send to channel route

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Switchboard.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
This is an alternative to #1498.
We were calling `nodeParams.features` from inside the channel, which is
problematic because we may have overriden those features for specific
peers. This is now fixed.
`IncomingPacket.decrypt` needs features to tell whether we are using
variable onion or not. What features should we use? Do we have an
unwritten rule that node-level features shouldn't be overriden? This
happens in the relayer and in the post-restart-htlc-cleaner.
> Fix override-features implementation

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/Relayer.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentPacketSpec.scala
There is no good reason to completely disable `var_onion_optin` and it can even be harmful: pending HTLCs after a restart may be lost if they used a variable-length onion, causing a loss of funds and potential channel closes.
> Prevent disabling `var_onion_optin`

- eclair-core/pom.xml
This will result in `eclair-core_2.13-<version>-tests.jar` file and allow to easily reuse Eclair testing classes in plugins.
> Use maven plugin to include tests

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/SynchronizationPipe.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/ChannelPaneController.scala
We're sending the type instead of sending an instantiated class...
NB: we're doing the same thing with `CMD_GETSTATE`, `CMD_GETSTATEDATA` and `CMD_GETINFO`: everywhere in the codebase we use it as if it were an object without any paramter, omitting the `replyTo`...I think the compiler should warn for these things, not sure if we need to fix it now for these commands, WDYT?
> Fix channel CMD_SIGN

- eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
- eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
Since we optionally support static-remotekey, we should allow our peers
to make it mandatory if they wish.
> Allow mandatory static-remotekey

- Dockerfile
Fixes #1560
That's the quick&easy solution but personally I don't like it, too much implicit things going on. The `ENTRYPOINT` directive uses the *shell form* which means that this line:
```
ENTRYPOINT JAVA_OPTS="$JAVA_OPTS" bash eclair-node/bin/eclair-node.sh -Declair.datadir=$ECLAIR_DATADIR
```
gets executed as this:
```
sh -c JAVA_OPTS="$JAVA_OPTS" bash eclair-node/bin/eclair-node.sh -Declair.datadir=$ECLAIR_DATADIR
```
Variables assignment before a shell command gets expanded and appended in a one-time environment used by the shell command. I've never liked this construct and prefer the more explicit use of `env`:
```
sh -c env JAVA_OPTS="$JAVA_OPTS" bash eclair-node/bin/eclair-node.sh -Declair.datadir=$ECLAIR_DATADIR
```
And to be even more explicit we might as well use the …
> fixes JAVA_OPTS expansion

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
When a channel gets confirmed while nodes are disconnected, recent versions of lnd sometimes fail to send their channel_reestablish message and instead send a funding_locked first (due to a race condition on their side).
When that happens, the channel stays stuck in the SYNCING state.
To avoid that, we trigger a reconnection until the race condition is eventually won by the channel_reestablish.
> Add workaround for lnd sync issue

- eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
In the revoked commit tx case, both nodes are competing to claim the HTLC outputs from the commit tx.
The test incorrectly assumed that node F would always win that race.
> Fix race condition in integration test

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
It's important in particular to highlight the case where an HTLC is half-fulfilled or half-failed.
> Clarify crossSign helper functions

- eclair-core/src/main/scala/fr/acinq/eclair/Features.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentRequest.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentInitiator.scala
- eclair-core/src/test/scala/fr/acinq/eclair/FeaturesSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentRequestSpec.scala
The `supportedMandatoryFeatures` set made less and less sense as we start supporting more features and allowing users to turn features on and off depending on the peers they connect to.
> Rework features compatibility

- README.md
- docs/Configure.md
- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeEstimator.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/StartupSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
When we have a trusted relationship with some of our peers (business relations, family members, our own mobile wallet, etc) it makes sense to relax the feerate mismatch constraint.
This must be done per-node, to avoid leaving the gates open for attackers.
> Add per-node feerate tolerance

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/Autoprobe.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RoutingSyncSpec.scala
Currently a `Symbol("data")` is used, this PR replaces it with dedicated `case object GetRouterData`. It's going to be used in plugin so it seems like a good idea to harden it.
> Add a case object to get router data

- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumxService.scala
> Increase docker timeouts for electrumx in tests

- eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/NodeRelayerSpec.scala
This test was randomly failing because of a race condition: we sometimes sent the payment failure before the payment FSM asked for routes, so it was ignored and the test could not progress.
> Fix NodeRelayer flaky test

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/PluginParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelEvents.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Auditor.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/HelpersSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/GUIUpdater.scala
- eclair-node/src/main/scala/fr/acinq/eclair/Boot.scala
- eclair-node/src/main/scala/fr/acinq/eclair/Plugin.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
This is continuation of https://github.com/ACINQ/eclair/pull/1580 (rather than wrestling with git I've decided to send a new PR). It follows suggestions outlined in https://github.com/ACINQ/eclair/commit/9d63b94c3bd028e5b6fec4fbbb87ad509eea5bd0.
> htlc post restart 4

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
ℹ️ this is a PR to `android-phoenix`
For small channels we blindly accept feerate from funder.
This is a temporary fix to allow making payment in high fees
environment and will be removed when "anchor outputs" is deployed
> High fee tolerance for small channels

- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/MultiPartPaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/send/PaymentLifecycle.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Validation.scala
Since Phoenix has a low number of channels and discards the whole public network graph, we can be more aggressive with what we log without flooding the logs.
This information will be very helpful to troubleshoot issues when users send multipart payments.
> Add more path finding logs

- eclair-core/src/test/scala/fr/acinq/eclair/router/AnnouncementsSpec.scala
A simple test which makes sure `nodeParams.nodeId` is always `nodeParams.privateKey.publicKey`. Maybe not needed but `nodeId` can be defined as something different while should not be.
> Add a nodeId equality test

- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
When the recipient is a direct peer, we can use the accurate knowledge of our local channels instead of hard-coded MPP parameters to choose the number of routes and the minimum route amount.
This change makes it possible to easily send all local funds in one payment when we're directly connected to the recipient.
@dpad85 I'll cherry-pick this commit on the `android-phoenix` branch once this is merged. It made me think that we probably want to change the default (15000 sats, 6 parts) for eclair-mobile MPP: no-one has complained yet, but maybe (1 000 sat, 10) would be better suited for a wallet.
> Improve MPP-send for direct channels

- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouteCalculationSpec.scala
When the recipient is a direct peer, we can use the accurate knowledge
of our local channels instead of hard-coded MPP parameters to choose
the number of routes and the minimum route amount.
This change makes it possible to easily send all local funds in one
payment when we're directly connected to the recipient.
NB: this PR imports in `android-phoenix` a fix that has been committed to `master`.
> Improve MPP-send for direct channels (#1599)

- eclair-core/src/main/scala/fr/acinq/eclair/router/RouteCalculation.scala
We were previously ommitting the nodeId from graph edge, which means we add duplicate edges but couldn't know which one was for which direction.
With that change it should be very easy to reproduce and understand path-finding issues.
NB: this is a PR to the `android-phoenix` branch.
> Path-finding: log edge direction

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
It turns out that:
- `def timedOutOutgoingHtlcs(blockHeight: Long): Set[wire.UpdateAddHtlc]` defined in `AbstractCommitments` is currently only used in `Commitments` object and nowhere else.
- Logic in HC commitments object can be simplified if `timedOutOutgoingHtlcs` takes additional arguments besides `blockHeight`.
So it makes sense to just remove `timedOutOutgoingHtlcs` from `AbstractCommitments` and let HC commitments object to do things differently internally without implementing of (useless) `timedOutOutgoingHtlcs`.
> Remove `timedOutOutgoingHtlcs` from AbstractCommitments

- eclair-core/src/main/scala/fr/acinq/eclair/wire/Onion.scala
It was implicitly doing an MPP between t2 and f, but that was misleading.
MPP is now explicitly drawn to prevent confusion.
> Clarify trampoline to legacy diagram

- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/PluginParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/PeerConnection.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/ReconnectionTask.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/ReconnectionTaskSpec.scala
Discussed at https://gitter.im/ACINQ/developers?at=5fa1289c2a3544071500e1b3, this will allow message-enabled plugins to keep a connection open to a given node even if there are no channels left.
> Allow plugins to force reconnect

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/HeadersOverDns.scala
When we query future blocks that bitcoinheaders.net doesn't have, instead of returning a DNS resolve error, it returns a DNS response without a block header.
We want to avoid logging it as an error, so we check for this specific case.
> Clean up bitcoinheaders error logs

- eclair-core/src/main/scala/fr/acinq/eclair/CheckElectrumSetup.scala
We have a background task that periodically checks the blockchain to
detect unexpected transactions, as they could be cheating attempts.
When cooperatively closing a channel, in the `NEGOTIATING` state, peers
exchange signatures in order to converge on a feerate for the mutual
close transaction. Any transaction exchanged during this negotiation
process is valid and may be published, even if the counterparty dies
abruptly before converging, due to e.g. connectivity issues.
Therefore, the electrum background check needs to take those
transactions into account and not flag them as potential cheating
attempts. We already do that when we are in the `CLOSING` state, as
there may be competing mutual closes.
> Take mutual close txes into account in Electrum background check

- .github/workflows/main.yml
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/EarnDotComFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdogSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/watchdogs/ExplorerApiSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/watchdogs/HeadersOverDnsSpec.scala
These tests have been flaky because external APIs tend to be down or throttle our calls. and we don't want our test suite to fail because of that.
In practice it's enough if developers run these tests locally once in a while.
> [CI] Exclude tests that call external APIs

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LightningMessageTypes.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
There are two issues:
1. because we forward commands *before* writing to disk in
`PendingRelayDb.safeSend` in order to reduce latency, there is a race
where the channel can process and acknowledge the command before the
db write. As a result, the command stays in the pending relay db and
will be cleaned up by the post-restart-htlc-cleaner at next restart.
2. in the general case, the channel acknowledges commands *before* it
writes its state to disk, which opens a window for losing the command
if we stop eclair at that exact time.
In order to fix 2., we introduce a new `acking` transition method, which
will be called after `storing`. This method adds a delay before actually
acknowledging the commands, which should be more than enough to solve 1.
I'm not sure we need that additional delay, …
> Ack htlc settlement commands after writing state

- eclair-core/src/main/scala/fr/acinq/eclair/PluginParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/PostRestartHtlcCleaner.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PostRestartHtlcCleanerSpec.scala
This is a bunch of small changes to make `CustomCommitmentsPlugin` methods easier to works with.
> Improve CustomCommitmentsPlugin methods

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/tor/TorProtocolHandler.scala
This is useful to redirect incoming tor traffic to eclair-front.
> Allow overriding of Tor target

- eclair-node/src/main/scala/fr/acinq/eclair/api/JsonSerializers.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
Thanks to recent changes, the `channelId` is available in `ChannelStateChanged`.
We now propagate this information to websocket channel events.
> Add channelId to websocket event

- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/Monitoring.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/BitcoinCoreFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/EarnDotComFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FallbackFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/SmoothFeeProvider.scala
- eclair-core/src/main/scala/fr/acinq/eclair/db/sqlite/SqliteFeeratesDb.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitcoinCoreFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/BitgoFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/DbFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/EarnDotComFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FallbackFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/SmoothFeeProviderSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/f/ShutdownStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/db/SqliteFeeratesDbSpec.scala
* Retrieve the minimum fee required to enter our mempool
* Add a metric to track this value
* Remove fallback fee providers when Bitcoin Core is used
* Add a metric to track feerate retrieval errors
For fallback fee providers that don't have any mempool information, we default to the 1008 block target. It doesn't matter as these fee providers will not be used anyway.
> Retrieve bitcoin's mempool-min-fee

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/io/Peer.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/ChannelCodecs.scala
- eclair-core/src/main/scala/fr/acinq/eclair/wire/LegacyChannelCodecs.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/FuzzySpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ThroughputSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForAcceptChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/a/WaitForOpenChannelStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedInternalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingCreatedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/b/WaitForFundingSignedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingConfirmedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/c/WaitForFundingLockedStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/IntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/interop/rustytests/RustyTestsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
- eclair-node-gui/src/main/scala/fr/acinq/eclair/gui/controllers/OpenChannelController.scala
- eclair-node/src/main/scala/fr/acinq/eclair/api/Service.scala
- eclair-node/src/test/scala/fr/acinq/eclair/api/ApiServiceSpec.scala
It can be useful to override the default relay fees when opening channels to specific nodes.
Note that these initial relay fees are not persisted in the DB. That means that if your node reboots before the funding transaction confirms, the channel will be opened with the default relay fees, not the overridden values.
Here is the command to open a channel with overridden relay fees:
```
eclair-cli open --nodeId=<nodeId> --fundingSatoshis=500000 --feeBaseMsat=1000 --feeProportionalMillionths=10000
```
Fixes #1507
> Set initial relay fees during channel open

- eclair-core/src/main/scala/fr/acinq/eclair/Eclair.scala
- eclair-core/src/main/scala/fr/acinq/eclair/router/Router.scala
- eclair-core/src/test/scala/fr/acinq/eclair/EclairImplSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/integration/PaymentIntegrationSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/BaseRouterSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/router/RouterSpec.scala
The router can now return local channels, with all necessary information to build routing hints from these channels.
It's not eclair-core's responsibility to choose what channels to use in routing hints: this is really a wallet strategy, so each wallet should have its own heuristics to choose what channels to include (if any).
I think @btcontract was interested in these.
> Add router API for invoice routing hints

- eclair-core/src/main/resources/reference.conf
We need to be above 253 sat/kw, but 3 sat/byte is overkill.
> Set min-fee-rate to 2 sat/byte

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/fee/FallbackFeeProvider.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/fee/FallbackFeeProviderSpec.scala
Using the `copy` method is risky because it's easy to forget newly added
fields. Also the test didn't make much sense.
> Fix bug in enforceMinimumFeerate

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/NodeParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
Took the opportunity to improve the naming as well.
I also considered putting them under a  `providers` section, WDYT?
```
on-chain-fees {
providers {
min-feerate = 1 // minimum feerate in satoshis per byte
smoothing-window = 6 // 1 = no smoothing
timeout = 5 seconds // max time we'll wait for answers from a fee provider before we fallback to the next one
}
...
}
```
> Move fee provider conf

- Dockerfile
This fixes the Docker build which was failing due to the new child module `eclair-front`.
We should probably add a way to start an `eclair-front` from docker too.
> fixup! Distribute connection-handling on multiple machines (#1566)

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/PaymentPacket.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/CommitmentsSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/NormalStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
We were heavily using `Try`, which unfortunately loses the type of exception (in our case `ChannelException`) and prevents us from doing a complete pattern matching on all error cases.
I'm replacing that with an `Either[ChannelException, X]` where possible. The goal is to slowly move away from untyped exceptions.
This may be a dangerous change, so please review carefully!
> Improve channel exceptions

- eclair-node/src/main/resources/application.conf
Even after #1566, we want the default to be a standalone deployment.
> Use a local actorsystem by default

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/g/NegotiatingStateSpec.scala
If we have nothing at stake there is no need to negotiate and we accept
their fee right away.
⚠️ This is a small change but a bug here would be costly.
> Accept remote's closing fee when we have nothing at stake

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/ChannelTypes.scala
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/ChannelTypesSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/StateTestsHelperMethods.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
When a revoked commitment is published, we didn't correctly settle pending HTLCs, which could lead to upstream channel closure.
This would not cause a loss of funds (especially since we would gain funds from the revoked channel) but it's a temporary liquidity loss that we'd like to avoid.
I took this opportunity to rework the revoked close tests to cover more scenarios.
> Settle HTLCs revoked commit

- eclair-core/src/main/resources/reference.conf
- eclair-core/src/main/scala/fr/acinq/eclair/channel/Helpers.scala
- eclair-core/src/test/scala/fr/acinq/eclair/TestConstants.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/h/ClosingStateSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/MultiPartHandlerSpec.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/PaymentInitiatorSpec.scala
We activate static_remotekey by default (optional).
This is necessary since lnd will start making it mandatory in their next release.
> Activate static_remotekey by default

- eclair-core/src/main/scala/fr/acinq/eclair/PluginParams.scala
- eclair-core/src/main/scala/fr/acinq/eclair/Setup.scala
Otherwise we can't extend it in other projects.
> Make PluginParams a simple trait

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Commitments.scala
- eclair-core/src/main/scala/fr/acinq/eclair/payment/Monitoring.scala
We put nodes in buckets in order to build a distribution and monitor
incoming/outgoing payment count/volume by node id.
> Measure the distribution of payments across nodes

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumClient.scala
- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWatcher.scala
- eclair-core/src/test/scala/fr/acinq/eclair/blockchain/electrum/ElectrumWalletBasicSpec.scala
Electrum can return unconfirmed txs in an address' history. When that happens, we should not try to fetch its confirmed position, it will return an error.
We simply need to ignore these events and wait for the tx to confirm.
I'll cherry-pick this commit to the `android` and `android-phoenix` branches once it's on `master`.
> ElectrumWatcher: fix for unconfirmed txs

- eclair-core/src/main/scala/fr/acinq/eclair/payment/relay/ChannelRelay.scala
- eclair-core/src/test/scala/fr/acinq/eclair/payment/relay/ChannelRelayerSpec.scala
Channel is still used if requested CLTV delta equals or is heigher than advertized
> Relax expiryDelta requirement when selecting a channel to relay

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/io/PeerSpec.scala
This scenario was correctly handled, but we were missing test coverage.
> Add test for duplicate temporary channel id

- eclair-core/src/test/scala/fr/acinq/eclair/integration/ChannelIntegrationSpec.scala
When a channel goes to the CLOSED state, the actor will stop itself.
We were previously sending messages to the actor asking for its state, which returns a failure when the actor is stopped. We can simply listen to state events to safely get the same result.
> Fix rare race conditions in integration tests

- BUILD.md
It seems like we need to compile eclair-core's tests for the front (but we don't require running them).
Another solution could be to add hooks in `pom.xml` to make `-Dmaven.test.skip` work, but that's really not my cup of tea :sweat_smile: 
Fixes #1657
> Update build instructions for front

- eclair-core/src/main/scala/fr/acinq/eclair/channel/Channel.scala
- eclair-core/src/test/scala/fr/acinq/eclair/channel/states/e/OfflineStateSpec.scala
We had a delay mechanism before re-enabling reconnected channels to avoid creating frequent channel updates on flappy connections and flooding the network with unnecessary gossip.
We don't need this protection for private channels since they're not gossiped to the rest of the network. And in the case of private channels to mobile wallets, we don't want to add any delay, otherwise the reconnected channel will not be in the router's graph and we'll have issues routing payments to that wallet (especially if they quickly disconnect, before our 10-seconds delay).
> More aggressively re-emit private channel updates

- eclair-core/src/main/scala/fr/acinq/eclair/blockchain/watchdogs/BlockchainWatchdog.scala
Actor names cannot conflict.
Even though blockchain watchdog actors stop themselves after fetching block data, when blocks are found in a short interval, we may end up with multiple actors of the same type simultaneously alive, so we need them to have unique names.
The blockcount isn't sufficient to make their names unique because forks can happen.
Fixes #1665
> Blockchain watchdogs use unique actor name
